Repository canonical/vanilla-framework, pull requests merged in 2018-11, with the labels that each got.

#2052 Slider input
  scss/_patterns_slider.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Status: Review

#2054 Stepped list update
  docs/en/patterns/lists.md
  examples/patterns/lists/lists-stepped-detailed.html
  examples/patterns/lists/lists-stepped.html
  scss/_patterns_lists.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Status: Review

#2057 Fixes broken links on Icons page
  docs/en/patterns/icons.md
Labels: Review: Code +1, Review: QA +1

#2061 Corrects colorpicker and datetime errors
  scss/_base_forms.scss
Labels: Review: Code +1, Review: QA +1

#2063 Fix strip borders
  scss/_patterns_strip.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Status: Review

#2062 Remove the Blink mac system font from the base font family.
  scss/_settings_font.scss
Labels: Review: Code +1, Status: Review

#2056 Remove offset from focus state
  scss/_base_forms.scss
  scss/_global_functions.scss
  scss/_patterns_accordion.scss
  scss/_patterns_modal.scss
  scss/_patterns_slider.scss
  scss/_patterns_switch.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Status: Review

#2069 Update <abbr> cursor to 'help'
  scss/_base_typography.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2064 Add a method of handling form validation for select dropdowns
  docs/en/base/forms.md
  examples/patterns/forms/form-validation.html
  scss/_patterns_form-validation.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Status: Review
