Repository canonical/vanilla-framework, pull requests merged in 2018-02, with the labels that each got.

#1586 Fix notifications.scss linting error
  scss/_patterns_notifications.scss
Labels: Review: Code +1

#1588 Fix matrix borders
  scss/_patterns_matrix.scss
Labels: Review: Code +1, Review: QA +1

#1589 Sync up design specs with scss components pt.1
  scss/_base_button.scss
  scss/_patterns_accordion.scss
  scss/_patterns_aside.scss
  scss/_patterns_buttons.scss
  scss/_patterns_card.scss
  scss/_patterns_matrix.scss
  scss/_patterns_media-object.scss
  scss/_patterns_modal.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1
