Repository canonical/vanilla-framework, pull requests merged in 2018-04, with the labels that each got.

#1663 Update the cards design link to the correct one
  docs/en/patterns/card.md
Labels: Review: Code +1

#1700 1658: Fix issue with navigation logo sizing
  examples/patterns/navigation/default.html
  examples/patterns/search-box/navigation.html
  scss/_patterns_navigation.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#1694 Re-add max-height of card header image
  scss/_patterns_card.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#1701 Add margin overrides to allow swapping div with p
  scss/_patterns_code-snippet.scss
Labels: Review: Code needed, Status: Review

#1699 Fix box-shadows - #1672
  scss/_patterns_card.scss
  scss/_patterns_notifications.scss
Labels: Review: Code +1, Review: Design +1

#1697 Increase space under ul to address issue on insights page
  scss/_base_lists.scss
  scss/_base_typography.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#1704 Address 1668 - spacing around checkboxes in p-lists
  scss/_base_forms.scss
  scss/_patterns_lists.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, v1.7.0-alpha-1

#1705 fix row in nav when no p-navigation__row class is present
  scss/_patterns_navigation.scss
Labels: Review: Code +1, Review: QA +1, Status: Review

#1706 Adjust spacing between icon and meta item in media object (1666)
  scss/_patterns_media-object.scss
Labels: Review: Code +1, Review: Design +1, Status: Review

#1696 Add baseline grid conditionally.
  _jekyll/_layouts/default.html
Labels: Review: Code +1, Status: Review

#1707 Fix 1674 - strip padding
  scss/_patterns_footer.scss
  scss/_patterns_strip.scss
  scss/_settings_spacing.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#1710 Separate u-align and u-align-text utilities
  examples/utilities/align.html
  scss/_base_typography.scss
  scss/_utilities_content-align.scss
Labels: Review: Code +1, Review: QA +1

#1712 Fix #1670 - gap in matrix when no image is present
  scss/_patterns_lists.scss
  scss/_patterns_matrix.scss
  scss/_patterns_navigation.scss
Labels: Review: Code +1, Review: QA +1, Status: Review

#1702 Make u-vertically-center work with img elements
  scss/_utilities_vertically-center.scss
Labels: Review: Code +1, Review: QA +1

#1714 Update to v1.7.0-beta-1
  package.json
  scss/_settings_system.scss
Labels: Review: Code +1, Status: Review

#1733 Change the term 'theme' for 'framework'
  docs/en/index.md
Labels: Review: Code +1, Status: Review

#1734 1721: Remove margins on .p-code-snippet__action
  scss/_patterns_code-snippet.scss
Labels: Review: Code +1, Review: QA +1, Status: Review

#1742 set VF_ENV to PRODUCTION to disable debug baseline grid
  _jekyll/_layouts/default.html
Labels: Status: Review

#1744 Inline-images: Fix image distortion
  scss/_patterns_inline-images.scss
Labels: Review: Code +1, Review: QA +1, Status: Review

#1745 Improve heading-icon to accomodate muted heading to h3 next to icon
  scss/_patterns_heading-icon.scss
  scss/_settings_spacing.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Status: Review

#1755 Bump version to 1.7.0-beta-2
  package.json
  scss/_settings_system.scss
Labels: Review: Code +1, Status: Review

#1762 Revert heading icon changes from #1745, and amend with new spacing
  scss/_patterns_heading-icon.scss
  scss/_settings_spacing.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#1764 Bump version to 1.7.0-beta-2.1
  package.json
  scss/_settings_system.scss
Labels: Review: Code needed, Status: Review

#1763 Fixes for various Vanilla docs bugs
  docs/en/base/forms.md
  examples/patterns/card/header.html
  examples/patterns/image/bordered.html
  examples/patterns/image/shadowed.html
  examples/patterns/inline-images.html
  examples/patterns/matrix.html
  examples/patterns/media-object/media-object-circ-img.html
  examples/patterns/media-object/media-object-large.html
  examples/patterns/media-object/media-object.html
  examples/patterns/strips/accent.html
  examples/patterns/strips/deep.html
  examples/patterns/strips/image.html
  examples/patterns/strips/is-bordered.html
  examples/patterns/strips/shallow.html
  examples/patterns/tables/table-expanding.html
  examples/utilities/align.html
  examples/utilities/image-position/bottom-left.html
  examples/utilities/image-position/bottom-right.html
  examples/utilities/image-position/bottom.html
  examples/utilities/image-position/left.html
  examples/utilities/image-position/right.html
  examples/utilities/image-position/top-left.html
  examples/utilities/image-position/top-right.html
  examples/utilities/image-position/top.html
Labels: Review: Code +1, Review: QA +1, Status: Review

#1771 Remove margin and padding from <code> + add vertical padding to <pre>
  scss/_base_code.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Status: Review

#1778 Reduce vertical spacing on examples directory + prettify markup
  index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Status: Review

#1781 Add !default to all settings
  scss/_settings_grid.scss
  scss/_settings_spacing.scss
Labels: Review: Code +1, Review: QA +1, Status: Review

#1773 Remove negative margin from consecutive .p-matrix__desc
  examples/patterns/matrix.html
  scss/_patterns_matrix.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1
