Repository canonical/vanilla-framework, pull requests merged in 2018-03, with the labels that each got.

#1601 Creates “Tables” category
  docs/en/metadata.yaml
Labels: Review: Code +1, Review: QA +1

#1611 Add a title to the search input in the docs template
  docs/template.html
Labels: Review: Code +1, Review: QA +1

#1600 Add file size check to CI
  .travis.yml
  tests/file-size-lint.sh
Labels: Review: Code +1, Review: QA +1

#1617 Correct box shadow and font-size on Tabs pattern
  scss/_patterns_card.scss
  scss/_patterns_tabs.scss
Labels: Review: Code +1, Review: QA +1

#1615 1609: Optimise icons
  scss/_patterns_icons.scss
  tests/file-size-lint.sh
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#1620 Update copyright date in Footer example
  examples/patterns/footer.html
Labels: Review: Code +1

#1618 Component spec updates #2
  scss/_base_forms.scss
  scss/_patterns_form-validation.scss
  scss/_patterns_heading-icon.scss
  scss/_patterns_lists.scss
  scss/_patterns_notifications.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#1619 Documentation content fixes
  docs/en/base/forms.md
  docs/en/patterns/card.md
  docs/en/patterns/form-validation.md
  docs/en/patterns/forms.md
  docs/en/patterns/images.md
  docs/en/patterns/links.md
  docs/en/patterns/search-box.md
  docs/en/utilities/image-position.md
  examples/patterns/card/default.html
  examples/patterns/card/header.html
  examples/patterns/forms/form-inline.html
  examples/patterns/forms/form-stacked.html
  examples/patterns/forms/form-validation.html
Labels: Review: Code +1, Review: QA +1

#1616 Add the MAAS layout for testing
  examples/templates/maas-layout.html
Labels: Review: Code +1, Review: QA +1

#1612 Expands “Media” to “Images and media”
  docs/en/metadata.yaml
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#1635 Bump to v1.6.7
  docs/template.html
  scss/_settings_system.scss
Labels: Review: Code +1

#1636 Fix media object linting errors
  scss/_patterns_media-object.scss
Labels: Review: Code needed, Review: QA needed

#1638 Remove redundant Form docs pages
  docs/en/base/forms.md
  docs/en/metadata.yaml
Labels: Review: Code +1, Review: QA +1

#1649 Bump the version to 1.7.0-alpha
  package.json
Labels: Review: Code +1

#1650 Fixed some lint errors for the release of the beta
  scss/_patterns_media-object.scss
Labels: Review: Code +1, Review: QA +1

#1653 Final round of lint fixes
  scss/_patterns_media-object.scss
Labels: Review: Code needed

#1656 Remove baseline grid from examples pages
  _jekyll/_layouts/default.html
Labels: Review: Code needed, Review: QA needed

#1657 Add Jekyll template changes to master
  _jekyll/_layouts/default.html
Labels: Review: Code needed
