Repository canonical/vanilla-framework, pull requests merged in 2018-08, with the labels that each got.

#1937 Update fieldset to match the design spec
  scss/_base_forms.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#1953 Fix missing 'default' flag in placeholders settings (#1950)
  scss/_settings_placeholders.scss
Labels: Review: Code needed, Review: QA needed

#1936 Add button has-icon state class
  docs/en/patterns/buttons.md
  examples/patterns/buttons/icon.html
  scss/_base_button.scss
  scss/_patterns_buttons.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#1956 Entrypoint for talisker gevent workers
  docs/.gitignore
  docs/Dockerfile
  docs/entrypoint
  docs/package.json
  docs/requirements.txt
  docs/run
Labels: Review: Code needed, Review: QA needed

#1913 p-cards: Apply fixed padding
  scss/_base_placeholders.scss
  scss/_patterns_card.scss
  scss/_settings_spacing.scss
Labels: Review: Code +1, Review: QA +1

#1963 Add sub-heading example to documentation
  docs/en/base/typography.md
  examples/base/sub-headings.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1964 Add new greys to color palette
  .spelling
  docs/en/settings/color-settings.md
  scss/_settings_colors.scss
Labels: Review: Code +1, Review: QA +1

#1966 Update accessible text on docs example
  docs/en/settings/color-settings.md
Labels: Review: Code +1, Review: QA +1

#1972 1947 slider pattern fix
  scss/_patterns_slider.scss
Labels: Review: Code +1, Review: QA +1

#1976 Update bottom border on list components
  scss/_base_lists.scss
  scss/_patterns_lists.scss
Labels: Review: Code +1, Review: QA +1

#1978 Remove unnecessary entrypoint files
  docs/entrypoint
  docs/requirements.txt
Labels: Review: Code +1, Review: QA +1

#1979 Add net-tools
  docs/Dockerfile
Labels: Review: Code +1
