Repository canonical/vanilla-framework, pull requests merged in 2019-10, with the labels that each got.

#2570 Add subset latin fonts
  docs/_layouts/examples.html
  docs/base/typography.md
  scss/_base_fontfaces.scss
  scss/_settings_font.scss
Labels: Performance ⚡️, Review: Code +1, Review: QA +1

#2578 Fix icons in buttons. Document is-light/dark classes. Add more icon button examples
  docs/examples/patterns/buttons/icon.html
  docs/patterns/buttons.md
  scss/_patterns_buttons.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2571 Theming correction
  docs/patterns/navigation.md
  scss/_base_forms-tick-elements.scss
  scss/_base_hr.scss
  scss/_base_typography-max-widths.scss
  scss/_base_typography.scss
  scss/_patterns_navigation.scss
  scss/_patterns_search-box.scss
  scss/_patterns_subnav.scss
  scss/_settings_colors.scss
  scss/_settings_themes.scss
Labels: Review: Code +1, Review: QA +1

#2581 #2579 - Fix Details title in docs.
  docs/base/details.md
Labels: Review: Code +1, Review: QA +1

#2583 #1960 - Add padding to search box so text doesn't go underneath.
  scss/_patterns_search-box.scss
Labels: Review: Code +1, Review: QA +1

#2582 #2475 - Rearrange select validation priorities.
  scss/_patterns_form-validation.scss
Labels: Review: Code +1, Review: QA +1

#2587 Update table-sortable.html
  docs/examples/patterns/tables/table-sortable.html
Labels: Review: Code +1, Review: QA +1

#2592 doc page for theming
  docs/patterns/navigation.md
  docs/settings/color-settings.md
  scss/_base_forms-tick-elements.scss
  scss/_base_hr.scss
  scss/_patterns_navigation.scss
  scss/_patterns_search-box.scss
  scss/_patterns_subnav.scss
  scss/_settings_themes.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2594 2.4.1
  docs/index.md
  package.json
  scss/_settings_system.scss
Labels: Review: Code +1

#2596 Update docs vanilla dependency to 2.4.1
  package.json
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2598 Removes <span> elements from <blockquote> example
  docs/examples/base/blockquotes.html
Labels: Review: Code +1, Review: QA +1

#2599 Update links and references for color-theming
  docs/settings/color-settings.md
Labels: Review: Code +1, Review: QA +1

#2607 Add icons accessibility callout
  docs/patterns/icons.md
Labels: Review: Code +1, Review: QA +1
