Repository canonical/vanilla-framework, pull requests merged in 2019-05, with the labels that each got.

#2296 Fix nav search
  docs/_layouts/default.html
  docs/redirects.map
Labels: Review: Code +1, Review: QA +1

#2273 Cssgrid
  docs/examples/patterns/card/overlay.html
  docs/examples/patterns/grid/default.html
  docs/examples/patterns/grid/empty-columns.html
  docs/examples/patterns/grid/incorrect-empty-columns.html
  docs/examples/patterns/grid/nested-medium.html
  docs/examples/patterns/grid/nested-small.html
  docs/examples/patterns/grid/nested.html
  docs/examples/patterns/grid/offsets.html
  docs/examples/patterns/icons/icons-dark.html
  docs/examples/patterns/icons/icons-light.html
  docs/examples/patterns/icons/icons-social.html
  docs/examples/patterns/lists/lists-stepped-detailed.html
  docs/examples/patterns/lists/lists-stepped.html
  docs/examples/patterns/strips/accent.html
  docs/examples/templates/maas-layout.html
  docs/examples/templates/typographic-spacing.html
  docs/examples/templates/vertical-spacing.html
  docs/examples/utilities/equal-height.html
  docs/patterns/grid.md
  scss/_base_tables.scss
  scss/_patterns_divider.scss
  scss/_patterns_grid.scss
  scss/_patterns_lists.scss
  scss/_settings_grid.scss
  scss/_utilities_equal-height.scss
  scss/_utilities_vertically-center.scss
Labels: Review: Code +1, Review: QA +1

#2303 Bump project version fo 2.0.0-alpha
  package.json
  scss/_settings_system.scss
Labels: Review: Code +1

#2304 Replace chevron icon with guillemette
  scss/_base_forms.scss
  scss/_patterns_icons.scss
  scss/_patterns_subnav.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2306 fix rule order
  scss/_base_forms.scss
Labels: Review: Code +1, Review: QA +1

#2310 fix strip selector so class order doesn't matter
  scss/_patterns_strip.scss
Labels: Review: Code +1

#2308 Bordered row
  docs/examples/patterns/grid/bordered.html
  scss/_base_hr.scss
Labels: Review: Code +1, Review: QA +1

#2309 Introduces new variable to change the font-weight for bold fonts
  scss/_base_typography-definitions.scss
  scss/_patterns_links.scss
  scss/_patterns_table-of-contents.scss
  scss/_settings_font.scss
Labels: Review: Code +1, Review: QA +1

#2311 Upgraded Husky config
  package.json
Labels: Review: Code +1, Review: QA +1

#2315 remove duplicate code. convert margin to padding so it pushes border down
  scss/_patterns_card.scss
Labels: Review: Code +1, Review: QA +1

#2316 fix tick position
  scss/_patterns_lists.scss
Labels: Review: Code needed, Review: QA needed

#2312 u-min-margin--bottom: ensure it keeps text on baseline grid
  docs/examples/patterns/card/overlay.html
  docs/examples/templates/vertical-spacing.html
  docs/examples/utilities/margin-collapse.html
  scss/_base_typography-definitions.scss
  scss/_base_typography.scss
  scss/_patterns_card.scss
  scss/_patterns_divider.scss
  scss/_patterns_lists.scss
  scss/_patterns_notifications.scss
  scss/_utilities_margin-collapse.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2321 Bump package version to 2.0.0-alpha.1
  package.json
  scss/_settings_system.scss
Labels: Review: Code +1

#2320 Fix base buttons class - .is--disabled to .is-disabled
  docs/examples/patterns/buttons/base.html
  scss/_base_button.scss
Labels: Review: Code +1, Review: QA +1

#2326 Refactor tooltips so that they no longer require class duplication
  docs/examples/patterns/tooltips.html
  scss/_patterns_tooltips.scss
Labels: Review: Code +1, Review: QA +1

#2344 Block cols
  scss/_patterns_grid.scss
Labels: Review: Code +1, Review: QA +1

#2345 Added clarification to media-object docs re: circular format needing square images
  docs/patterns/media-object.md
Labels: Review: QA +1

#2347 Fix 2289 (accordion)
  scss/_base_tables.scss
  scss/_patterns_accordion.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2346 Docs: reformat and clarify grid docs
  docs/patterns/grid.md
Labels: Review: Code +1, Review: QA +1

#2348 Stacked form: replace hardcoded layout with grid classes
  docs/examples/patterns/forms/form-stacked.html
  scss/_patterns_forms.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2318 Use run script v3.4.1
  .gitignore
  docs/Dockerfile
  docs/nginx.conf
  run
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2351 Ellipsise nav links longer than 20em
  scss/_patterns_navigation.scss
Labels: Review: Code +1, Review: QA +1

#2357 correct name of grid bordered row example
  docs/examples/patterns/grid/bordered.html
Labels: Review: Code +1, Review: QA +1

#2342 Includes the referenced margin collapse utility into typography
  scss/_base_placeholders-margin-collapse.scss
  scss/_base_typography-definitions.scss
  scss/_utilities_margin-collapse.scss
Labels: Review: Code +1, Review: QA +1

#2355 Docs: correct the path for the heading-icon examples.
  docs/patterns/heading-icon.md
Labels: Review: Code +1, Review: QA +1

#2358 update breakpoint documentaiton to match actual breakpoints
  docs/settings/breakpoint-settings.md
Labels: Review: Code +1, Review: QA +1

#2359 Bump project version to 2.0.0-beta
  package.json
  scss/_settings_system.scss
Labels: Review: Code +1

#2362 Placeholders refactor
  scss/_base.scss
  scss/_base_placeholders-fixed-width-container.scss
  scss/_base_placeholders-margin-collapse.scss
  scss/_base_placeholders.scss
  scss/_base_typography-definitions.scss
  scss/_patterns_grid.scss
  scss/_utilities_layout.scss
Labels: Review: Code +1, Review: QA +1

#2363 Bump package version to 2.0.0-beta.1
  package.json
  scss/_settings_system.scss
Labels: Review: Code +1
