Repository canonical/vanilla-framework, pull requests merged in 2019-02, with the labels that each got.

#2141 fix selectors in matrix
  scss/_patterns_matrix.scss
Labels: Review: Code needed, Review: Design +1, Review: QA needed

#2138 2.0 refactor
  examples/templates/typographic-spacing.html
  scss/_base_fontfaces.scss
  scss/_base_tables.scss
  scss/_base_typography-definitions.scss
  scss/_base_typography-heading-mixins.scss
  scss/_base_typography-max-widths.scss
  scss/_base_typography.scss
  scss/_patterns_form-help-text.scss
  scss/_patterns_form-validation.scss
  scss/_patterns_matrix.scss
  scss/_patterns_table-mobile-card.scss
  scss/_settings_spacing.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2144 2.0 Refactor: More extensive testcase markup
  examples/templates/typographic-spacing.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2149 Remove Google + icons
  docs/en/patterns/icons.md
  examples/patterns/icons/icons-social.html
Labels: Review: Code +1, Review: QA +1

#2148 Improve typographic spacing examples (new pr against branch develop)
  examples/templates/typographic-spacing.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2151 Back port docs changes to v1.8
  docs/en/patterns/icons.md
  docs/en/settings/color-settings.md
  docs/template.html
  examples/patterns/icons/icons-dark.html
  examples/patterns/icons/icons-light.html
  examples/patterns/icons/icons-social.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2152 1791 tooltip placement
  examples/patterns/tooltips.html
  scss/_patterns_tooltips.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2156 Add background-color to root element (html) so we don't rely on browser defaults
  scss/_base.scss
  scss/_base_background.scss
Labels: Review: Code +1, Review: QA +1

#2157 2100 spacing variable rename
  docs/en/settings/spacing-settings.md
  scss/_base_blockquotes.scss
  scss/_base_button.scss
  scss/_base_code.scss
  scss/_base_forms.scss
  scss/_base_hr.scss
  scss/_base_lists.scss
  scss/_base_media.scss
  scss/_base_placeholders.scss
  scss/_base_tables.scss
  scss/_patterns_accordion.scss
  scss/_patterns_breadcrumbs.scss
  scss/_patterns_buttons.scss
  scss/_patterns_card.scss
  scss/_patterns_code-copyable.scss
  scss/_patterns_code-numbered.scss
  scss/_patterns_contextual-menu.scss
  scss/_patterns_divider.scss
  scss/_patterns_footer.scss
  scss/_patterns_form-validation.scss
  scss/_patterns_grid.scss
  scss/_patterns_heading-icon.scss
  scss/_patterns_lists.scss
  scss/_patterns_matrix.scss
  scss/_patterns_media-object.scss
  scss/_patterns_navigation.scss
  scss/_patterns_notifications.scss
  scss/_patterns_pagination.scss
  scss/_patterns_pull-quotes.scss
  scss/_patterns_search-box.scss
  scss/_patterns_strip.scss
  scss/_patterns_switch.scss
  scss/_patterns_table-mobile-card.scss
  scss/_patterns_tabs.scss
  scss/_patterns_tooltips.scss
  scss/_settings_grid.scss
  scss/_settings_spacing.scss
  scss/_utilities_baseline-grid.scss
  scss/_utilities_embedded-media.scss
Labels: Review: Code +1, Review: QA +1

#2160 Remove media query so that .u-vertically-center works at all viewports
  scss/_utilities_vertically-center.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2161 Restyle primary navigation
  scss/_patterns_navigation.scss
  scss/_settings_colors.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2162 Add max-width to <label> elements
  scss/_base_typography.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2164 Remove $px var in preparation for font-size change
  scss/_base_button.scss
  scss/_base_forms.scss
  scss/_base_hr.scss
  scss/_base_placeholders.scss
  scss/_base_tables.scss
  scss/_patterns_accordion.scss
  scss/_patterns_buttons.scss
  scss/_patterns_card.scss
  scss/_patterns_code-copyable.scss
  scss/_patterns_contextual-menu.scss
  scss/_patterns_divider.scss
  scss/_patterns_lists.scss
  scss/_patterns_matrix.scss
  scss/_patterns_navigation.scss
  scss/_settings_placeholders.scss
  scss/_settings_spacing.scss
  scss/_utilities_vertical-spacing.scss
Labels: Review: Code +1, Review: QA +1

#2165 unhardcode tooltip triangle dimensions and offsets
  scss/_patterns_tooltips.scss
Labels: Review: Code +1, Review: QA +1

#2155 Added new subnavigation pattern, documented and added example
  .spelling
  docs/en/patterns/navigation.md
  examples/patterns/navigation/subnav.html
  scss/_base_blockquotes.scss
  scss/_base_placeholders.scss
  scss/_base_tables.scss
  scss/_patterns_card.scss
  scss/_patterns_navigation.scss
  scss/_patterns_subnav.scss
  scss/_patterns_tabs.scss
  scss/_settings_spacing.scss
  scss/_vanilla.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2172 Add updated slack icon
  docs/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#2171 Add u-no-print utility to exclude elements from printed pages
  docs/en/metadata.yaml
  docs/en/utilities/no-print.md
  examples/utilities/no-print.html
  gulp/parker.js
  scss/_utilities_no-print.scss
  scss/_vanilla.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1
