Repository canonical/vanilla-framework, pull requests merged in 2019-06, with the labels that each got.

#2366 Update README to match docs/index.md
  README.md
Labels: Review: Code +1

#2323 Add new variable - with default values - for navigation border and text colours
  scss/_patterns_navigation.scss
  scss/_patterns_subnav.scss
  scss/_patterns_tabs.scss
  scss/_settings_colors.scss
Labels: Review: Code +1, Review: QA +1

#2369 tfoot border, remove leftover strong link references
  docs/examples/base/table.html
  docs/examples/patterns/list-tree.html
  scss/_base_tables.scss
Labels: Review: Code +1, Review: QA +1

#2372 Kill gulp with fire
  .spelling
  CONTRIBUTING.md
  README.md
  docs/_layouts/default.html
  docs/building-vanilla.md
  docs/index.md
  docs/patterns/grid.md
  docs/patterns/navigation.md
  package.json
  scss/_patterns_subnav.scss
  tests/parker.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2375 Fix map name conflict
  scss/_base_typography.scss
  scss/_settings_font.scss
Labels: Review: Code +1, Review: QA +1

#2376 Fix nav styling at smaller viewports so that it's full-width
  scss/_patterns_navigation.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2377 Update package to 2.0.0
  package.json
  scss/_settings_system.scss
Labels: Review: Code +1

#2378 Update 1.8 refs
  docs/index.md
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2379 Bump version to 2.0.1
  docs/index.md
  package.json
  scss/_settings_system.scss
Labels: Review: Code +1

#2381 Make grid col names overrideable
  scss/_base_placeholders.scss
  scss/_base_typography.scss
  scss/_patterns_grid.scss
  scss/_settings_font.scss
  scss/_settings_grid.scss
Labels: Review: Code +1, Review: QA +1

#2380 Update vanilla dep to v2.0.1
  .spelling
  .travis.yml
  docs/_layouts/default.html
  docs/base/typography.md
  docs/building-vanilla.md
  docs/customising-vanilla.md
  docs/examples/patterns/navigation/default.html
  docs/examples/templates/vertical-spacing.html
  docs/examples/utilities/floats/large-screens.html
  docs/examples/utilities/floats/medium-screens.html
  docs/examples/utilities/floats/small-screens.html
  docs/index.md
  docs/nginx.conf
  docs/patterns/accordion.md
  docs/patterns/article-pagination.md
  docs/patterns/breadcrumbs.md
  docs/patterns/card.md
  docs/patterns/contextual-menu.md
  docs/patterns/grid.md
  docs/patterns/icons.md
  docs/patterns/list-tree.md
  docs/patterns/lists.md
  docs/patterns/navigation.md
  docs/patterns/pull-quote.md
  docs/patterns/search-box.md
  docs/patterns/strip.md
  docs/patterns/tabs.md
  docs/patterns/tooltips.md
  docs/sass/_patterns_aside.scss
  docs/sass/styles.scss
  docs/settings/animation-settings.md
  docs/settings/breakpoint-settings.md
  docs/settings/color-settings.md
  docs/settings/font-settings.md
  docs/settings/layout-settings.md
  docs/settings/placeholder-settings.md
  docs/settings/spacing-settings.md
  docs/utilities/align.md
  docs/utilities/baseline-grid.md
  docs/utilities/clearfix.md
  docs/utilities/equal-height.md
  docs/utilities/floats.md
  docs/utilities/functions.md
  docs/utilities/hide.md
  docs/utilities/margin-collapse.md
  docs/utilities/no-print.md
  docs/utilities/off-screen.md
  docs/utilities/padding-collapse.md
  docs/utilities/show.md
  docs/utilities/vertically-center.md
  gulp/lint.js
  gulp/parker.js
  gulp/styles.js
  gulp/watch.js
  package.json
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2384 configurable table layout
  docs/_layouts/default.html
  docs/settings/table-layout.md
  scss/_base_tables.scss
  scss/_settings.scss
  scss/_settings_tables.scss
  scss/_utilities_layout.scss
Labels: Review: Code +1, Review: QA +1

#2387 address feedback on #2384 (part 1)
  docs/_layouts/default.html
  docs/settings/table-layout.md
  scss/_base_tables.scss
  scss/_settings_tables.scss
  scss/_utilities_layout.scss
Labels: Review: Code +1

#2389 Remove gulpfile.js
  gulpfile.js
Labels: Review: Code +1, Review: QA +1

#2393 Update docs icon examples
  docs/patterns/icons.md
Labels: Review: Code +1, Review: QA +1

#2396 Restructure docs sidebar navigation
  docs/_layouts/default.html
  docs/base/tables.md
Labels: Review: Code +1, Review: QA +1
