Repository canonical/vanilla-framework, pull requests merged in 2019-08, with the labels that each got.

#2440 Hide second navigation list in docs side nav on page
  docs/_layouts/default.html
Labels: Review: Code +1, Review: QA +1

#2441 Add new status page and labels. Update doc vanilla dependency to 2.2.0
  docs/_layouts/default.html
  docs/base/code.md
  docs/component-status.md
  docs/patterns/accordion.md
  docs/patterns/menu-button.md
  docs/patterns/navigation.md
  docs/patterns/pagination.md
  package.json
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2443 Update sidebar active link
  docs/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#2442 fix build, broken $table-layout-fixed
  scss/_utilities_layout.scss
Labels: Review: Code +1, Review: QA +1

#2445 decrease scope of selector so only direct children of .row span full width
  scss/_patterns_grid.scss
Labels: Review: Code +1, Review: QA +1

#2450 Make p-card's spacing rules less greedy
  scss/_patterns_card.scss
Labels: Review: Code +1, Review: QA +1

#2446 Update icon colours to $color-mid-dark
  scss/_patterns_icons.scss
Labels: Review: Code needed, Review: QA needed

#2467 Stop bullets from beforming when the title wraps
  scss/_patterns_lists.scss
Labels: Review: Code +1, Review: QA +1

#2468 Animations - Reorder and update content
  docs/patterns/icons.md
  docs/settings/animation-settings.md
Labels: Review: Code +1, Review: QA +1

#2469 Bump Vanilla version to 2.3.0
  docs/index.md
  package.json
  scss/_settings_system.scss
Labels: Review: Code +1

#2470 Update heading title and dividers
  docs/_layouts/default.html
  docs/base/reset.md
  docs/settings/table-layout.md
Labels: Review: Code +1, Review: QA +1

#2472 Fix label search result
  docs/_layouts/default.html
Labels: Review: Code +1, Review: QA +1

#2476 Rejig homepage layout
  docs/index.md
Labels: Review: Code +1, Review: QA +1

#2473 Remove <p> nesting in button examples
  docs/examples/patterns/buttons/base.html
  docs/examples/patterns/buttons/brand.html
  docs/examples/patterns/buttons/icon.html
  docs/examples/patterns/buttons/negative.html
  docs/examples/patterns/buttons/neutral.html
  docs/examples/patterns/buttons/positive.html
Labels: Review: Code +1, Review: QA +1

#2481 Fix 404 broken link
  docs/patterns/navigation.md
Labels: Review: Code +1, Review: QA +1

#2482 Update page heading
  docs/examples/index.html
Labels: Review: Code +1, Review: QA +1

#2486 JS notifications
  docs/base/code.md
  docs/base/tables.md
  docs/patterns/accordion.md
  docs/settings/spacing-settings.md
  docs/utilities/baseline-grid.md
Labels: Review: Code +1, Review: QA +1

#2494 Reorder and add sections to icons page
  docs/patterns/icons.md
Labels: Review: Code +1, Review: QA +1

#2495 Consistent footers
  docs/_layouts/default.html
Labels: Review: Code +1, Review: QA +1

#2498 Docs sidebar refresh
  docs/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#2499 Update homepage hero headings
  docs/_layouts/default.html
  docs/index.md
  docs/sass/styles.scss
Labels: Review: Code needed, Review: QA needed

#2500 Document usage of `is-light` for icons.
  docs/patterns/icons.md
Labels: Review: Code +1, Review: QA +1

#2490 Add JS notifications and functionality to docs
  docs/base/code.md
  docs/patterns/accordion.md
  docs/patterns/contextual-menu.md
  docs/patterns/list-tree.md
  docs/patterns/modal.md
  docs/patterns/navigation.md
  docs/patterns/notification.md
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2506 Remove dead link from package.json
  package.json
Labels: Review: Code +1

#2508 Increase the height of the modal iframe
  docs/patterns/modal.md
Labels: Review: Code +1, Review: QA +1

#2510 Bump the version of example-js to v1.2.0
  docs/_layouts/default.html
Labels: Review: Code +1, Review: QA +1

#2452 Spacing adjustment
  docs/examples/templates/typographic-spacing.html
  scss/_base_button.scss
  scss/_base_forms.scss
  scss/_base_lists.scss
  scss/_base_placeholders-margin-collapse.scss
  scss/_base_typography-definitions.scss
  scss/_base_typography.scss
  scss/_patterns_card.scss
  scss/_patterns_code-copyable.scss
  scss/_patterns_form-help-text.scss
  scss/_patterns_form-validation.scss
  scss/_patterns_forms.scss
  scss/_patterns_heading-icon.scss
  scss/_patterns_icons.scss
  scss/_patterns_inline-images.scss
  scss/_patterns_lists.scss
  scss/_patterns_matrix.scss
  scss/_patterns_media-object.scss
  scss/_patterns_tabs.scss
  scss/_settings_spacing.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2509 Add baseline grid background
  docs/_layouts/examples.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2511 Fix pagination margins
  scss/_patterns_icons.scss
  scss/_patterns_pagination.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2515 Fix positive buttons with icons
  docs/examples/patterns/buttons/icon.html
  scss/_patterns_buttons.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2519 replace calculations with already existing var that does same thing.…
  docs/examples/templates/tick-element-comparison.html
  scss/_base_button.scss
  scss/_base_forms.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2516 Add styling for detail element
  docs/_layouts/default.html
  docs/base/details.md
  docs/examples/base/details.html
  docs/examples/templates/typographic-spacing.html
  scss/_base.scss
  scss/_base_details.scss
  scss/_base_typography-definitions.scss
  scss/_base_typography.scss
  scss/_patterns_label.scss
  scss/_settings_spacing.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2520 Revert placeholders
  docs/customising-vanilla.md
  scss/_base.scss
  scss/_base_placeholders-fixed-width-container.scss
  scss/_base_placeholders-margin-collapse.scss
  scss/_base_placeholders.scss
  scss/_base_typography-definitions.scss
  scss/_base_typography-max-widths.scss
  scss/_base_typography.scss
  scss/_patterns_grid.scss
  scss/_patterns_icons.scss
  scss/_patterns_label.scss
  scss/_patterns_lists.scss
  scss/_patterns_media-object.scss
  scss/_settings_colors.scss
  scss/_utilities_layout.scss
  scss/_utilities_margin-collapse.scss
Labels: Review: Code +1, Review: QA +1
