Repository canonical/vanilla-framework, pull requests merged in 2019-09, with the labels that each got.

#2526 fix list item margins
  scss/_patterns_lists.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2523 Delete mixin invocations that dump into the beginning of build.css
  docs/examples/patterns/icons/icons-dark.html
  docs/examples/patterns/icons/icons-light.html
  scss/_patterns_accordion.scss
  scss/_patterns_pagination.scss
Labels: Review: Code +1, Review: QA +1

#2529 Remove densification of inputs in tables and provide dense inputs/but…
  docs/base/forms.md
  docs/examples/patterns/buttons/dense.html
  docs/examples/patterns/forms/dense.html
  docs/examples/patterns/tables/table-expanding.html
  docs/patterns/buttons.md
  scss/_base_button.scss
  scss/_base_forms.scss
Labels: Review: Code +1, Review: QA +1

#2528 Checkbox alignment classes
  docs/base/forms.md
  docs/examples/base/forms/aligned-checkboxes.html
  docs/examples/base/forms/aligned-radio.html
  scss/_base_forms-tick-elements.scss
  scss/_base_forms.scss
Labels: Review: Code +1, Review: QA +1

#2530 Themify tick elements
  scss/_base_forms-tick-elements.scss
  scss/_settings_themes.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2531 Labels wrapping checkboxes
  scss/_base_forms-tick-elements.scss
  scss/_patterns_switch.scss
Labels: Review: Code +1, Review: QA +1

#2535 Add support for right-aligned subnavs
  docs/examples/patterns/navigation/subnav.html
  docs/patterns/navigation.md
  scss/_patterns_subnav.scss
Labels: Review: Code +1, Review: QA +1

#2537 Update hide utility docs
  docs/utilities/hide.md
Labels: Review: Code +1, Review: QA +1

#2536 Update `u-hide` example
  docs/examples/utilities/hide.html
Labels: Review: Code needed, Review: QA needed

#2544 fix vr issue in nav and tabs
  scss/_patterns_navigation.scss
  scss/_patterns_tabs.scss
Labels: Review: Code +1, Review: QA +1

#2547 fix table td padding; move fontsize bump query 1px
  scss/_base_tables.scss
  scss/_settings_breakpoints.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2546 Move focus outline inside element. Tint with validation colours if el…
  scss/_base_details.scss
  scss/_base_forms.scss
  scss/_global_functions.scss
  scss/_patterns_pagination.scss
  scss/_patterns_search-box.scss
  scss/_settings_placeholders.scss
  scss/_utilities_layout.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2548 Bump project version to v2.4.0
  docs/index.md
  package.json
  scss/_settings_system.scss
Labels: Review: Code +1

#2550 Update docs to vanilla v2.4.0 and example JS to 1.2.1
  docs/_layouts/default.html
  package.json
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2559 Add padding below tables
  scss/_base_tables.scss
Labels: Review: Code +1, Review: QA +1

#2556 Update nav in dark theme to use #333
  scss/_patterns_navigation.scss
  scss/_settings_colors.scss
Labels: Review: Code +1, Review: QA +1

#2538 Add dark theme support to subnavs
  scss/_patterns_subnav.scss
  tests/parker.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1
