Repository canonical/vanilla-framework, pull requests merged in 2019-07, with the labels that each got.

#2403 Refactor lists sass so that placeholders are in global scope
  scss/_patterns_lists.scss
Labels: Review: Code +1, Review: QA +1

#2405 Bump framework version to 2.1.0
  docs/index.md
  package.json
  scss/_settings_system.scss
Labels: Review: Code +1, Review: QA +1

#2415 fix extra double-primes in expanding table code example
  docs/examples/patterns/tables/table-expanding.html
Labels: Review: Code +1, Review: QA +1

#2417 remove var that is no longer used
  scss/_settings_grid.scss
Labels: Review: Code +1

#2416 Built new status labels
  docs/examples/patterns/labels/deprecated.html
  docs/examples/patterns/labels/in-progress.html
  docs/examples/patterns/labels/new.html
  docs/examples/patterns/labels/updated.html
  docs/examples/patterns/labels/validated.html
  docs/patterns/labels.md
  scss/_patterns_label.scss
  scss/_vanilla.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2421 Ensure nested rows get correct column count when not direct children of cols
  docs/examples/patterns/grid/nested-medium.html
  scss/_patterns_grid.scss
Labels: Review: Code +1, Review: QA +1

#2425 Fix misleading text in checkbox docs
  docs/base/forms.md
Labels: Review: Code +1, Review: QA +1

#2429 Add back duplicate navifation for search
  docs/_layouts/default.html
Labels: Review: Code +1, Review: QA +1

#2431 update grid gutter to 2rem, as it is a closer match to vf 1.8
  docs/patterns/grid.md
  scss/_settings_grid.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2432 Remove 1600px viewport from Percy
  .travis.yml
Labels: Review: Code +1, Review: QA +1

#2434 Add variables for social media icon colours.
  scss/_patterns_icons.scss
Labels: Review: Code +1, Review: QA -1

#2435 Bumped Vanilla version to 2.2.0
  docs/index.md
  package.json
  scss/_settings_system.scss
Labels: Review: Code +1

#2433 Add missing vf- prefix to animation example
  docs/settings/animation-settings.md
Labels: Review: Code needed
