Repository canonical/vanilla-framework, pull requests merged in 2019-01, with the labels that each got.

#2086 Update label to reflect input
  examples/base/forms/form.html
Labels: Review: Code +1, Review: QA +1

#2087 Resize delete icon
  scss/_patterns_icons.scss
Labels: Review: Code +1, Review: QA +1

#2082 Use 100vh instead of height 100% on body with sticky footer
  scss/_utilities_sticky-footer.scss
Labels: Review: Code +1, Review: QA +1

#2105 v1.8.1
  .travis.yml
  docs/en/index.md
  docs/en/metadata.yaml
  docs/en/utilities/baseline-grid.md
  docs/en/utilities/functions.md
  docs/package.json
  docs/template.html
  docs/yarn.lock
  scss/_patterns_slider.scss
  scss/_settings_system.scss
Labels: Review: Code +1

#2112 Add Usabilla to documentation site
  docs/template.html
Labels: Review: Code +1, Review: QA +1

#2109 Update fixed-width to 72rem
  scss/_settings_grid.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2117 Typographic adjustments
  examples/templates/typographic-spacing.html
  scss/_base_button.scss
  scss/_base_typography.scss
  scss/_patterns_card.scss
  scss/_patterns_heading-icon.scss
  scss/_patterns_lists.scss
  scss/_patterns_matrix.scss
  scss/_patterns_media-object.scss
  scss/_settings_spacing.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2123 card p:last-child – fix selector from "starts with" to "contains"
  scss/_patterns_card.scss
Labels: Review: Code +1, Review: QA +1

#2126 move base typography rules at beginning of base includes
  scss/_base.scss
  scss/_base_forms.scss
Labels: Review: Code +1, Review: QA +1

#2120 Updates to 'Icons' layout on docs
  docs/en/patterns/icons.md
  examples/patterns/icons/icons-dark.html
  examples/patterns/icons/icons-light.html
  examples/patterns/icons/icons-social.html
Labels: Review: Code +1, Review: QA +1

#2131 Update docs color page to use card styles
  docs/en/settings/color-settings.md
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2135 Typography refactor: Break up huge _typography.scss file into smaller files
  examples/templates/typographic-spacing.html
  scss/_base_fontfaces.scss
  scss/_base_tables.scss
  scss/_base_typography-definitions.scss
  scss/_base_typography-heading-mixins.scss
  scss/_base_typography-max-widths.scss
  scss/_base_typography.scss
  scss/_patterns_table-mobile-card.scss
  scss/_settings_spacing.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2136 pattern-fixes
  scss/_base_tables.scss
  scss/_patterns_form-help-text.scss
  scss/_patterns_form-validation.scss
  scss/_patterns_matrix.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2139 add usabilla to documentation
  docs/template.html
Labels: Review: Code +1, Review: QA +1
