Repository canonical/vanilla-framework, pull requests merged in 2019-11, with the labels that each got.

#2610 Add import snippet to components documentation
  .gitignore
  .spelling
  docs/base/code.md
  docs/base/forms.md
  docs/base/tables.md
  docs/base/typography.md
  docs/patterns/accordion.md
  docs/patterns/article-pagination.md
  docs/patterns/breadcrumbs.md
  docs/patterns/buttons.md
  docs/patterns/card.md
  docs/patterns/contextual-menu.md
  docs/patterns/grid.md
  docs/patterns/heading-icon.md
  docs/patterns/icons.md
  docs/patterns/images.md
  docs/patterns/inline-images.md
  docs/patterns/labels.md
  docs/patterns/links.md
  docs/patterns/list-tree.md
  docs/patterns/lists.md
  docs/patterns/matrix.md
  docs/patterns/media-object.md
  docs/patterns/modal.md
  docs/patterns/muted-heading.md
  docs/patterns/navigation.md
  docs/patterns/notification.md
  docs/patterns/pagination.md
  docs/patterns/pull-quote.md
  docs/patterns/search-box.md
  docs/patterns/slider.md
  docs/patterns/strip.md
  docs/patterns/switch.md
  docs/patterns/table-of-contents.md
  docs/patterns/tabs.md
  docs/patterns/tooltips.md
Labels: Review: Code +1, Review: QA +1

#2609 Consistent page titles
  docs/examples/base/font-weights.html
  docs/examples/base/forms/select-multiple.html
  docs/examples/base/forms/textarea.html
  docs/examples/patterns/article-pagination.html
  docs/examples/patterns/code-copyable.html
  docs/examples/patterns/code-numbered.html
  docs/examples/patterns/grid/bordered.html
  docs/examples/patterns/grid/nested-medium.html
  docs/examples/patterns/grid/nested-small.html
  docs/examples/patterns/grid/nested.html
  docs/examples/patterns/icons/icons-dark.html
  docs/examples/patterns/icons/icons-light.html
  docs/examples/patterns/icons/icons-social.html
  docs/examples/patterns/image/bordered.html
  docs/examples/patterns/image/shadowed.html
  docs/examples/patterns/lists/lists-stepped-detailed.html
  docs/examples/patterns/lists/lists-stepped.html
  docs/examples/patterns/media-object/media-object-circ-img.html
  docs/examples/patterns/media-object/media-object-large.html
  docs/examples/patterns/media-object/media-object.html
  docs/examples/patterns/navigation/default-dark.html
  docs/examples/patterns/navigation/subnav.html
  docs/examples/patterns/pagination/pagination-disabled.html
  docs/examples/patterns/strips/deep.html
  docs/examples/patterns/strips/is-bordered.html
  docs/examples/patterns/strips/shallow.html
  docs/examples/patterns/tables/table-expanding.html
  docs/examples/patterns/tables/table-mobile-card.html
  docs/examples/patterns/tables/table-sortable.html
Labels: Review: Code +1, Review: QA +1

#2613 Clarify animation mixing usage example in docs
  docs/settings/animation-settings.md
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2614 Add usage to code-copyable
  docs/base/code.md
Labels: Review: Code +1, Review: QA +1

#2615 Add import snippet to utilities documentation
  docs/settings/layout-settings.md
  docs/settings/spacing-settings.md
  docs/utilities/align.md
  docs/utilities/baseline-grid.md
  docs/utilities/clearfix.md
  docs/utilities/embedded-media.md
  docs/utilities/equal-height.md
  docs/utilities/floats.md
  docs/utilities/hide.md
  docs/utilities/image-position.md
  docs/utilities/margin-collapse.md
  docs/utilities/no-print.md
  docs/utilities/off-screen.md
  docs/utilities/padding-collapse.md
  docs/utilities/show.md
  docs/utilities/vertically-center.md
Labels: Review: Code +1, Review: QA +1

#2617 Rename vertical divider to responsive divider
  docs/patterns/lists.md
Labels: Review: Code +1, Review: QA +1

#2616 Documentation entry on max-width; u-no-max-width utility
  .spelling
  docs/base/typography.md
  docs/examples/utilities/max-width-unset.html
  scss/_base_typography-max-widths.scss
  scss/_patterns_notifications.scss
  scss/_settings_spacing.scss
  scss/_utilities_max-width.scss
  scss/_vanilla.scss
Labels: Review: Code +1, Review: Design needed, Review: QA +1

#2619 Fix icons inside buttons; add font-metrics utility
  .spelling
  docs/_layouts/default.html
  docs/examples/patterns/buttons/icon.html
  docs/examples/utilities/font-metrics.html
  docs/utilities/baseline-grid.md
  docs/utilities/font-metrics.md
  scss/_base_button.scss
  scss/_base_forms.scss
  scss/_patterns_buttons.scss
  scss/_patterns_icons.scss
  scss/_patterns_search-box.scss
  scss/_settings_font.scss
  scss/_utilities_font-metrics.scss
  scss/_vanilla.scss
Labels: Review: Code +1, Review: QA +1

#2621 Table expanding panel: Prevent children with defined margins from stretching
  scss/_patterns_table-expanding.scss
Labels: Review: Code +1, Review: QA +1

#2624 Document font-size bump, clarify type scale, fix breakpoint typo
  docs/base/typography.md
  docs/settings/breakpoint-settings.md
Labels: Review: Code +1, Review: QA +1

#2626 Remove coding standards page from docs nav
  docs/_layouts/default.html
Labels: Review: Code +1, Review: QA +1

#2637 Remove details doc page
  docs/_layouts/default.html
  docs/base/details.md
Labels: Review: Code needed, Review: QA needed

#2638 External link
  docs/examples/patterns/links/links-external.html
  scss/_patterns_links.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2640 Replace old chevron with new; Add missing role to markup
  docs/examples/patterns/tables/table-sortable.html
  scss/_patterns_table-sortable.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2639 Add new social RSS icon
  docs/examples/patterns/icons/icons-social.html
  docs/patterns/icons.md
  scss/_patterns_icons.scss
Labels: Review: Code +1, Review: QA +1

#2641 Update social icon library
  scss/_patterns_icons.scss
Labels: Review: Code +1, Review: QA +1

#2643 Fix notification icon position
  scss/_patterns_notifications.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2636 Provide utility to overlap table cell padding
  docs/_layouts/default.html
  docs/examples/utilities/table-cell-padding-overlap.html
  docs/utilities/table-cell-padding-overlap.md
  scss/_base_placeholders.scss
  scss/_base_tables.scss
  scss/_settings_spacing.scss
  scss/_utilities_margin-collapse.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2644 fix mobile card table
  docs/examples/patterns/tables/table-mobile-card.html
  scss/_base_tables.scss
  scss/_patterns_table-mobile-card.scss
Labels: Don't merge, Review: Code +1, Review: Design +1, Review: QA +1

#2650 Contextual menu: add focus state to links; expand to fit content until it hits its max-width
  scss/_patterns_contextual-menu.scss
  tests/parker.js
Labels: Review: Code +1, Review: QA +1

#2651 Increase input margin bottom by .5rem
  docs/examples/templates/tick-element-comparison.html
  scss/_base_forms.scss
  scss/_settings_spacing.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2659 Reduce RSS & LinkedIn icon size
  scss/_patterns_icons.scss
  tests/parker.js
Labels: Review: Code +1, Review: QA +1

#2652 Validation fields: prevent text from overlapping validation icons
  scss/_patterns_form-validation.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2667 Fix the table sorting pattern functionality on Chrome
  docs/examples/patterns/tables/table-sortable.html
Labels: Review: Code +1, Review: QA +1

#2666 Prevent table header border from disappearing when tbody contains no rows
  scss/_base_tables.scss
Labels: Review: Code +1, Review: QA +1
