Repository canonical/vanilla-framework, pull requests merged in 2019-12, with the labels that each got.

#2671 Add new social email icon
  docs/examples/patterns/icons/icons-social.html
  docs/patterns/icons.md
  scss/_patterns_icons.scss
Labels: Review: Code +1, Review: QA +1

#2682 Indent p-stepped-list__content
  scss/_patterns_lists.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2683 Remove Ubuntu and Canonical social icons
  .spelling
  docs/component-status.md
  docs/examples/patterns/icons/icons-social.html
  docs/patterns/icons.md
  scss/_patterns_icons.scss
Labels: Review: Code +1, Review: QA +1

#2687 Fix middot position as it was in 2.3.0
  scss/_patterns_lists.scss
Labels: Review: Code +1, Review: QA +1

#2689 Bump version to 2.5.0
  docs/index.md
  package.json
  scss/_settings_system.scss
Labels: Review: Code +1, Review: QA +1

#2692 Bump version of Vanilla used by the docs
  package.json
  yarn.lock
Labels: Don't merge, Review: Code +1, Review: Design +1, Review: QA +1

#2691 Don't build deprecate util, fix setting app-version before it's used
  scss/_settings.scss
  scss/deprecate/_index.scss
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#2693 Update component status 2.5.0
  docs/_layouts/default.html
  docs/base/typography.md
  docs/component-status.md
  docs/settings/color-settings.md
  docs/utilities/font-metrics.md
  docs/utilities/table-cell-padding-overlap.md
  docs/utilities/truncate.md
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2694 Update component status 2.5.0
  docs/base/code.md
  docs/patterns/accordion.md
  docs/patterns/menu-button.md
  docs/patterns/navigation.md
  docs/patterns/pagination.md
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2698 Convert Vanilla JS in examples to ES5
  docs/examples/patterns/accordion.html
  docs/examples/patterns/code-copyable.html
  docs/examples/patterns/contextual-menu/default.html
  docs/examples/patterns/contextual-menu/with-indicator.html
  docs/examples/patterns/modal.html
  docs/examples/patterns/navigation/subnav.html
  docs/examples/patterns/notifications/notifications.html
  docs/examples/patterns/slider/slider-input.html
  docs/examples/patterns/slider/slider.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2704 Remove old path from testing URL
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Review: Code +1

#2703 Store Vanilla version in jekyll config
  docs/_config.yml
  docs/index.md
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#2705 Use Codepen for Vanilla docs examples
  docs/_layouts/default.html
  docs/_layouts/examples.html
  docs/base/code.md
  docs/base/forms.md
  docs/base/tables.md
  docs/base/typography.md
  docs/js/example.js
  docs/patterns/accordion.md
  docs/patterns/article-pagination.md
  docs/patterns/breadcrumbs.md
  docs/patterns/buttons.md
  docs/patterns/card.md
  docs/patterns/contextual-menu.md
  docs/patterns/grid.md
  docs/patterns/heading-icon.md
  docs/patterns/images.md
  docs/patterns/inline-images.md
  docs/patterns/labels.md
  docs/patterns/links.md
  docs/patterns/list-tree.md
  docs/patterns/lists.md
  docs/patterns/matrix.md
  docs/patterns/media-object.md
  docs/patterns/modal.md
  docs/patterns/muted-heading.md
  docs/patterns/navigation.md
  docs/patterns/notification.md
  docs/patterns/pagination.md
  docs/patterns/pull-quote.md
  docs/patterns/search-box.md
  docs/patterns/slider.md
  docs/patterns/strip.md
  docs/patterns/switch.md
  docs/patterns/table-of-contents.md
  docs/patterns/tabs.md
  docs/patterns/tooltips.md
  docs/settings/animation-settings.md
  docs/settings/spacing-settings.md
  docs/utilities/align.md
  docs/utilities/baseline-grid.md
  docs/utilities/clearfix.md
  docs/utilities/embedded-media.md
  docs/utilities/equal-height.md
  docs/utilities/floats.md
  docs/utilities/font-metrics.md
  docs/utilities/hide.md
  docs/utilities/image-position.md
  docs/utilities/margin-collapse.md
  docs/utilities/no-print.md
  docs/utilities/off-screen.md
  docs/utilities/padding-collapse.md
  docs/utilities/show.md
  docs/utilities/table-cell-padding-overlap.md
  docs/utilities/truncate.md
  docs/utilities/vertically-center.md
Labels: Maintenance 🔨, Review: Code +1, Review: Design +1, Review: QA +1

#2708 Fix :visited link styles in subnav
  scss/_patterns_subnav.scss
Labels: Review: Code +1, Review: QA +1

#2707 Consistent JS examples in docs
  docs/examples/patterns/accordion.html
  docs/examples/patterns/code-copyable.html
  docs/examples/patterns/contextual-menu/default.html
  docs/examples/patterns/contextual-menu/with-indicator.html
  docs/examples/patterns/list-tree.html
  docs/examples/patterns/modal.html
  docs/examples/patterns/navigation/subnav.html
  docs/examples/patterns/notifications/notifications.html
  docs/examples/patterns/slider/slider-input.html
  docs/examples/patterns/slider/slider.html
  docs/examples/patterns/tables/table-expanding.html
  docs/examples/patterns/tables/table-sortable.html
  docs/examples/utilities/baseline-grid.html
Labels: Review: Code +1, Review: QA +1
