Repository canonical/vanilla-framework, pull requests merged in 2020-09, with the labels that each got.

#3255 Switch component: Fix validator issue
  scss/_patterns_switch.scss
  templates/_layouts/examples.html
  templates/docs/examples/patterns/switch.html
  templates/docs/examples/utilities/baseline-grid.html
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3257 Remove `href` from buttons
  templates/docs/examples/patterns/contextual-menu/dark.html
  templates/docs/examples/patterns/contextual-menu/default.html
  templates/docs/examples/patterns/contextual-menu/with-indicator.html
  templates/docs/examples/templates/typographic-spacing.html
Labels: Review: Code +1, Review: QA +1

#3258 Add lang attrib to html tag
  templates/_layouts/examples.html
  templates/docs/building-vanilla.md
Labels: Review: Code needed, Review: QA needed

#3265 Accessibility fixes: Navigation
  templates/docs/examples/layouts/documentation.html
  templates/docs/examples/patterns/navigation/default-dark.html
  templates/docs/examples/patterns/navigation/default.html
  templates/docs/examples/patterns/navigation/deprecated-dark.html
  templates/docs/examples/patterns/navigation/deprecated.html
  templates/docs/examples/patterns/navigation/full-width.html
  templates/docs/examples/patterns/navigation/subnav-dark.html
  templates/docs/examples/patterns/navigation/subnav.html
  templates/docs/examples/patterns/search-box/navigation-dark.html
  templates/docs/examples/patterns/search-box/navigation.html
  templates/docs/examples/templates/maas-layout.html
  templates/docs/examples/templates/snapcraft-publicise.html
  templates/docs/examples/templates/z-index.html
Labels: Review: Code +1, Review: QA +1

#3267 Fix errors when building with dart-sass
  .github/workflows/pr.yml
  scss/_base_button.scss
  scss/_patterns_buttons.scss
  scss/_patterns_pagination.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3268 Fixes misaligned quotes in pull quotes component
  scss/_patterns_pull-quotes.scss
  templates/docs/examples/patterns/pull-quotes/variants.html
Labels: Bug 🐛, Review: Code +1, Review: Design +1, Review: QA +1

#3270 Add landmarks to layout examples
  templates/docs/examples/layouts/application-structure.html
  templates/docs/examples/layouts/application.html
Labels: Review: Code +1, Review: QA +1

#3271 Add roles and correct tags to side navigation
  templates/docs/examples/patterns/side-navigation/_default.html
  templates/docs/examples/patterns/side-navigation/_icons.html
  templates/docs/examples/patterns/side-navigation/_layout-application.html
  templates/docs/examples/patterns/side-navigation/docs.html
  templates/docs/examples/patterns/side-navigation/icons.html
  templates/docs/examples/templates/maas-docs-grid.html
  templates/docs/examples/templates/maas-docs.html
Labels: Review: Code +1, Review: QA +1

#3275 Bump version to 2.18.0
  package.json
Labels: Maintenance 🔨, Review: Code +1

#3204 Navigation highlight update option 2
  scss/_patterns_navigation.scss
  scss/_patterns_subnav.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3277 Fix table-related accessibility issues
  scss/_patterns_table-sortable.scss
  templates/docs/component-status.md
  templates/docs/examples/base/forms/aligned-checkboxes.html
  templates/docs/examples/base/forms/aligned-radio.html
  templates/docs/examples/base/table.html
  templates/docs/examples/layouts/application-structure.html
  templates/docs/examples/layouts/application.html
  templates/docs/examples/layouts/documentation.html
  templates/docs/examples/patterns/forms/_checkbox-inline.html
  templates/docs/examples/patterns/forms/_radio-inline.html
  templates/docs/examples/patterns/forms/tick-comparison.html
  templates/docs/examples/patterns/tables/table-colored-rows.html
  templates/docs/examples/patterns/tables/table-expanding.html
  templates/docs/examples/patterns/tables/table-mobile-card.html
  templates/docs/examples/patterns/tables/table-sortable.html
  templates/docs/examples/templates/maas-docs-grid.html
  templates/docs/examples/templates/maas-layout.html
  templates/docs/examples/templates/tick-element-comparison.html
  templates/docs/examples/utilities/table-cell-padding-overlap.html
  templates/docs/examples/utilities/truncate.html
Labels: Review: Code +1, Review: QA +1

#3280 Accessibility validator fix: Moves any `<style>` tags on example pages to the `<head>`
  templates/_layouts/examples.html
  templates/docs/examples/base/hr-dark.html
  templates/docs/examples/base/hr.html
  templates/docs/examples/layouts/application-structure.html
  templates/docs/examples/layouts/application.html
  templates/docs/examples/layouts/documentation.html
  templates/docs/examples/patterns/grid/responsive.html
  templates/docs/examples/patterns/side-navigation/dark.html
  templates/docs/examples/templates/maas-docs-grid.html
  templates/docs/examples/templates/maas-docs.html
  templates/docs/examples/templates/snapcraft-publicise.html
  templates/docs/examples/templates/typographic-spacing.html
Labels: Review: Code +1, Review: QA +1

#3283 Accessibility fix: Remove alt attribs from all buttons
  templates/_layouts/_header.html
  templates/docs/examples/layouts/documentation.html
  templates/docs/examples/patterns/search-box/default-dark.html
  templates/docs/examples/patterns/search-box/default.html
  templates/docs/examples/patterns/search-box/navigation-dark.html
  templates/docs/examples/patterns/search-box/navigation.html
  templates/docs/examples/templates/maas-docs-grid.html
  templates/docs/examples/templates/maas-docs.html
  templates/docs/examples/templates/maas-layout.html
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3288 Bump version of Vanilla to 2.19
  package.json
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3289 Accessibility: Misc markup fixes
  templates/_layouts/_footer.html
  templates/_layouts/_root.html
  templates/index.html
Labels: Review: Code needed, Review: QA needed

#3290 Remove width attrib from anchors, remove invalid aria-labels from contextual menu
  templates/docs/examples/patterns/contextual-menu/dark.html
  templates/docs/examples/patterns/contextual-menu/default.html
  templates/docs/examples/patterns/contextual-menu/with-indicator.html
  templates/docs/examples/patterns/modal/default.html
  templates/docs/examples/templates/maas-layout.html
  templates/docs/examples/templates/z-index.html
Labels: Review: Code +1, Review: QA +1

#3297 Update flask-base to 0.6.4
  requirements.txt
Labels: Maintenance 🔨, Review: Code needed, Review: QA needed

#3291 Add aria-attributes to slider component
  templates/docs/examples/patterns/slider/slider-input.html
Labels: Review: Code +1, Review: QA +1

#3299 Remove attr checked from select
  templates/docs/examples/templates/snapcraft-publicise.html
Labels: Review: Code +1, Review: QA +1

#3300 Remove empty action attributes from vanilla examples to avoid validator errors
  templates/docs/examples/layouts/documentation.html
  templates/docs/examples/templates/maas-docs-grid.html
  templates/docs/examples/templates/maas-docs.html
  templates/docs/examples/templates/tick-element-comparison.html
Labels: Review: Code +1, Review: QA +1

#3296 Remove obsolete frameborder attribute
  scss/_base_media.scss
  templates/docs/examples/utilities/embedded-media.html
Labels: Review: Code +1, Review: QA +1

#3305 Remove invalid links from showcase page
  templates/showcase.html
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3311 Add autocomplete and fix types in a few places
  templates/_layouts/_header.html
  templates/docs/examples/base/forms/fieldset.html
  templates/docs/examples/base/forms/form.html
  templates/docs/examples/base/forms/input.html
  templates/docs/examples/base/forms/labels.html
  templates/docs/examples/layouts/documentation.html
  templates/docs/examples/patterns/forms/_form-stacked.html
  templates/docs/examples/patterns/forms/dense.html
  templates/docs/examples/patterns/forms/form-help-text.html
  templates/docs/examples/patterns/forms/form-inline.html
  templates/docs/examples/patterns/forms/form-validation.html
  templates/docs/examples/patterns/forms/forms-required.html
  templates/docs/examples/patterns/forms/tick-comparison.html
  templates/docs/examples/patterns/search-box/default-dark.html
  templates/docs/examples/patterns/search-box/default.html
  templates/docs/examples/patterns/search-box/navigation-dark.html
  templates/docs/examples/patterns/search-box/navigation.html
  templates/docs/examples/templates/maas-docs-grid.html
  templates/docs/examples/templates/maas-docs.html
  templates/docs/examples/templates/maas-layout.html
  templates/docs/examples/templates/tick-element-comparison.html
  templates/docs/examples/templates/typographic-spacing.html
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#3316 Remove duplicate ids
  templates/docs/examples/layouts/application.html
  templates/docs/examples/patterns/accordion/headings.html
  templates/docs/examples/patterns/forms/_checkbox.html
  templates/docs/examples/patterns/forms/_form-stacked.html
  templates/docs/examples/patterns/forms/_radio-heading.html
  templates/docs/examples/patterns/tables/table-expanding.html
  templates/docs/examples/templates/maas-docs.html
  templates/docs/examples/templates/snapcraft-publicise.html
  templates/docs/examples/templates/typographic-spacing.html
Labels: Review: Code +1, Review: QA +1

#3320 Fix tree component roles as per spec
  templates/docs/examples/patterns/list-tree.html
Labels: Review: Code +1, Review: QA +1

#3323 Add status and alerts roles to notifications and validation messages
  templates/docs/examples/patterns/forms/form-validation.html
  templates/docs/examples/patterns/notifications/action.html
  templates/docs/examples/patterns/notifications/caution.html
  templates/docs/examples/patterns/notifications/information.html
  templates/docs/examples/patterns/notifications/negative.html
  templates/docs/examples/patterns/notifications/positive.html
Labels: Review: Code +1, Review: QA +1

#3325 Applicaiton layout: Point aria-describedby to correct ids
  templates/docs/examples/layouts/application.html
Labels: Review: Code +1, Review: QA +1
