Repository canonical/vanilla-framework, pull requests merged in 2020-01, with the labels that each got.

#2715 Install bundler@1 on travis
  .travis.yml
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#2713 Fix code-copyable (#2690)
  scss/_patterns_code-copyable.scss
Labels: Review: Code +1, Review: QA +1

#2717 Fix renovate config
  renovate.json
Labels: Review: Code +1

#2712 Adjust breakpoints to fix midbreakpoint failure (#2696)
  scss/_patterns_navigation.scss
Labels: Review: Code +1, Review: QA +1

#2710 Update ./run script to latest version
  run
Labels: Review: Code +1, Review: QA +1

#2731 Add strong text example to typography
  docs/base/typography.md
  docs/examples/base/strong.html
Labels: Review: Code +1, Review: QA +1

#2730 Style range input as slider by default
  docs/base/forms.md
  docs/component-status.md
  docs/examples/base/forms/range.html
  docs/patterns/slider.md
  scss/_base_forms-range.scss
  scss/_base_forms.scss
  scss/_patterns_slider.scss
Labels: Breaking change 💣, Review: Code +1, Review: Design +1, Review: QA +1

#2732 Make sure all settings files are independent
  scss/_settings_grid.scss
  scss/_settings_placeholders.scss
Labels: Review: Code +1, Review: QA +1

#2733 Fix Firefox issues with component status table
  docs/component-status.md
Labels: Review: Code +1, Review: QA +1

#2738 Remove unnecessary margin
  docs/component-status.md
Labels: Review: Code +1, Review: QA +1

#2740 Enable multistage builds, update pretty-quick
  .travis.yml
  Dockerfile
  docs/Dockerfile
  docs/nginx.conf
  package.json
  renovate.json
Labels: Review: Code +1, Review: QA +1

#2764 Fix spelling typo
  docs/examples/utilities/truncate.html
Labels: Review: Code +1

#2768 Update specificity of navigation styles to fix issue with full width nav
  scss/_base_placeholders.scss
  scss/_patterns_navigation.scss
Labels: Bug 🐛, Review: Code +1, Review: Design +1, Review: QA +1

#2769 Add separate page with individual CSS examples
  docs/examples/index.html
  docs/examples/individual/index.html
Labels: Review: Code needed, Review: Design +1, Review: QA +1

#2783 Only animate necessary props in navigation links
  scss/_patterns_navigation.scss
Labels: Review: Code +1, Review: QA +1

#2780 Update look of table header to match #2501
  docs/_includes/base/forms/aligned-checkboxes.html
  docs/_includes/base/forms/aligned-radio.html
  docs/base/forms.md
  scss/_base_forms-tick-elements.scss
  scss/_base_tables.scss
  scss/_base_typography-definitions.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2788 Bump version of Vanilla framework to 2.6.0
  package.json
  scss/_settings_system.scss
Labels: Review: Code +1

#2789 Upgrade docs site to Vanilla 2.6.0
  docs/_config.yml
  docs/index.md
  package.json
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2774 Update Travis and Percy configs to run on Flask docs
  .travis.yml
  docs/examples/utilities/image-position/left.md
  package.json
  snapshots.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2794 Add release drafter config
  .github/release-drafter.yml
Labels: Review: Code +1

#2795 Remove Jekyll config
  docs/_config.yml
Labels: Review: Code needed

#2800 Add missing equal sign
  docs/patterns/icons.md
Labels: Review: Code +1

#2803 /standalone at the end of the URL
  docs/examples/index.html
  docs/examples/standalone.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#2798 Dockerfile for Flask version
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#2807 Read titles from templates
  docs/404.html
  docs/500.html
  docs/_layouts/default.html
  docs/examples/index.html
  docs/examples/standalone.html
  requirements.txt
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#2809 Add redirects for previous locations of static resources
  redirects.yaml
Labels: Review: Code +1, Review: QA +1
