Repository canonical/vanilla-framework, pull requests merged in 2020-06, with the labels that each got.

#3108 Bump version to 2.12.1
  package.json
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3114 Consistent hover background color
  scss/_base_button.scss
  scss/_patterns_buttons.scss
  scss/_patterns_contextual-menu.scss
  scss/_patterns_side-navigation.scss
  scss/_settings_colors.scss
Labels: Review: Code +1, Review: QA +1

#3121 add borders to detailed list
  scss/_patterns_lists.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3128 Fix focus outline in tab strip
  scss/_patterns_tabs.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3129 Add k8s configuration in deploy/site.yaml
  deploy/site.yaml
Labels: Review: Code +1
