Repository canonical/vanilla-framework, pull requests merged in 2020-10, with the labels that each got.

#3326 Apply standard vanilla focus state to treeview items
  scss/_patterns_list-tree.scss
Labels: Review: Code +1, Review: QA +1

#3329 Add cookie policy to Vanilla site
  package.json
  scss/docs/site.scss
  templates/_layouts/_footer.html
  templates/_layouts/_root.html
  yarn.lock
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3330 Fix show utility to correctly set initial value
  scss/_utilities_show.scss
  templates/docs/examples/utilities/show.html
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3331 Bump version to 2.19.1
  package.json
Labels: Maintenance 🔨, Review: Code +1

#3332 Make sure cookie policy is correctly styled in docs
  templates/_layouts/docs.html
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3336 Bump to cookie version v3.03
  .gitignore
  package.json
  yarn.lock
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3339 Fix a few validator complaints
  templates/docs/examples/layouts/application.html
  templates/docs/examples/patterns/forms/_form-stacked.html
  templates/docs/examples/templates/snapcraft-publicise.html
  templates/docs/examples/templates/tick-element-comparison.html
Labels: Review: Code +1

#3335 Change h3 font-weight to 100
  scss/_base_typography-definitions.scss
  scss/_patterns_pull-quotes.scss
Labels: Maintenance 🔨, Review: Code +1, Review: Design +1, Review: QA +1

#3345 Update color of side navigation headings
  scss/_patterns_side-navigation.scss
Labels: Maintenance 🔨, Review: Code +1, Review: Design +1, Review: QA +1

#3346 Set muted heading font weight to 300
  scss/_base_button.scss
  scss/_base_code.scss
  scss/_base_fontfaces.scss
  scss/_base_forms.scss
  scss/_base_tables.scss
  scss/_base_typography-definitions.scss
  scss/_base_typography.scss
  scss/_settings_font.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3349 Add missing treeitem roles on li that have ul in them
  templates/docs/examples/patterns/list-tree.html
Labels: Review: Code +1, Review: QA +1

#3347 Update the accessibility guidelines page
  templates/accessibility.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3359 Fixes broken pagination links in search results
  templates/docs/search.html
Labels: Documentation 📝, Review: Code +1, Review: QA +1

#3117 Ensure <pre> elements use ubuntu mono instead of browser default
  scss/_base_code.scss
  scss/_base_typography.scss
  templates/docs/base/code.md
  templates/docs/examples/base/code-block.html
  templates/docs/examples/base/code-inline.html
  templates/docs/examples/base/pre.html
Labels: Review: Code +1, Review: QA +1

#3367 Clarify the usage of the dark-themed icons.
  templates/docs/patterns/icons.md
Labels: Documentation 📝, Review: Code +1, Review: QA +1

#3372 Remove unnecessary wrong media query from subnav
  scss/_patterns_subnav.scss
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3380 Fix anchor links in side navigation on mobile
  templates/static/js/scripts.js
Labels: Bug 🐛, Documentation 📝, Review: Code +1, Review: QA +1
