Repository canonical/vanilla-framework, pull requests merged in 2020-04, with the labels that each got.

#2973 Fix class attribute selectors
  scss/_patterns_buttons.scss
  scss/_patterns_card.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#2978 Bump Vanilla version to 2.9.1
  package.json
Labels: Maintenance 🔨, Review: Code +1

#2984 Update renovate.json based on maas-ui
  renovate.json
Labels: Maintenance 🔨, Review: Code +1

#2985 Make sure Circle CI fails if server doesn't run
  .circleci/config.yml
Labels: Maintenance 🔨, Review: Code +1

#2997 Don't rely on icon from juju charms
  templates/docs/examples/patterns/media-object/media-object-large.html
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3000 Bump Vanilla version to 2.10.0
  package.json
Labels: Maintenance 🔨, Review: Code +1

#3004 Removed confusing sentence about margin in notification.
  templates/docs/patterns/notification.md
Labels: Documentation 📝, Review: Code +1, Review: QA +1

#3006 Disambiguates “Input”, “HTML5”, and “Textarea”
  templates/docs/base/forms.md
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3002 Update PR workflow to test SCSS on PRs
  .github/workflows/pr.yml
  tests/parker.js
Labels: Maintenance 🔨, Review: Code +1

#3007 Changes notification example to not use “Information:”
  templates/docs/examples/patterns/notifications/information.html
Labels: Documentation 📝, Review: Code +1, Review: QA +1

#3015 Remove duplicated side-navigation id from the template
  templates/_layouts/docs.html
Labels: Documentation 📝, Review: Code +1, Review: QA +1

#3023 Fix the small screen side navigation
  templates/_layouts/docs.html
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3024 Make sure side navigation id doesn't collide with side navigation docs
  templates/_layouts/docs.html
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3028 Close side navigation drawer on anchor click
  templates/static/js/example.js
  templates/static/js/scripts.js
Labels: Bug 🐛, Documentation 📝, Review: Code +1, Review: QA +1

#3029 Fix z-index collisiton and bottom border in tabs on small screens
  scss/_patterns_tabs.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3031 Fix JS error on search results page
  templates/static/js/scripts.js
Labels: Documentation 📝, Review: Code +1, Review: QA +1

#3030 Bump Vanilla to 2.10.1 for the release
  package.json
Labels: Maintenance 🔨, Review: Code +1
