Repository canonical/vanilla-framework, pull requests merged in 2020-11, with the labels that each got.

#3383 fix incorrect aria-hidden value on subnavigation
  templates/docs/examples/patterns/navigation/_script.js
Labels: Bug 🐛, Maintenance 🔨, Review: Code +1, Review: QA +1

#3385 remove top border from first item in matrix on small screens
  scss/_patterns_matrix.scss
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3392 Bump version to 2.19.3
  package.json
Labels: Maintenance 🔨

#3395 Fix adding custom styles to embedded examples
  scss/_utilities_baseline-grid.scss
  scss/standalone/example.scss
  templates/_layouts/examples.html
  templates/static/js/example.js
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3400 Enforce BEM class naming
  .stylelintrc.json
  scss/docs/_patterns_syntax-highlight.scss
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3401 Allow .p-form--inline formgroups to wrap when necessary
  scss/_patterns_forms.scss
  templates/docs/examples/patterns/forms/form-inline.html
Labels: Bug 🐛, Review: Code +1, Review: QA needed

#3398 Fix the cookie policy styling in examples
  templates/docs/examples/index.html
  templates/docs/examples/standalone.html
Labels: Review: Code +1, Review: QA +1

#3406 Fix spell-checking of the docs
  .spelling
  package.json
  templates/docs/base/code.md
  templates/docs/base/forms.md
  templates/docs/layouts/documentation.md
  templates/docs/patterns/breadcrumbs.md
  templates/docs/patterns/navigation.md
  templates/docs/patterns/pagination.md
  templates/docs/patterns/strip.md
Labels: Documentation 📝, Maintenance 🔨, Review: Code +1, Review: QA +1

#3404 Add .is-small button class
  scss/_base_button.scss
  templates/docs/component-status.md
  templates/docs/examples/patterns/buttons/small.html
  templates/docs/patterns/buttons.md
Labels: Feature 🎁, Review: Code +1, Review: Design +1, Review: QA +1

#3410 Add ability to set foreground (tick) color on success icon
  scss/_base_icon-definitions.scss
  scss/_patterns_buttons.scss
  templates/docs/examples/patterns/buttons/icon.html
  templates/docs/examples/templates/tick-element-comparison.html
Labels: Feature 🎁, Review: Code +1, Review: QA +1

#3413 Add "is-active" button state
  scss/_patterns_buttons.scss
  templates/docs/component-status.md
  templates/docs/examples/patterns/buttons/active.html
  templates/docs/patterns/buttons.md
Labels: Feature 🎁, Review: Code +1, Review: QA +1

#3414 Set position: relative on .p-checkbox
  scss/_patterns_form-tick-elements.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3415 Adjust position of hidden tick inputs
  scss/_base_forms-tick-elements.scss
  scss/_patterns_form-tick-elements.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3425 Prepare 2.20.0 release
  package.json
  templates/_layouts/docs.html
  templates/docs/component-status.md
  templates/docs/layouts/application.md
  templates/docs/patterns/buttons.md
Labels: Maintenance 🔨, Review: Code needed

#3429 Add focus-visible support to vf-focus mixin
  scss/_global_functions.scss
Labels: Feature 🎁, Review: Code +1, Review: QA +1

#3430 Update command prompt font family
  scss/_patterns_code-copyable.scss
Labels: Maintenance 🔨, Review: Code +1, Review: Design +1
