Repository canonical/vanilla-framework, pull requests merged in 2020-03, with the labels that each got.

#2869 Fix examples
  site/_layouts/default.html
  site/docs/base/code.md
  site/docs/base/forms.md
  site/docs/base/tables.md
  site/docs/base/typography.md
  site/docs/examples/index.html
  site/docs/examples/standalone.html
  site/docs/patterns/accordion.md
  site/docs/patterns/article-pagination.md
  site/docs/patterns/breadcrumbs.md
  site/docs/patterns/buttons.md
  site/docs/patterns/card.md
  site/docs/patterns/contextual-menu.md
  site/docs/patterns/grid.md
  site/docs/patterns/heading-icon.md
  site/docs/patterns/images.md
  site/docs/patterns/inline-images.md
  site/docs/patterns/labels.md
  site/docs/patterns/links.md
  site/docs/patterns/list-tree.md
  site/docs/patterns/lists.md
  site/docs/patterns/matrix.md
  site/docs/patterns/media-object.md
  site/docs/patterns/modal.md
  site/docs/patterns/muted-heading.md
  site/docs/patterns/navigation.md
  site/docs/patterns/notification.md
  site/docs/patterns/pagination.md
  site/docs/patterns/pull-quote.md
  site/docs/patterns/search-box.md
  site/docs/patterns/slider.md
  site/docs/patterns/strip.md
  site/docs/patterns/switch.md
  site/docs/patterns/table-of-contents.md
  site/docs/patterns/tabs.md
  site/docs/patterns/tooltips.md
  site/docs/settings/animation-settings.md
  site/docs/settings/spacing-settings.md
  site/docs/utilities/align.md
  site/docs/utilities/baseline-grid.md
  site/docs/utilities/clearfix.md
  site/docs/utilities/embedded-media.md
  site/docs/utilities/equal-height.md
  site/docs/utilities/floats.md
  site/docs/utilities/font-metrics.md
  site/docs/utilities/hide.md
  site/docs/utilities/image-position.md
  site/docs/utilities/margin-collapse.md
  site/docs/utilities/no-print.md
  site/docs/utilities/off-screen.md
  site/docs/utilities/padding-collapse.md
  site/docs/utilities/show.md
  site/docs/utilities/table-cell-padding-overlap.md
  site/docs/utilities/truncate.md
  site/docs/utilities/vertically-center.md
Labels: Review: Code +1, Review: QA +1

#2876 Move Jekyll metadata to Flask template blocks
  site/_layouts/site.html
  site/accessibility.html
  site/browser-support.html
  site/contribute.html
  site/index.html
  site/showcase.html
Labels: Review: Code +1, Review: QA +1

#2879 Fix links in docs main nav
  site/_layouts/default.html
Labels: Review: Code needed, Review: QA needed

#2888 Fix docker image
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#2890 Clean up PR GitHub workflow
  .github/workflows/pr_docker_build.yml
Labels: Maintenance 🔨, Review: Code needed, Review: QA needed

#2893 Fix highlighting link for standalone examples
  site/_layouts/default.html
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#2905 Update docs link in release drafter template
  .github/release-drafter.yml
Labels: Maintenance 🔨, Review: Code +1

#2906 Add Circle CI badge to README
  README.md
Labels: Maintenance 🔨, Review: Code +1

#2917 Make footer consistent between site and docs layouts
  .github/ISSUE_TEMPLATE/report-a-bug.md
  templates/_layouts/_footer.html
  templates/_layouts/docs.html
  templates/_layouts/site.html
  templates/static/js/scripts.js
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#2924 Update search site URL
  webapp/app.py
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#2925 Remove border from subnav dropdowns
  scss/_patterns_subnav.scss
Labels: Maintenance 🔨, Review: Code +1, Review: Design +1, Review: QA +1

#2929 Remove bottom margin from label component
  scss/_patterns_label.scss
Labels: Maintenance 🔨, Review: Code +1, Review: Design +1

#2935 Align side navigation group border with text
  scss/_patterns_side-navigation.scss
Labels: Feature 🎁, Review: Code +1, Review: Design +1

#2941 Prevent pretty-quick from commiting changes in husky hook
  package.json
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#2936 Update Vanilla docs to use new side navigation
  scss/docs/docs.scss
  templates/_layouts/docs.html
  templates/static/js/scripts.js
Labels: Documentation 📝, Review: Code +1, Review: Design +1, Review: QA +1

#2956 Bump Vanilla version to 2.9.0
  package.json
Labels: Maintenance 🔨, Review: Code +1

#2962 Fix selector to match all buttons with modifiers
  scss/_patterns_buttons.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#2964 Update listing of latest blog posts on home page
  templates/index.html
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1
