Repository canonical/vanilla-framework, pull requests merged in 2020-05, with the labels that each got.

#3060 Update grid.md
  templates/docs/patterns/grid.md
  templates/docs/patterns/lists.md
  templates/docs/settings/table-layout.md
Labels: Documentation 📝, Review: Code +1, Review: QA +1

#3070 Bump Vanilla version to 2.11
  package.json
Labels: Maintenance 🔨, Review: Code +1

#3072 scope margin-left on p-stepped-list__content to stepped list only
  scss/_patterns_lists.scss
  tests/parker.js
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3081 Fix side navigation overlapping with global nav
  scss/_patterns_side-navigation.scss
  templates/docs/examples/layouts/_global-nav.html
  templates/docs/examples/layouts/documentation.html
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3082 Support rgba colors in `vf-url-friendly-color` function
  scss/_global_functions.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3080 fix external link icon lineheight so it doesn't distort focus outline
  scss/_patterns_links.scss
  templates/docs/examples/templates/external-links.html
Labels: Don't merge, Review: Code +1, Review: Design +1, Review: QA +1

#3079 Fix focus outline in navigation and tabs
  scss/_patterns_navigation.scss
  scss/_patterns_tabs.scss
  templates/docs/examples/patterns/tabs.html
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3088 Update templatefinder
  requirements.txt
Labels: Maintenance 🔨, Review: Code +1

#3089 Remove vertical offsets from divider lines
  scss/_patterns_divider.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3090 Bump version of Vanilla to 2.12
  package.json
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3094 Encode CodePen prefill data
  templates/static/js/example.js
Labels: Bug 🐛, Documentation 📝, Review: Code +1, Review: QA +1

#3095 Fix z-index issues between contextual menu and tabs
  scss/_patterns_contextual-menu.scss
  templates/docs/examples/templates/z-index.html
Labels: Breaking change 💣, Bug 🐛, Review: Code +1, Review: QA +1

#3098 Fix Python dependencies issue
  Dockerfile
Labels: Review: Code needed, Review: QA needed

#3100 Fix z-index collisions between patterns
  scss/_patterns_contextual-menu.scss
  scss/_patterns_form-validation.scss
  scss/_patterns_modal.scss
  templates/docs/examples/templates/z-index.html
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3096 Snapshot only example screenshots for Percy
  snapshots.js
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3104 Docs: fix typo in heading-icon.md
  templates/docs/patterns/heading-icon.md
Labels: Review: Code +1

#3106 Update light theme border and highlight colors to be transparent
  scss/_patterns_contextual-menu.scss
  scss/_settings_colors.scss
  templates/docs/examples/patterns/side-navigation/_icons.html
Labels: Bug 🐛, Review: Code +1, Review: Design +1, Review: QA +1
