Repository canonical/vanilla-framework, pull requests merged in 2020-07, with the labels that each got.

#3137 Extend %placeholder instead of .classname in SCSS
  scss/_patterns_article-pagination.scss
Labels: Maintenance 🔨, Review: Code needed

#3141 Fix bold in code
  scss/_base_code.scss
  templates/docs/examples/base/code.html
Labels: Bug 🐛, Review: Code +1, Review: Design +1, Review: QA +1

#3140 Make list placeholders includable separately from patterns
  scss/_patterns_lists.scss
  templates/docs/patterns/lists.md
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3146 Fix typo in class name in list example
  templates/docs/examples/patterns/lists/lists-inline-stretch-align.html
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3156 Bump version of Vanilla to 2.14.0
  package.json
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3164 Change default font-display value to fallback
  package.json
  scss/_settings_font.scss
  templates/docs/base/typography.md
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3176 Rename deploy to konf
  konf/site.yaml
Labels: Review: QA +1

#3182 Add yarn.lock to docker image
  Dockerfile
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3185 Add Sentry DSN to site.yaml
  konf/site.yaml
Labels: Review: Code +1

#3179 Chips improvements
  scss/_patterns_chip.scss
  scss/_vanilla.scss
  scss/standalone/patterns_chip.scss
  templates/_layouts/docs.html
  templates/docs/examples/patterns/chip/long-values.html
  templates/docs/examples/patterns/chip/multiple.html
  templates/docs/examples/patterns/chip/with-dismiss.html
  templates/docs/examples/patterns/chip/without-dismiss.html
  templates/docs/examples/utilities/margin-collapse.html
  templates/docs/patterns/chip.md
Labels: Review: Code +1, Review: QA +1

#3124 Increase title margin on small screens
  scss/_patterns_matrix.scss
Labels: Bug 🐛, Review: Code +1, Review: Design +1, Review: QA +1

#3195 Fix icons in standalone chip examples
  scss/standalone/patterns_chip.scss
Labels: Documentation 📝, Review: Code +1, Review: QA +1
