Repository canonical/vanilla-framework, pull requests merged in 2020-02, with the labels that each got.

#2814 Themify contextual menu
  docs/examples/patterns/contextual-menu/dark.html
  docs/examples/patterns/contextual-menu/light.html
  docs/patterns/contextual-menu.md
  scss/_patterns_contextual-menu.scss
  scss/_settings_themes.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2812 Add /search to docs site
  docs/search.html
  requirements.txt
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#2818 fix search input placement in IE11
  scss/_patterns_search-box.scss
Labels: Review: Code +1, Review: QA +1

#2819 Search results page
  docs/404.html
  docs/500.html
  docs/_layouts/default.html
  docs/search.html
  docs/static/js/scripts.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2820 Move search box to main nav
  docs/_layouts/default.html
  docs/search.html
  docs/static/scss/styles.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2821 Number classes
  docs/base/typography.md
  docs/component-status.md
  docs/examples/base/sub-headings.html
  docs/examples/patterns/headings/default.html
  docs/examples/patterns/headings/mixed.html
  docs/examples/templates/maas-layout.html
  docs/examples/templates/typographic-spacing.html
  scss/_base_typography.scss
  scss/_patterns_headings.scss
  scss/_patterns_icons.scss
  scss/_patterns_links.scss
Labels: Feature 🎁, Review: Code +1, Review: QA +1

#2822 Add search to Vanilla docs
  docs/404.html
  docs/500.html
  docs/_layouts/default.html
  docs/search.html
  docs/static/js/scripts.js
  docs/static/scss/styles.scss
  requirements.txt
  webapp/app.py
Labels: Review: QA +1

#2829 Remove .npmignore
  .npmignore
  package.json
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#2834 Update flask-base to prevent caching of _status endpoints
  requirements.txt
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#2837 Update release drafter template, use it as GH Workflow
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: Review: Code +1

#2839 Pass Vanilla version from package.json to scss
  package.json
  sass-functions.js
  scss/_settings_system.scss
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#2840 Add workflow to publish Vanilla to npm and assets on release
  .github/workflows/publish-on-release.yml
Labels: Maintenance 🔨, Review: Code +1

#2845 Bump version to 2.7.1
  package.json
Labels: Maintenance 🔨, Review: Code +1

#2846 Fix release workflow to be triggered on release publish event
  .github/workflows/publish-on-release.yml
Labels: Maintenance 🔨

#2850 Better dotrun support
  .gitignore
  package.json
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#2854 Fix external link background leaking
  scss/_patterns_links.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#2856 Only compensate margin on pararaphs that don't have heading classes
  scss/_base_typography-definitions.scss
Labels: Bug 🐛, Review: Code +1, Review: Design +1, Review: QA +1

#2852 Improve class selectors for navigation
  docs/_layouts/default.html
  docs/component-status.md
  docs/examples/patterns/navigation/_script.js
  docs/examples/patterns/navigation/default-dark.html
  docs/examples/patterns/navigation/default.html
  docs/examples/patterns/navigation/deprecated-dark.html
  docs/examples/patterns/navigation/deprecated.html
  docs/examples/patterns/navigation/full-width.html
  docs/examples/patterns/navigation/subnav-dark.html
  docs/examples/patterns/navigation/subnav.html
  docs/examples/patterns/search-box/navigation-dark.html
  docs/examples/patterns/search-box/navigation.html
  docs/patterns/navigation.md
  package.json
  scss/_patterns_navigation.scss
  scss/_patterns_subnav.scss
Labels: Breaking change 💣, Maintenance 🔨, Review: Code +1, Review: Design +1, Review: QA +1
