Repository canonical/vanilla-framework, pull requests merged in 2021-07, with the labels that each got.

#3807 Add dark theme to the buttons
  scss/_base_button.scss
  scss/_patterns_buttons.scss
  scss/_settings_colors.scss
  scss/_settings_themes.scss
  templates/docs/component-status.md
  templates/docs/examples/patterns/buttons/dark.html
  templates/docs/examples/templates/external-links.html
  templates/docs/patterns/buttons.md
  tests/parker.js
Labels: Feature 🎁, Review: Code +1, Review: Design +1, Review: QA +1

#3775 Spacing vars update
  scss/_base_blockquotes.scss
  scss/_base_button.scss
  scss/_base_forms.scss
  scss/_base_hr.scss
  scss/_layouts_application-panels.scss
  scss/_patterns_breadcrumbs.scss
  scss/_patterns_card.scss
  scss/_patterns_code-snippet.scss
  scss/_patterns_divider.scss
  scss/_patterns_grid.scss
  scss/_patterns_heading-icon.scss
  scss/_patterns_lists.scss
  scss/_patterns_matrix.scss
  scss/_patterns_media-object.scss
  scss/_patterns_modal.scss
  scss/_patterns_notifications.scss
  scss/_patterns_pagination.scss
  scss/_patterns_pull-quotes.scss
  scss/_patterns_search-and-filter.scss
  scss/_patterns_side-navigation.scss
  scss/_patterns_subnav.scss
  scss/_patterns_switch.scss
  scss/_settings_colors.scss
  scss/_settings_grid.scss
  scss/_settings_spacing.scss
  scss/_utilities_baseline-grid.scss
  templates/docs/upgrade-guide-v3.md
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3843 Remove contextual menu styles from p-table--mobile-card
  scss/_patterns_table-mobile-card.scss
  scss/standalone/patterns_table-mobile-card.scss
  templates/docs/component-status.md
  templates/docs/examples/patterns/tables/table-mobile-card.html
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3844 Update existing notification pattern with new styling
  scss/_patterns_notifications.scss
Labels: Feature 🎁, Review: Code +1, Review: Design +1, Review: QA +1

#3852 Move global nav styles from example to scss file
  scss/standalone/patterns_skip-link.scss
  templates/docs/examples/layouts/_global-nav.html
  templates/docs/examples/layouts/documentation.html
  templates/docs/examples/layouts/global-nav.css
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3859 Notifications deprecations
  .spelling
  scss/_patterns_notifications.scss
  templates/docs/component-status.md
  templates/docs/examples/patterns/notifications/dismissible.html
  templates/docs/examples/patterns/notifications/timestamp.html
  templates/docs/examples/patterns/notifications/variants.html
  templates/docs/patterns/notification.md
Labels: Review: Code +1

#3866 Update notification spacing
  scss/_base_forms.scss
  scss/_base_typography-definitions.scss
  scss/_patterns_notifications.scss
  scss/_settings_spacing.scss
  templates/docs/examples/patterns/notifications/action.html
  templates/docs/examples/patterns/notifications/borderless.html
  templates/docs/examples/patterns/notifications/caution.html
  templates/docs/examples/patterns/notifications/dismissible.html
  templates/docs/examples/patterns/notifications/information.html
  templates/docs/examples/patterns/notifications/inline.html
  templates/docs/examples/patterns/notifications/modal.html
  templates/docs/examples/patterns/notifications/negative.html
  templates/docs/examples/patterns/notifications/notifications.html
  templates/docs/examples/patterns/notifications/positive.html
  templates/docs/examples/patterns/notifications/raised.html
  templates/docs/examples/patterns/notifications/timestamp.html
  templates/docs/examples/patterns/notifications/variants.html
Labels: Feature 🎁, Review: Code +1, Review: QA +1

#3874 Bump version to 2.33.0-rc2
  package.json
Labels: Maintenance 🔨

#3875 Bump version to 2.33.0
  package.json
Labels: Maintenance 🔨

#3864 Bring search and filter height inline with other inputs
  scss/_base_button.scss
  scss/_patterns_buttons.scss
  scss/_patterns_search-and-filter.scss
  tests/parker.js
Labels: Maintenance 🔨, Review: Code +1, Review: Design +1, Review: QA +1

#3880 Set z-index of hr.u-no-margin--bottom
  package.json
  scss/_base_placeholders.scss
  templates/docs/examples/templates/z-index.html
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3879 Add documentation on notification accessibility
  templates/docs/patterns/notification.md
Labels: Documentation 📝, Review: Code +1

#3881 Document icon color customisation
  .spelling
  templates/docs/patterns/icons.md
Labels: Documentation 📝, Review: Code needed

#3882 Add heading for modal footer
  templates/docs/patterns/modal.md
Labels: Review: Code +1

#3883 Remove unnecessary comment from layout application template
  templates/docs/examples/patterns/side-navigation/_layout-application.html
Labels: Maintenance 🔨, Review: Code +1

#3894 Document font-weight variables
  scss/_base_code.scss
  scss/_base_fontfaces.scss
  scss/_base_syntax-highlighting.scss
  scss/_base_typography-definitions.scss
  scss/_patterns_code-copyable.scss
  scss/_patterns_label.scss
  scss/_settings_font.scss
  templates/docs/settings/font-settings.md
Labels: Documentation 📝, Review: Code needed, Review: QA needed

#3893 Add dart-sass build info
  templates/docs/building-vanilla.md
Labels: Documentation 📝, Review: Code +1, Review: QA +1
