Repository canonical/vanilla-framework, pull requests merged in 2021-09, with the labels that each got.

#3964 Fix labels in docs for 2.35
  templates/_layouts/docs.html
  templates/docs/whats-new.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝

#3963 No indentation accordion variation
  package.json
  scss/_patterns_accordion.scss
  scss/standalone/patterns_accordion.scss
  templates/_layouts/docs.html
  templates/docs/examples/patterns/accordion/tick-elements.html
  templates/docs/patterns/accordion.md
  templates/docs/whats-new.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Bug 🐛

#3973 Add hover state for uncollpased accordion button
  scss/_patterns_accordion.scss
Labels: Review: QA +1, Review: Code +1, Bug 🐛

#3953 Move card padding to `p-card__inner`
  .spelling
  scss/_base_placeholders.scss
  scss/_patterns_card.scss
  scss/standalone/patterns_card.scss
  templates/_layouts/docs.html
  templates/docs/examples/patterns/card/_header-and-footer.html
  templates/docs/examples/patterns/card/content-bleed.html
  templates/docs/examples/patterns/card/default.html
  templates/docs/examples/patterns/card/header.html
  templates/docs/examples/patterns/card/highlighted.html
  templates/docs/examples/templates/typographic-spacing.html
  templates/docs/patterns/card.md
  templates/docs/patterns/icons.md
  templates/docs/whats-new.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Feature 🎁

#3965 Align help text and labels for tick elements
  scss/_patterns_form-help-text.scss
  scss/_patterns_form-tick-elements.scss
  scss/standalone/patterns_form-tick-elements.scss
  scss/standalone/patterns_forms.scss
  templates/_layouts/docs.html
  templates/docs/base/forms.md
  templates/docs/examples/patterns/forms/form-help-text.html
  templates/docs/examples/patterns/forms/tick-comparison.html
  templates/docs/whats-new.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Bug 🐛

#3971 Spacing refactor rebased on the 3.0 feature branch
  .circleci/config.yml
  scss/_base_blockquotes.scss
  scss/_base_button.scss
  scss/_base_code.scss
  scss/_base_details.scss
  scss/_base_forms-tick-elements.scss
  scss/_base_forms.scss
  scss/_base_hr.scss
  scss/_base_lists.scss
  scss/_base_media.scss
  scss/_base_placeholders.scss
  scss/_base_tables.scss
  scss/_base_typography-definitions.scss
  scss/_base_typography.scss
  scss/_layouts_application-panels.scss
  scss/_layouts_fluid-breakout.scss
  scss/_patterns_accordion.scss
  scss/_patterns_breadcrumbs.scss
  scss/_patterns_buttons.scss
  scss/_patterns_card.scss
  scss/_patterns_chip.scss
  scss/_patterns_code-snippet.scss
  scss/_patterns_contextual-menu.scss
  scss/_patterns_divider.scss
  scss/_patterns_form-help-text.scss
  scss/_patterns_form-tick-elements.scss
  scss/_patterns_form-validation.scss
  scss/_patterns_forms.scss
  scss/_patterns_grid.scss
  scss/_patterns_heading-icon.scss
  scss/_patterns_label.scss
  scss/_patterns_links.scss
  scss/_patterns_lists.scss
  scss/_patterns_logo-section.scss
  scss/_patterns_matrix.scss
  scss/_patterns_media-object.scss
  scss/_patterns_modal.scss
  scss/_patterns_navigation.scss
  scss/_patterns_notifications.scss
  scss/_patterns_pagination.scss
  scss/_patterns_pull-quotes.scss
  scss/_patterns_search-and-filter.scss
  scss/_patterns_search-box.scss
  scss/_patterns_separator.scss
  scss/_patterns_side-navigation.scss
  scss/_patterns_table-icons.scss
  scss/_patterns_table-mobile-card.scss
  scss/_patterns_tabs.scss
  scss/_patterns_tooltips.scss
  scss/_settings_spacing.scss
  scss/_utilities_baseline-grid.scss
  scss/_utilities_embedded-media.scss
  templates/docs/examples/layouts/application/_styles.css
  templates/docs/settings/spacing-settings.md
  templates/docs/upgrade-guide-v3.md
Labels: Review: QA +1, Review: Code +1, Feature 🎁, Breaking change 💣, Maintenance 🔨, Documentation 📝

#3982 Truncates modal to fit content and centers
  package.json
  scss/_patterns_modal.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Bug 🐛

#3983 Make header fixed in modal
  scss/_patterns_modal.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Bug 🐛

#3986 Update watch:scss:skip-standalone
  package.json
Labels: Review: QA +1, Review: Code +1, Bug 🐛

#3998 Update modal accessibility docs
  templates/docs/patterns/modal.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝
