Repository canonical/vanilla-framework, pull requests merged in 2021-04, with the labels that each got.

#3676 Add footer to modal dialog
  scss/_patterns_modal.scss
  scss/standalone/patterns_modal.scss
  templates/_layouts/docs.html
  templates/docs/component-status.md
  templates/docs/examples/patterns/modal/default.html
  templates/docs/examples/patterns/modal/footer.html
  templates/docs/patterns/modal.md
Labels: Feature 🎁, Review: Code +1, Review: Design +1, Review: QA +1

#3689 Update docs with guidance on using tooltips with disabled elements
  templates/docs/patterns/tooltips.md
Labels: Documentation 📝, Review: Code +1, Review: QA +1

#3688 Improve show/hiding of tooltips in JS example
  templates/docs/examples/patterns/tooltips/_tooltips_script.js
Labels: Documentation 📝, Review: Code +1, Review: QA +1

#3691 Add right padding to modal header to accommodate close button
  scss/_patterns_modal.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3694 Update p-stepped-list__title to allow child elements
  scss/_patterns_lists.scss
  templates/docs/examples/patterns/lists/lists-stepped-detailed.html
  templates/docs/examples/patterns/lists/lists-stepped.html
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3695 Print size of build file in CI logs
  .github/workflows/pr.yml
  .github/workflows/publish-on-release.yml
Labels: Maintenance 🔨, Review: Code +1

#3696 Update the style of back to top link
  scss/_patterns_links.scss
Labels: Bug 🐛, Review: Code +1, Review: Design +1, Review: QA +1

#3670 Add logo-section component
  scss/_patterns_logo-section.scss
  scss/_vanilla.scss
  scss/standalone/patterns_logo-section.scss
  templates/_layouts/docs.html
  templates/docs/component-status.md
  templates/docs/examples/patterns/logo-section/logo-section-in-six-column-parent.html
  templates/docs/examples/patterns/logo-section/logo-section.html
  templates/docs/patterns/inline-images.md
  templates/docs/patterns/logo-section.md
  templates/docs/upgrade-guide-v3.md
Labels: Feature 🎁, Review: Code +1, Review: QA +1

#3702 Remove right arrow from tabs component
  package.json
  scss/_patterns_tabs.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1, Review: UX +1

#3706 Fix backround of buttons in contextual menu
  scss/_patterns_contextual-menu.scss
  templates/docs/examples/patterns/contextual-menu/dark.html
  templates/docs/examples/patterns/contextual-menu/default.html
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3704 Remove unnecessary p-slider class from the example
  templates/docs/examples/patterns/slider/slider-input.html
Labels: Documentation 📝, Review: Code +1, Review: QA +1

#3707 Update table mobile card design
  scss/_base_forms-tick-elements.scss
  scss/_base_tables.scss
  scss/_base_typography-definitions.scss
  scss/_patterns_chip.scss
  scss/_patterns_table-mobile-card.scss
Labels: Maintenance 🔨, Review: Code +1, Review: Design +1, Review: QA +1

#3697 Increase small text line height
  scss/_patterns_table-mobile-card.scss
  scss/_settings_spacing.scss
  templates/docs/examples/base/small.html
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3716 Add toolbar to the fluid-breakout layout
  package.json
  scss/_layouts_fluid-breakout.scss
  templates/_layouts/docs.html
  templates/docs/component-status.md
  templates/docs/examples/layouts/fluid-breakout/_toolbar.html
  templates/docs/examples/layouts/fluid-breakout/fluid-breakout-cards-with-aside-and-toolbar.html
  templates/docs/examples/layouts/fluid-breakout/fluid-breakout-left-aside-and-toolbar.html
  templates/docs/layouts/fluid-breakout.md
Labels: Feature 🎁, Review: Code +1, Review: Design +1, Review: QA +1

#3715 Link from Vanilla to React docs
  .spelling
  templates/docs/base/code.md
  templates/docs/base/forms.md
  templates/docs/base/tables.md
  templates/docs/patterns/accordion.md
  templates/docs/patterns/buttons.md
  templates/docs/patterns/card.md
  templates/docs/patterns/chip.md
  templates/docs/patterns/contextual-menu.md
  templates/docs/patterns/grid.md
  templates/docs/patterns/icons.md
  templates/docs/patterns/links.md
  templates/docs/patterns/lists.md
  templates/docs/patterns/modal.md
  templates/docs/patterns/notification.md
  templates/docs/patterns/pagination.md
  templates/docs/patterns/search-and-filter.md
  templates/docs/patterns/search-box.md
  templates/docs/patterns/slider.md
  templates/docs/patterns/strip.md
  templates/docs/patterns/tabs.md
  templates/docs/patterns/tooltips.md
Labels: Documentation 📝, Review: Code needed, Review: QA needed

#3722 Add comma to hero text on marketing site homepage
  templates/docs/examples/patterns/strips/suru.html
  templates/index.html
Labels: Maintenance 🔨, Review: Code +1
