Repository canonical/vanilla-framework, pull requests merged in 2021-03, with the labels that each got.

#3600 Update component status for 2.25
  templates/_layouts/docs.html
  templates/docs/component-status.md
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3601 Remove margin right from contextual menu
  package.json
  scss/_patterns_contextual-menu.scss
  templates/docs/examples/templates/maas-layout.html
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3603 Fix linkchecker on GH actions
  .github/workflows/pr.yml
Labels: Maintenance 🔨, Review: Code +1

#3597 Fix fieldset issues raised in #969
  scss/_base_forms.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3606 Install linkchecker via pip3
  .github/workflows/pr.yml
Labels: Maintenance 🔨, Review: Code needed

#3609 Fix bottom margin on last p element in p-matrix__desc
  scss/_patterns_matrix.scss
Labels: Bug 🐛, Review: Code +1, Review: Design +1, Review: QA +1

#3607 Add selector-max-type linting rule
  .stylelintrc.json
  scss/_base_background.scss
  scss/_base_blockquotes.scss
  scss/_base_box-sizing.scss
  scss/_base_button.scss
  scss/_base_code.scss
  scss/_base_details.scss
  scss/_base_forms-range.scss
  scss/_base_forms-tick-elements.scss
  scss/_base_forms.scss
  scss/_base_hr.scss
  scss/_base_links.scss
  scss/_base_lists.scss
  scss/_base_media.scss
  scss/_base_tables.scss
  scss/_base_typography.scss
  scss/_patterns_accordion.scss
  scss/_patterns_card.scss
  scss/_patterns_form-validation.scss
  scss/_patterns_forms.scss
  scss/_patterns_icons.scss
  scss/_patterns_lists.scss
  scss/_patterns_navigation.scss
  scss/_patterns_side-navigation.scss
  scss/_patterns_subnav.scss
  scss/_patterns_switch.scss
  scss/_patterns_table-expanding.scss
  scss/_patterns_table-mobile-card.scss
  scss/_patterns_table-sortable.scss
  scss/_utilities_baseline-grid.scss
  scss/_utilities_hide.scss
  scss/_utilities_vertically-center.scss
  scss/docs/site.scss
  scss/standalone/example.scss
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3620 Use calc for computations with grid-max-width
  scss/_base_hr.scss
  scss/_layouts_fluid-breakout.scss
  scss/_settings_grid.scss
  scss/standalone/custom.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3613 Add indeterminate state checkbox
  scss/_base_forms-tick-elements.scss
  templates/docs/base/forms.md
  templates/docs/component-status.md
  templates/docs/examples/base/forms/_indeterminate_script.js
  templates/docs/examples/base/forms/checkbox-indeterminate.html
Labels: Feature 🎁, Review: Code +1, Review: Design +1, Review: QA +1

#3612 Add the search and filter component
  .spelling
  scss/_patterns_search-and-filter.scss
  scss/_vanilla.scss
  scss/standalone/patterns_search-and-filter.scss
  templates/_layouts/docs.html
  templates/docs/component-status.md
  templates/docs/examples/patterns/search-and-filter/_default-script.js
  templates/docs/examples/patterns/search-and-filter/_overflow-script.js
  templates/docs/examples/patterns/search-and-filter/_search-prompt-script.js
  templates/docs/examples/patterns/search-and-filter/chip-overflow.html
  templates/docs/examples/patterns/search-and-filter/default.html
  templates/docs/examples/patterns/search-and-filter/with-chips.html
  templates/docs/examples/patterns/search-and-filter/with-search-prompt.html
  templates/docs/patterns/search-and-filter.md
  tests/parker.js
Labels: Feature 🎁, Review: Code +1, Review: Design +1, Review: QA +1

#3630 Add missing labels to side navigation for 2.26
  templates/_layouts/docs.html
Labels: Maintenance 🔨, Review: QA +1

#3634 Use the correct color code for the $color-information example
  templates/docs/settings/color-settings.md
Labels: Documentation 📝, Review: Code +1

#3638 Remove custom syntax highlighting from home page
  scss/docs/_patterns_syntax-highlight.scss
  scss/docs/site.scss
  templates/index.html
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3640 Add the definition of done to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Maintenance 🔨, Review: Code +1

#3632 Add .is-bordered to code snippet
  package.json
  scss/_patterns_code-snippet.scss
  scss/docs/site.scss
  templates/_layouts/docs.html
  templates/docs/base/code.md
  templates/docs/base/forms.md
  templates/docs/base/separators.md
  templates/docs/base/tables.md
  templates/docs/base/typography.md
  templates/docs/component-status.md
  templates/docs/examples/patterns/code-snippet/is-bordered.html
  templates/docs/layouts/application.md
  templates/docs/layouts/fluid-breakout.md
  templates/docs/layouts/sticky-footer.md
  templates/docs/patterns/accordion.md
  templates/docs/patterns/breadcrumbs.md
  templates/docs/patterns/buttons.md
  templates/docs/patterns/contextual-menu.md
  templates/docs/patterns/icons.md
  templates/docs/patterns/lists.md
  templates/docs/patterns/navigation.md
  templates/static/js/example.js
Labels: Don't merge, Feature 🎁, Review: Code +1, Review: QA +1

#3641 Add latest Vanilla version to home page
  templates/index.html
Labels: Documentation 📝, Review: Code +1, Review: QA +1

#3642 Update search box examples with JS to handle cancel event
  templates/docs/examples/patterns/search-box/_script.js
  templates/docs/examples/patterns/search-box/default-dark.html
  templates/docs/examples/patterns/search-box/default.html
  templates/docs/examples/patterns/search-box/navigation-dark.html
  templates/docs/examples/patterns/search-box/navigation.html
  templates/docs/patterns/search-box.md
Labels: Documentation 📝, Review: Code +1, Review: QA +1

#3644 Fix border when hovering disabled base button
  scss/_patterns_buttons.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3646 Document formatting in table cells
  scss/standalone/patterns_table-sortable.scss
  templates/docs/base/tables.md
  templates/docs/examples/patterns/tables/table-formatting.html
Labels: Documentation 📝, Review: Code +1, Review: QA +1

#3645 Clarify base button role
  templates/docs/patterns/buttons.md
Labels: Documentation 📝, Review: QA +1

#3647 Add bottom margin to embedded-media, to match paragraph bottom margin
  scss/_utilities_embedded-media.scss
Labels: Maintenance 🔨, Review: Code +1, Review: Design +1, Review: QA +1

#3651 Replace custom suru scss and inline bg image with built-in suru
  scss/docs/site.scss
  templates/404.html
  templates/500.html
  templates/accessibility.html
  templates/browser-support.html
  templates/contribute.html
  templates/index.html
  templates/showcase.html
Labels: Maintenance 🔨, Review: Code +1, Review: Design +1, Review: QA +1

#3654 Merge PR with master before running Percy
  .circleci/config.yml
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3650 Document ability to add icon classes to anchor tags
  templates/docs/examples/patterns/icons/icons-links.html
  templates/docs/patterns/icons.md
Labels: Documentation 📝, Review: Code +1, Review: QA +1

#3657 Simplify external link icon example
  templates/docs/examples/patterns/links/links-external-typography.html
  templates/docs/examples/patterns/links/links-external.html
Labels: Documentation 📝, Review: Code +1, Review: QA +1

#3656 Change width of medium application panel
  scss/_layouts_application.scss
Labels: Maintenance 🔨, Review: Code +1, Review: Design needed, Review: QA +1

#3660 Add Vanilla-branded Suru to the website
  scss/_patterns_strip.scss
  scss/docs/site.scss
Labels: Maintenance 🔨, Review: Code +1, Review: Design +1, Review: QA +1

#3661 Document figure support on images
  templates/docs/examples/patterns/image/caption.html
  templates/docs/patterns/images.md
Labels: Documentation 📝, Review: Code +1, Review: QA +1

#3672 Remove aliceOS logo from home page
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#3678 Change modal dialog overflow to auto
  scss/_patterns_modal.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3677 Detached tooltip
  package.json
  scss/_patterns_tooltips.scss
  templates/_layouts/docs.html
  templates/docs/component-status.md
  templates/docs/examples/patterns/tooltips/_tooltips_script.js
  templates/docs/examples/patterns/tooltips/default.html
  templates/docs/examples/patterns/tooltips/detached.html
  templates/docs/patterns/tooltips.md
Labels: Feature 🎁, Review: Code +1, Review: QA +1
