Repository canonical/vanilla-framework, pull requests merged in 2021-08, with the labels that each got.

#3904 Make notificaiton margin-bottom not depend on scaling factor
  scss/_patterns_notifications.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3909 increase z-index of hr without margin bottom
  scss/_base_placeholders.scss
Labels: Bug 🐛, Review: Code needed, Review: QA needed

#3899 Add password toggle pattern
  package.json
  scss/_patterns_form-password-toggle.scss
  scss/_patterns_icons.scss
  scss/_vanilla.scss
  scss/standalone/patterns_form-password-toggle.scss
  templates/docs/base/forms.md
  templates/docs/component-status.md
  templates/docs/examples/patterns/forms/_script.js
  templates/docs/examples/patterns/forms/password-toggle.html
  templates/docs/examples/patterns/icons/icons-additional.html
  templates/docs/examples/patterns/icons/icons-light.html
  templates/docs/patterns/icons.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1, Feature 🎁

#3912 Cross list
  scss/_patterns_lists.scss
  templates/_layouts/docs.html
  templates/docs/component-status.md
  templates/docs/examples/patterns/lists/lists-status.html
  templates/docs/patterns/lists.md
Labels: Review: QA +1, Review: Code +1, Feature 🎁

#3917 Hide Chrome's search clear icon on search and filter pattern
  scss/_patterns_search-and-filter.scss
Labels: Review: QA +1, Review: Code +1, Bug 🐛

#3925 Document mandatory nature of cancel button in `p-search-box` pattern
  templates/docs/patterns/search-box.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝

#3930 Add right padding to deprecated notification response element
  scss/_patterns_notifications.scss
  scss/standalone/patterns_notifications.scss
Labels: Review: QA +1, Review: Code +1, Bug 🐛

#3931 Enable labels to truncate with ellipses
  scss/_base_forms.scss
  templates/docs/examples/utilities/truncate.html
Labels: Review: QA +1, Review: Code +1, Bug 🐛

#3921 `p-tab-buttons` pattern
  scss/_base_button.scss
  scss/_patterns_tab-buttons.scss
  scss/_vanilla.scss
  scss/standalone/patterns_tab-buttons.scss
  templates/_layouts/docs.html
  templates/docs/component-status.md
  templates/docs/examples/patterns/tab-buttons/default.html
  templates/docs/examples/patterns/tab-buttons/dense.html
  templates/docs/examples/patterns/tab-buttons/icons.html
  templates/docs/patterns/tabs.md
  tests/parker.js
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1, Feature 🎁

#3933 update side nav labels for 2.34.0
  templates/_layouts/docs.html
  templates/docs/base/forms.md
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#3948 Update asterisk on required form fields
  package.json
  scss/_base_forms-tick-elements.scss
  scss/_base_forms.scss
  scss/_patterns_form-tick-elements.scss
  templates/docs/base/forms.md
  templates/docs/examples/patterns/forms/forms-required.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Feature 🎁
