Repository canonical/vanilla-framework, pull requests merged in 2021-12, with the labels that each got.

#4173 Prevent renovate from upgrading python in CircleCi image
  renovate.json
Labels: Review: Code +1, Maintenance 🔨

#4168 Add theming for chips
  scss/_patterns_chip.scss
  scss/_settings_colors.scss
  scss/_settings_themes.scss
  templates/docs/examples/patterns/chip/dark.html
  templates/docs/examples/patterns/chip/variants.html
  templates/docs/patterns/chip.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Feature 🎁

#4176 Refactor margin/gutter scss maps
  scss/_base_grid-definitions.scss
  scss/_base_hr.scss
  scss/_layouts_fluid-breakout.scss
  scss/_patterns_divider.scss
  scss/_patterns_grid.scss
  scss/_patterns_logo-section.scss
  scss/_patterns_navigation.scss
  scss/_patterns_side-navigation.scss
  scss/_settings_grid.scss
  templates/docs/upgrade-guide-v3.md
Labels: Review: Code +1, Breaking change 💣, Maintenance 🔨

#4177 Remove unnecessary margin reset
  scss/_patterns_table-expanding.scss
Labels: Review: QA +1, Review: Code +1, Bug 🐛

#4178 Update internal dependencies at any time
  renovate.json
Labels: Review: Code +1, Maintenance 🔨

#4181 Attempt to force node LTS version in renovate
  .github/workflows/pr.yml
  .github/workflows/publish-on-release.yml
  package.json
  renovate.json
Labels: Review: Code +1, Maintenance 🔨

#4185 Add missing import sections
  templates/docs/layouts/application.md
  templates/docs/layouts/sticky-footer.md
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#4190 Wrap font-face definitions in `@at-root`
  scss/_base_fontfaces.scss
Labels: Review: Code +1, Bug 🐛

#4197 Reword text-max-width section of upgrade guide
  templates/docs/upgrade-guide-v3.md
Labels: Review: Code +1, Documentation 📝

#4196 Add contextual menu icon update to upgrade guide
  templates/docs/upgrade-guide-v3.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝

#4202 Remove specific node versions from package.json
  package.json
Labels: Review: Code +1, Maintenance 🔨

#4198 Add code pattern changes to upgrade guide
  templates/docs/upgrade-guide-v3.md
Labels: Review: QA +1, Documentation 📝

#4199 Add new Accordion section to upgrade guide
  templates/docs/upgrade-guide-v3.md
Labels: Review: QA +1, Documentation 📝

#4201 Add search box description to upgrade guide
  templates/docs/upgrade-guide-v3.md
Labels: Review: QA +1, Documentation 📝

#4203 Add breadcrumbs to upgrade guide
  templates/docs/upgrade-guide-v3.md
Labels: Review: QA +1, Documentation 📝

#4204 Change order of variable names
  templates/docs/upgrade-guide-v3.md
Labels: Review: QA needed, Documentation 📝

#4207 Improve the docs around breakpoints
  templates/docs/upgrade-guide-v3.md
Labels: Review: QA +1

#4208 Fix sass deprecation warning
  scss/_patterns_chip.scss
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#4210 Make the naming of tables and class names more consistent
  templates/docs/upgrade-guide-v3.md
Labels: Review: QA +1, Documentation 📝

#4212 Add image module and update images
  .github/workflows/pr.yml
  requirements.txt
  templates/_layouts/site.html
  templates/index.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#4218 Reorder migration guide
  templates/docs/migration-guide-to-v3.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝

#4216 Update homepage
  templates/index.html
Labels: Review: QA +1, Review: Code +1, Documentation 📝

#4219 Update what's new page
  templates/docs/changelog-v2.md
  templates/docs/migration-guide-to-v3.md
  templates/docs/whats-new.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝

#4223 Update README on vanilla website
  README.md
Labels: Review: QA +1, Documentation 📝

#4221 Add updated labels to side navigation
  templates/_layouts/docs.html
  templates/docs/patterns/search-box.md
  templates/docs/whats-new.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝
