Repository canonical/vanilla-framework, pull requests merged in 2021-02, with the labels that each got.

#3528 Improve docs about autoprefixer
  README.md
  templates/docs/building-vanilla.md
Labels: Documentation 📝, Review: Code +1, Review: QA +1

#3529 Fix Vanilla version in the docs
  templates/docs/component-status.md
Labels: Documentation 📝

#3527 Code snippet: multiple dropdowns
  .spelling
  scss/_patterns_code-snippet.scss
  scss/standalone/patterns_code-snippet.scss
  templates/docs/base/code.md
  templates/docs/component-status.md
  templates/docs/examples/patterns/code-snippet/_script.js
  templates/docs/examples/patterns/code-snippet/default.html
  templates/docs/examples/patterns/code-snippet/dropdown-multiple.html
  templates/docs/examples/patterns/code-snippet/dropdown.html
  templates/docs/examples/patterns/code-snippet/icon.html
  templates/docs/examples/patterns/code-snippet/numbered.html
  templates/docs/examples/patterns/code-snippet/prism.html
  templates/docs/examples/patterns/code-snippet/wrapping.html
Labels: Feature 🎁, Review: Code +1, Review: Design +1, Review: QA +1

#3531 Automate version in title of component status page
  templates/docs/component-status.md
  webapp/app.py
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3535 Remove word-break: break-all from code element
  scss/_base_code.scss
  scss/_settings_spacing.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3538 Apply !important on all properties of the .u-vertically-center utuility class
  scss/_utilities_vertically-center.scss
  scss/_vanilla.scss
Labels: Review: Code +1, Review: QA +1

#3504 Add .row-breakout to enable layouts that spill into the page margins
  scss/_base_grid-definitions.scss
  scss/_layouts_fluid-breakout.scss
  scss/_patterns_grid.scss
  scss/_settings_grid.scss
  scss/_vanilla.scss
  scss/standalone/layouts_fluid-breakout-full.scss
  scss/standalone/layouts_fluid-breakout.scss
  templates/_layouts/docs.html
  templates/docs/examples/layouts/fluid-breakout/_aside.html
  templates/docs/examples/layouts/fluid-breakout/_cve-table.html
  templates/docs/examples/layouts/fluid-breakout/fluid-breakout-cards-and-aside.html
  templates/docs/examples/layouts/fluid-breakout/fluid-breakout-full--cve-table.html
  templates/docs/examples/layouts/fluid-breakout/fluid-breakout-full.html
  templates/docs/examples/layouts/fluid-breakout/fluid-breakout-left-aside.html
  templates/docs/examples/layouts/fluid-breakout/fluid-breakout-no-aside.html
  templates/docs/examples/layouts/fluid-breakout/fluid-breakout-right-aside.html
  templates/docs/examples/layouts/fluid-breakout/visualize-grid.css
  templates/docs/examples/patterns/card/_header-and-footer.html
  templates/docs/layouts/fluid-breakout.md
  templates/docs/patterns/grid.md
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3543 Add .is-dark support for inline code element
  scss/_base_code.scss
  scss/_layouts_application.scss
  scss/_settings_colors.scss
  templates/docs/base/code.md
  templates/docs/component-status.md
  templates/docs/examples/base/code-inline-dark.html
  templates/docs/examples/layouts/application/structure.html
Labels: Maintenance 🔨, Review: Code +1, Review: Design +1, Review: QA +1

#3560 Add small capitalised style, utilities to align small and paragraph text
  scss/_base_typography.scss
  scss/_utilities_content-align.scss
Labels: Review: Code +1, Review: QA +1

#3561 Add light and dense version of hr
  scss/_base_hr.scss
  scss/_base_placeholders.scss
Labels: Review: Code +1, Review: QA +1

#3569 Show ellipsis on buttons that launch modals
  templates/docs/examples/patterns/contextual-menu/dark.html
  templates/docs/examples/patterns/contextual-menu/default.html
  templates/docs/examples/patterns/modal/default.html
  templates/docs/examples/patterns/modal/modal-scroll.html
  templates/docs/examples/templates/z-index.html
  templates/docs/patterns/contextual-menu.md
  templates/docs/patterns/modal.md
Labels: Maintenance 🔨, Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3573 Ubuntu mono font bugs
  scss/_base_code.scss
  scss/_base_fontfaces.scss
  scss/_patterns_code-copyable.scss
  scss/_patterns_code-snippet.scss
Labels: Bug 🐛, Review: Code +1, Review: Design +1, Review: QA +1

#3581 add "Edit on CodePen" link to code snippet examples
  templates/static/js/example.js
Labels: Maintenance 🔨, Review: Code +1, Review: Design +1, Review: QA +1

#3572 Focus on first focusable element within a dialog when launching
  templates/docs/examples/patterns/contextual-menu/_script.js
  templates/docs/examples/patterns/modal/_script.js
  templates/docs/patterns/contextual-menu.md
  templates/docs/patterns/modal.md
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1, Review: UX +1

#3583 Add aria-pressed state to buttons
  package.json
  scss/_base_button.scss
  scss/standalone/patterns_buttons.scss
  templates/_layouts/docs.html
  templates/docs/component-status.md
  templates/docs/examples/patterns/buttons/pressed.html
  templates/docs/examples/patterns/contextual-menu/_script.js
  templates/docs/patterns/buttons.md
  tests/parker.js
Labels: Maintenance 🔨, Review: Code +1, Review: Design +1, Review: QA +1

#3585 Document hr classes is-muted, is-fixed-width
  templates/docs/base/separators.md
  templates/docs/examples/base/hr-fixed-width.html
  templates/docs/examples/base/hr-muted.html
Labels: Review: Code +1, Review: QA +1

#3584 Fix margin right on multiple buttons of mixed element types
  scss/_base_button.scss
  scss/_patterns_chip.scss
  scss/_patterns_search-box.scss
  scss/standalone/patterns_notifications.scss
  templates/docs/examples/patterns/buttons/alignment.html
  templates/docs/examples/templates/maas-layout.html
Labels: Breaking change 💣, Bug 🐛, Focal 20.04, Review: Code +1, Review: QA +1

#3588 Add .is-dark utility and theming support to middot list
  scss/_patterns_lists.scss
  scss/_settings_themes.scss
  scss/standalone/dark.scss
  templates/docs/component-status.md
  templates/docs/examples/patterns/lists/lists-mid-dot-dark.html
  templates/docs/patterns/lists.md
  templates/docs/settings/color-settings.md
Labels: Feature 🎁, Review: Code +1, Review: Design +1, Review: QA +1
