Repository canonical/vanilla-framework, pull requests merged in 2021-06, with the labels that each got.

#3772 Remove background from link button.
  scss/_patterns_buttons.scss
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#3765 Move subnav styles to main nav styles
  package.json
  scss/_patterns_navigation.scss
  scss/_patterns_subnav.scss
  templates/_layouts/docs.html
  templates/docs/component-status.md
  templates/docs/examples/patterns/navigation/_script.js
  templates/docs/examples/patterns/navigation/deprecated-dark.html
  templates/docs/examples/patterns/navigation/deprecated-subnav-dark.html
  templates/docs/examples/patterns/navigation/deprecated-subnav.html
  templates/docs/examples/patterns/navigation/deprecated.html
  templates/docs/examples/patterns/navigation/dropdown-dark.html
  templates/docs/examples/patterns/navigation/dropdown.html
  templates/docs/examples/templates/snapcraft-publicise.html
  templates/docs/examples/templates/z-index.html
  templates/docs/patterns/navigation.md
  templates/docs/upgrade-guide-v3.md
  tests/parker.js
Labels: Maintenance 🔨, Review: Code +1, Review: Design +1, Review: QA +1

#3783 Fix small typo in navigation examples
  templates/docs/examples/layouts/documentation.html
  templates/docs/examples/patterns/navigation/default-dark.html
  templates/docs/examples/patterns/navigation/default.html
  templates/docs/examples/patterns/navigation/full-width.html
Labels: Bug 🐛, Review: Code needed, Review: QA needed

#3796 Add `has-overflow` utility to tables
  package.json
  scss/_base_tables.scss
  scss/_patterns_table-expanding.scss
  scss/standalone/patterns_table-overflow.scss
  templates/_layouts/docs.html
  templates/docs/base/tables.md
  templates/docs/component-status.md
  templates/docs/examples/patterns/tables/table-overflow.html
Labels: Feature 🎁, Review: Code +1, Review: QA +1

#3799 Fix title of `has-overflow` item in component status page
  templates/docs/component-status.md
  webapp/app.py
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3810 Remove showcase page
  redirects.yaml
  templates/_layouts/_header.html
  templates/docs/examples/patterns/tabs/navigation.html
  templates/showcase.html
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3812 add 410 template for deleted content
  deleted.yaml
  redirects.yaml
  templates/410.html
Labels: Maintenance 🔨, Review: Code +1, Review: QA +1

#3811 Website accessibility fixes
  templates/_layouts/_header.html
  templates/accessibility.html
  templates/browser-support.html
  templates/docs/examples/index.html
  templates/docs/examples/standalone.html
  templates/docs/index.html
  templates/index.html
Labels: Maintenance 🔨, Review: Code +1, Review: Design +1, Review: QA +1

#3801 Add p-label
  scss/_patterns_label.scss
  scss/_settings_colors.scss
  templates/_layouts/docs.html
  templates/docs/component-status.md
  templates/docs/examples/patterns/labels/default.html
  templates/docs/patterns/labels.md
Labels: Feature 🎁, Review: Code +1, Review: QA +1
