Repository canonical/vanilla-framework, pull requests merged in 2022-01, with the labels that each got.

#4228 Update search in navigation to expanding search
  run
  templates/_layouts/_header.html
  templates/_layouts/_root.html
  templates/_layouts/docs.html
  templates/docs/examples/patterns/navigation/_script-search.js
  templates/static/js/scripts.js
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#4231 Bump version to 3.0.0
  package.json
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#4233 Add accessibility accordion notes
  templates/docs/patterns/accordion.md
Labels: Review: QA +1, Accessibility

#4234 Add lists accessibility doc
  templates/docs/patterns/lists.md
Labels: Review: QA +1, Documentation 📝

#4235 Add link accessibility doc
  templates/docs/patterns/links.md
Labels: Review: QA +1, Documentation 📝

#4239 Add search box accessibility doc
  templates/docs/patterns/search-box.md
Labels: Review: QA +1, Documentation 📝

#4237 Add accessibility card text
  templates/docs/patterns/accordion.md
  templates/docs/patterns/breadcrumbs.md
  templates/docs/patterns/card.md
  templates/docs/patterns/lists.md
Labels: Review: QA +1, Documentation 📝

#4241 Add tooltip accessibility doc
  .spelling
  templates/docs/patterns/links.md
  templates/docs/patterns/tooltips.md
Labels: Review: QA +1, Documentation 📝

#4248 Fix notifications in docs
  templates/docs/base/forms.md
  templates/docs/layouts/application.md
  templates/docs/patterns/accordion.md
  templates/docs/patterns/buttons.md
  templates/docs/patterns/contextual-menu.md
  templates/docs/patterns/labels.md
  templates/docs/patterns/matrix.md
  templates/docs/patterns/navigation.md
  templates/docs/patterns/search-and-filter.md
  templates/docs/patterns/search-box.md
  templates/docs/patterns/strip.md
  templates/docs/patterns/tooltips.md
  templates/docs/settings/animation-settings.md
  templates/docs/settings/color-settings.md
  templates/docs/utilities/image-position.md
Labels: Review: QA needed, Review: Code needed, Bug 🐛

#4252 Merge Button Accessibility sections into one
  templates/docs/patterns/buttons.md
Labels: Review: QA needed, Documentation 📝

#4253 Update slider style
  package.json
  scss/_base_forms-range.scss
  templates/docs/examples/base/forms/range.html
  templates/docs/examples/patterns/slider/slider-input.html
Labels: Review: Design needed, Review: QA +1, Review: Code +1, Maintenance 🔨

#4255 Fix broken link in docs
  templates/docs/migration-guide-to-v3.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝

#4254 Updated switch styling
  scss/_patterns_switch.scss
Labels: Review: QA +1, Review: Design +1, Review: Code needed, Maintenance 🔨

#4260 Add role=switch to switch component
  templates/docs/examples/patterns/switch.html
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨, Accessibility

#4261 Removed right alignment in card example
  scss/standalone/patterns_card.scss
  templates/docs/examples/patterns/card/content-bleed.html
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#4264 Add nested counter to order lists
  package.json
  scss/_patterns_lists.scss
  templates/_layouts/docs.html
  templates/docs/examples/patterns/lists/list-nested-count.html
  templates/docs/patterns/lists.md
  templates/docs/whats-new.md
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#4262 Logo section accessibility doc
  .spelling
  templates/docs/examples/patterns/logo-section/logo-section.html
  templates/docs/patterns/logo-section.md
Labels: Review: Code +1, Documentation 📝

#4268 Add label accessibility doc
  templates/docs/patterns/labels.md
Labels: Review: QA +1, Documentation 📝

#4269 Add pagination accessibility docs
  .spelling
  templates/docs/patterns/pagination.md
Labels: Review: QA +1, Documentation 📝

#4271 Add switch accessibility docs
  templates/docs/patterns/switch.md
Labels: Review: QA +1, Documentation 📝

#4267 Added min-height to close button
  scss/_patterns_notifications.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Bug 🐛

#4275 Add grid accessibility notes
  templates/docs/patterns/grid.md
Labels: Review: QA +1, Documentation 📝

#4277 Add heading icon accessibility docs
  templates/docs/patterns/heading-icon.md
Labels: Review: QA +1, Documentation 📝

#4286 Add icon accessibility docs
  templates/docs/patterns/icons.md
Labels: Documentation 📝

#4288 Added notification accessibility docs
  templates/docs/examples/patterns/notifications/action.html
  templates/docs/examples/patterns/notifications/timestamp.html
  templates/docs/patterns/notification.md
Labels: Review: QA +1, Documentation 📝
