Repository canonical/vanilla-framework, pull requests merged in 2022-03, with the labels that each got.

#4358 Add accessibility docs for strip
  templates/docs/patterns/strip.md
Labels: Review: QA +1, Documentation 📝

#4359 Close contextual menu when focus leaves
  templates/docs/examples/patterns/contextual-menu/_script.js
Labels: Review: QA +1, Bug 🐛, Review: Code +1 (with changes)

#4363 Fix broken `snippet__line` outside of `snippet_block--numbered`
  package.json
  scss/_patterns_code-snippet.scss
Labels: Review: QA +1, Review: Code +1, Bug 🐛

#4361 Update aria-labels on landmarks
  templates/_layouts/_footer.html
  templates/_layouts/_header.html
  templates/_layouts/docs.html
  templates/docs/examples/layouts/documentation.html
  templates/docs/examples/layouts/sticky-footer.html
  templates/docs/examples/patterns/links/links-skip.html
  templates/docs/examples/patterns/navigation/default-dark.html
  templates/docs/examples/patterns/navigation/default.html
  templates/docs/examples/patterns/navigation/dropdown-dark.html
  templates/docs/examples/patterns/navigation/full-width.html
  templates/docs/examples/patterns/navigation/search-dark.html
  templates/docs/examples/patterns/navigation/search-light.html
  templates/docs/examples/patterns/side-navigation/_default.html
  templates/docs/examples/patterns/side-navigation/_docs.html
  templates/docs/examples/patterns/side-navigation/_layout-JAAS.html
  templates/docs/examples/patterns/side-navigation/_layout-application.html
  templates/docs/examples/templates/maas-docs-grid.html
  templates/docs/examples/templates/maas-layout.html
  templates/docs/examples/templates/snapcraft-publicise.html
  templates/docs/examples/templates/z-index.html
Labels: Review: QA +1, Review: Code +1, Bug 🐛
