Repository canonical/vanilla-framework, pull requests merged in 2022-12, with the labels that each got.

#4402 Update styling of buttons and form elements
  package.json
  scss/_base_button.scss
  scss/_base_code.scss
  scss/_base_forms-range.scss
  scss/_base_forms.scss
  scss/_base_hr.scss
  scss/_base_placeholders.scss
  scss/_layouts_fluid-breakout.scss
  scss/_patterns_card.scss
  scss/_patterns_chip.scss
  scss/_patterns_contextual-menu.scss
  scss/_patterns_form-tick-elements.scss
  scss/_patterns_form-validation.scss
  scss/_patterns_icons.scss
  scss/_patterns_links.scss
  scss/_patterns_lists.scss
  scss/_patterns_logo-section.scss
  scss/_patterns_matrix.scss
  scss/_patterns_modal.scss
  scss/_patterns_navigation.scss
  scss/_patterns_notifications.scss
  scss/_patterns_search-and-filter.scss
  scss/_patterns_search-box.scss
  scss/_patterns_segmented-control.scss
  scss/_patterns_side-navigation.scss
  scss/_patterns_strip.scss
  scss/_patterns_switch.scss
  scss/_patterns_table-sortable.scss
  scss/_settings_colors.scss
  scss/_settings_grid.scss
  scss/_settings_placeholders.scss
  scss/_settings_spacing.scss
  scss/_utilities_font-metrics.scss
  scss/_utilities_margin-collapse.scss
  scss/_utilities_vertical-spacing.scss
  scss/standalone/patterns_navigation.scss
  templates/_layouts/docs.html
  templates/docs/examples/patterns/navigation/deprecated.html
  templates/docs/examples/patterns/search-box/default-dark.html
  templates/docs/whats-new.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Feature 🎁

#4615 Add hover states for checkboxes
  scss/_patterns_form-tick-elements.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Bug 🐛

#4619 Increase z-index of the modal so that it overlays the navigation drawer
  scss/_patterns_modal.scss
Labels: Review: QA +1, Review: Code +1, Bug 🐛
