Repository canonical/vanilla-framework, pull requests merged in 2022-10, with the labels that each got.

#4591 Make password text easier to read when toggled
  scss/_patterns_form-password-toggle.scss
Labels: Maintenance 🔨, Review: Code +1 (with changes)

#4584 Stepped counter size
  scss/_patterns_lists.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Feature 🎁

#4601 Revert to new logo style
  templates/_layouts/_header.html
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#4602 Fix warning for division operator
  scss/_patterns_lists.scss
Labels: Review: QA +1, Review: Code +1, Bug 🐛

#4603 Update the underline style of links on hover
  scss/_base_links.scss
Labels: Review: Design +1, Review: Code +1, Maintenance 🔨
