Repository canonical/vanilla-framework, pull requests merged in 2022-04, with the labels that each got.

#4390 Fix search by providing search engine id
  webapp/app.py
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#4386 Make top nav adjustments (size and highlight colour)
  scss/_patterns_navigation.scss
  templates/docs/examples/patterns/navigation/deprecated.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Feature 🎁

#4394 Nav spacing: increase gap between logo and menu items
  scss/_patterns_navigation.scss
Labels: Review: QA +1, Review: Code +1

#4399 Remove design section from docs
  templates/docs/base/typography.md
  templates/docs/patterns/breadcrumbs.md
  templates/docs/patterns/heading-icon.md
  templates/docs/patterns/images.md
  templates/docs/patterns/list-tree.md
  templates/docs/patterns/matrix.md
  templates/docs/patterns/media-object.md
  templates/docs/patterns/muted-heading.md
  templates/docs/patterns/pull-quote.md
  templates/docs/patterns/switch.md
  templates/docs/patterns/table-of-contents.md
  templates/docs/settings/animation-settings.md
  templates/docs/settings/color-settings.md
  templates/docs/settings/font-settings.md
  templates/docs/utilities/image-position.md
Labels: Review: QA +1, Maintenance 🔨

#4407 Revert to old style logo
  templates/_layouts/_header.html
Labels: Review: QA +1, Review: Code +1

#4409 Update side nav for 3.2
  templates/_layouts/docs.html
Labels: Review: QA +1, Review: Code +1

#4401 Separate Tab buttons from tabs
  templates/_layouts/docs.html
  templates/docs/patterns/tab-buttons.md
  templates/docs/patterns/tabs.md
Labels: Review: QA +1, Don't merge, Maintenance 🔨

#4406 Update accordion
  package.json
  scss/_patterns_accordion.scss
  templates/_layouts/docs.html
  templates/docs/whats-new.md
Labels: Review: QA +1, Review: Design +1, Feature 🎁, Review: Code +1 (with changes)

#4414 Add component menu
  component_tabs.yaml
  templates/_layouts/_component_tabs.html
  templates/_layouts/docs.html
  templates/_layouts/docs_discourse.html
  templates/docs/patterns/accordion/accessibility.md
  templates/docs/patterns/accordion/index.md
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#4427 Add menu to all patterns
  component_tabs.yaml
  templates/docs/patterns/breadcrumbs/accessibility.md
  templates/docs/patterns/breadcrumbs/index.md
  templates/docs/patterns/buttons/accessibility.md
  templates/docs/patterns/buttons/index.md
  templates/docs/patterns/card/accessibility.md
  templates/docs/patterns/card/index.md
  templates/docs/patterns/chip.md
  templates/docs/patterns/contextual-menu/accessibility.md
  templates/docs/patterns/contextual-menu/index.md
  templates/docs/patterns/grid/accessibility.md
  templates/docs/patterns/grid/index.md
  templates/docs/patterns/heading-icon/accessibility.md
  templates/docs/patterns/heading-icon/index.md
  templates/docs/patterns/icons/accessibility.md
  templates/docs/patterns/icons/index.md
  templates/docs/patterns/links/accessibility.md
  templates/docs/patterns/links/index.md
  templates/docs/patterns/lists/accessibility.md
  templates/docs/patterns/lists/index.md
  templates/docs/patterns/logo-section/accessibility.md
  templates/docs/patterns/logo-section/index.md
  templates/docs/patterns/modal/accessibility.md
  templates/docs/patterns/modal/index.md
  templates/docs/patterns/navigation/accessibility.md
  templates/docs/patterns/navigation/index.md
  templates/docs/patterns/notification/accessibility.md
  templates/docs/patterns/notification/index.md
  templates/docs/patterns/pagination/accessibility.md
  templates/docs/patterns/pagination/index.md
  templates/docs/patterns/search-box/accessibility.md
  templates/docs/patterns/search-box/index.md
  templates/docs/patterns/segmented-control.md
  templates/docs/patterns/status-labels/accessibility.md
  templates/docs/patterns/status-labels/index.md
  templates/docs/patterns/strip/accessibility.md
  templates/docs/patterns/strip/index.md
  templates/docs/patterns/switch/accessibility.md
  templates/docs/patterns/switch/index.md
  templates/docs/patterns/tabs/accessibility.md
  templates/docs/patterns/tabs/index.md
  templates/docs/patterns/tooltips/accessibility.md
  templates/docs/patterns/tooltips/index.md
  webapp/app.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#4435 Fix nav active for design
  templates/_layouts/_header.html
Labels: Review: QA +1, Review: Code +1

#4436 Update accordion docs
  templates/docs/patterns/accordion.md
Labels: Review: QA needed

#4431 Fix version in package.json
  package.json
Labels: Review: Code +1, Maintenance 🔨

#4424 Align accordion's icon with heading
  scss/_patterns_accordion.scss
Labels: Review: QA +1, Review: Code +1

#4432 Fix page jumping after codepen loads
  templates/static/js/example.js
Labels: Review: QA +1, Bug 🐛, Review: Code +1 (with changes)

#4371 Ensure sidenav is only tabable when in view
  scss/_patterns_side-navigation.scss
  templates/_class-references/side-navigation.html
  templates/docs/examples/patterns/side-navigation/_toggle_script.js
  templates/docs/patterns/navigation/accessibility.md
  templates/docs/patterns/navigation/index.md
  templates/static/js/scripts.js
Labels: Review: QA +1, Review: Code +1, Bug 🐛

#4443 Add accessibility doc for quotes
  component_tabs.yaml
  templates/docs/patterns/pull-quote/accessibility.md
  templates/docs/patterns/pull-quote/index.md
Labels: Review: QA +1, Documentation 📝
