Repository canonical/vanilla-framework, pull requests merged in 2022-06, with the labels that each got.

#4489 Close side nav drawer when anchors are clicked
  templates/static/js/scripts.js
Labels: Review: QA +1, Review: Code +1, Documentation 📝

#4497 Create badge component
  component_tabs.yaml
  package.json
  scss/_patterns_badge.scss
  scss/_patterns_tabs.scss
  scss/_vanilla.scss
  scss/standalone/patterns_badge.scss
  templates/_layouts/docs.html
  templates/docs/examples/patterns/badge/chips.html
  templates/docs/examples/patterns/badge/colors.html
  templates/docs/examples/patterns/badge/default.html
  templates/docs/examples/patterns/badge/side-navigation.html
  templates/docs/examples/patterns/badge/tabs.html
  templates/docs/patterns/badge/accessibility.md
  templates/docs/patterns/badge/index.md
  templates/docs/whats-new.md
Labels: Review: QA +1, Feature 🎁, Review: Code +1 (with changes)

#4498 Fix the logo title to a specific font size
  scss/_patterns_navigation.scss
Labels: Review: QA +1, Bug 🐛, Review: Code +1 (with changes)
