Repository canonical/vanilla-framework, pull requests merged in 2023-03, with the labels that each got.

#4673 Revert What's new page to 3.12 release
  templates/docs/whats-new.md
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#4669 Use chevron icon in article pagination
  scss/_patterns_article-pagination.scss
Labels: Review: QA +1, Review: Code +1, Bug 🐛

#4682 Removed highlight of side nav items on search results page [WD-2276]
  webapp/app.py
Labels: Review: QA +1, Review: Code +1, Bug 🐛

#4686 Set version in releases.yml file to 3.12.1
  releases.yml
Labels: Review: Code +1, Maintenance 🔨

#4693 Fix icon override on the main page
  templates/index.html
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#4700 Add missing page to side navigation
  side-navigation.yaml
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#4701 Fixes incorrect aria-label on tabs examples
  templates/docs/examples/patterns/segmented-control/default.html
  templates/docs/examples/patterns/segmented-control/dense.html
  templates/docs/examples/patterns/segmented-control/icons.html
  templates/docs/examples/patterns/tab-buttons/default.html
  templates/docs/examples/patterns/tab-buttons/dense.html
  templates/docs/examples/patterns/tab-buttons/icons.html
  templates/docs/examples/patterns/tabs/content.html
Labels: Review: QA +1, Documentation 📝

#4717 Add unified spacing utils
  package.json
  releases.yml
  scss/_settings_spacing.scss
  scss/_utilities_vertical-spacing.scss
  templates/docs/examples/utilities/vertical-spacing-unit.html
  templates/docs/examples/utilities/vertical-spacing.html
  templates/docs/utilities/vertical-spacing.md
Labels: Review: QA +1, Review: Code +1, Feature 🎁
