Repository canonical/vanilla-framework, pull requests merged in 2023-02, with the labels that each got.

#4649 Bring back upload-assets CLI tool for release
  .github/workflows/publish-on-release.yml
Labels: Review: Code +1, Maintenance 🔨

#4658 Update top nav font weight
  scss/_base_typography-definitions.scss
  scss/_patterns_navigation.scss
  scss/_settings_font.scss
Labels: Review: Design +1, Review: Code +1, Bug 🐛

#4657 Fix nesting row in fixed width container
  scss/_utilities_layout.scss
  templates/docs/examples/utilities/fixed-width-container-nesting.html
Labels: Review: QA +1, Review: Code +1, Bug 🐛

#4660 Fix the calculation of hr margin
  scss/_base_hr.scss
Labels: Review: Design +1, Review: Code +1, Bug 🐛

#4661 Add missing secret for upload-assets snap
  .github/workflows/publish-on-release.yml
Labels: Review: Code +1, Maintenance 🔨

#4665 Fix font size of all caps text component
  package.json
  redirects.yaml
  scss/_base_typography-definitions.scss
  scss/_base_typography.scss
  scss/_patterns_muted-heading.scss
  templates/docs/base/typography.md
  templates/docs/examples/patterns/text-small-caps.html
  templates/docs/examples/patterns/x-small-capitalised.html
  templates/docs/examples/utilities/align-by-baseline.html
  templates/docs/whats-new.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Feature 🎁

#4671 Set white background for search and filter dropdown [WD-2279]
  scss/_patterns_search-and-filter.scss
Labels: Review: QA +1, Review: Code +1, Bug 🐛
