Repository canonical/vanilla-framework, pull requests merged in 2023-01, with the labels that each got.

#4625 reduce social icon sizes to work better next to headings
  scss/_base_placeholders.scss
Labels: Review: Code +1

#4616 Update imports to the variable font beta
  scss/_base_fontfaces.scss
  scss/_settings_font.scss
  templates/_layouts/docs.html
  templates/docs/base/typography.md
  templates/docs/examples/base/font-weights.html
  templates/docs/examples/base/variable-font.html
  templates/docs/settings/font-settings.md
  templates/docs/whats-new.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#4623 Temporary script to fix the upload assets job
  .github/workflows/publish-on-release.yml
  scripts/upload_assets.py
Labels: Review: Code +1, Maintenance 🔨

#4630 Fix link for Chrome Accessibility Developer Tools
  templates/accessibility.html
Labels: Review: QA +1, Documentation 📝

#4621 New full-width layout for Design System website [WD-775]
  package.json
  scss/_layouts_full-width.scss
  scss/_vanilla.scss
  templates/docs/examples/layouts/full-width/default.html
  templates/docs/examples/layouts/full-width/no-sidebar.html
  templates/docs/examples/patterns/side-navigation/_toggle_script.js
  templates/docs/whats-new.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Feature 🎁
