Repository canonical/vanilla-framework, pull requests merged in 2023-05, with the labels that each got.

#4756 Revert logo font size to match logo sizing
  scss/_patterns_navigation.scss
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#4759 Update rule-highlight pattern to use to appropriate class
  templates/docs/examples/layouts/brochure-site/_25-75-nested.html
Labels: Review: QA needed, Review: Code needed, Documentation 📝

#4772 Add paper colour variable
  package.json
  scss/_settings_colors.scss
Labels: Review: Code +1, Maintenance 🔨
