Repository canonical/vanilla-framework, pull requests merged in 2023-04, with the labels that each got.

#4722 Fix split list items overflowing in the other column
  scss/_patterns_lists.scss
  templates/docs/examples/patterns/lists/lists-split.html
Labels: Review: QA +1, Review: Code +1, Bug 🐛

#4725 Move all deps to devDeps
  Dockerfile
  package.json
Labels: Review: Code +1, Maintenance 🔨

#4732 Skip installing Chromium for production on jenkins
  Dockerfile
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#4733 Revert new vertical spacing classes
  releases.yml
  scss/_utilities_vertical-spacing.scss
  templates/docs/examples/utilities/vertical-spacing-unit.html
  templates/docs/examples/utilities/vertical-spacing.html
  templates/docs/utilities/vertical-spacing.md
Labels: Maintenance 🔨

#4738 Remove unnecessary release notes
  releases.yml
Labels: Review: QA +1, Review: Code +1

#4736 Fix alignment of heading icon
  scss/_patterns_heading-icon.scss
Labels: Review: Design needed, Review: QA +1, Review: Code +1 (with changes)

#4750 Remove border radius from images
  scss/_base_media.scss
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#4730 Add sections and blocks components
  package.json
  releases.yml
  scss/_base_placeholders.scss
  scss/_patterns_section.scss
  scss/_vanilla.scss
  scss/standalone/patterns_section.scss
  side-navigation.yaml
  templates/docs/examples/layouts/brochure-site/_25-25-50.html
  templates/docs/examples/layouts/brochure-site/_25-75-nested.html
  templates/docs/examples/layouts/brochure-site/_25-75.html
  templates/docs/examples/layouts/brochure-site/_50-50.html
  templates/docs/examples/layouts/brochure-site/index.html
  templates/docs/examples/patterns/section/block.html
  templates/docs/examples/patterns/section/section.html
  templates/docs/layouts/brochure.md
  templates/docs/patterns/section.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Feature 🎁
