Repository canonical/vanilla-framework, pull requests merged in 2023-07, with the labels that each got.

#4821 Make sure logo tag backround is not configurable
  scss/_patterns_navigation.scss
  scss/_settings_colors.scss
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#4823 Update section component
  releases.yml
  scss/_patterns_section.scss
  scss/_utilities_vertical-spacing.scss
  side-navigation.yaml
  templates/docs/examples/layouts/brochure-site/_50-50.html
  templates/docs/examples/patterns/rule/dark.html
  templates/docs/examples/patterns/section/block.html
  templates/docs/examples/patterns/section/deep.html
  templates/docs/examples/patterns/section/section.html
  templates/docs/examples/patterns/section/shallow.html
  templates/docs/layouts/brochure.md
  templates/docs/migration-guide-to-v4.md
  templates/docs/patterns/section.md
Labels: Review: Design +1, Review: Code +1, Maintenance 🔨

#4835 Remove outdated info about alpha releases
  templates/docs/migration-guide-to-v4.md
Labels: Review: QA +1, Documentation 📝

#4830 Migration guide updates
  templates/docs/migration-guide-to-v4.md
Labels: Review: QA +1, Documentation 📝

#4836 Move brochure sites example to separate category
  templates/docs/base/paper.md
  templates/docs/examples/brochure/25-25-25-25-split-structure.html
  templates/docs/examples/brochure/25-25-50-split-structure.html
  templates/docs/examples/brochure/25-25-50-split.html
  templates/docs/examples/brochure/25-75-nested.html
  templates/docs/examples/brochure/25-75-offset-structure.html
  templates/docs/examples/brochure/25-75-offset.html
  templates/docs/examples/brochure/25-75-split-structure.html
  templates/docs/examples/brochure/25-75-split.html
  templates/docs/examples/brochure/50-50-split-structure.html
  templates/docs/examples/brochure/50-50-split.html
  templates/docs/examples/brochure/_25-25-25-25-structure.html
  templates/docs/examples/brochure/_25-25-50-structure.html
  templates/docs/examples/brochure/_25-25-50.html
  templates/docs/examples/brochure/_25-75-nested.html
  templates/docs/examples/brochure/_25-75-offset-structure.html
  templates/docs/examples/brochure/_25-75-offset.html
  templates/docs/examples/brochure/_25-75-structure.html
  templates/docs/examples/brochure/_25-75.html
  templates/docs/examples/brochure/_50-50-structure.html
  templates/docs/examples/brochure/_50-50.html
  templates/docs/examples/brochure/index.html
  templates/docs/examples/index.html
  templates/docs/examples/patterns/rule/default.html
  templates/docs/examples/patterns/rule/highlight.html
  templates/docs/examples/patterns/strips/white.html
  templates/docs/layouts/brochure.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝

#4839 Fix license link
  README.md
Labels: Review: Code +1, Documentation 📝

#4817 Dark tabs
  releases.yml
  scss/_patterns_tabs.scss
  scss/_settings_themes.scss
  templates/docs/examples/patterns/tabs/content-dark.html
  templates/docs/examples/patterns/tabs/content.html
  templates/docs/patterns/tabs/index.md
  tests/parker.js
Labels: Review: QA +1, Review: Code +1, Feature 🎁

#4851 Remove Vanilla 3 changes from "What's new" page
  templates/docs/changelog-v2.md
  templates/docs/changelog-v3.html
  templates/docs/whats-new.html
Labels: Review: QA +1, Review: Code +1, Documentation 📝

#4850 Update border and font in chips
  scss/_patterns_chip.scss
Labels: Review: Design needed, Review: QA +1, Review: Code +1, Maintenance 🔨
