Repository canonical/vanilla-framework, pull requests merged in 2023-06, with the labels that each got.

#4767 Add sliding nav on mobile
  package.json
  releases.yml
  scss/_patterns_navigation.scss
  templates/docs/examples/patterns/navigation/_script-sliding.js
  templates/docs/examples/patterns/navigation/sliding-dark.html
  templates/docs/examples/patterns/navigation/sliding-light.html
  templates/docs/examples/patterns/navigation/sliding-search.html
  templates/docs/patterns/navigation/index.md
  tests/parker.js
Labels: Review: Design needed, Review: QA +1, Review: UX +1, Feature 🎁, Review: Code +1 (with changes)

#4780 Update typography docs for Vanilla 4.0
  .spelling
  templates/docs/base/typography.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝

#4804 Use ps5 registry
  konf/site.yaml
Labels: Review: Code +1, Maintenance 🔨
