Repository canonical/vanilla-framework, pull requests merged in 2023-10, with the labels that each got.

#4882 Ignore warnings to prevent redirects from failing the build
  .github/workflows/pr.yml
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#4888 Use dark search in the top navbar
  templates/_layouts/_header.html
Labels: Review: QA +1, Review: Code +1, Bug 🐛

#4890 Revert pushing to release branch
  .github/workflows/publish-on-release.yml
Labels: Review: Code needed, Maintenance 🔨

#4892 Fixed minor typos for Inline Radio and Checkbox docs
  templates/docs/examples/patterns/forms/_checkbox-inline.html
  templates/docs/examples/patterns/forms/_radio-inline.html
Labels: Review: Code +1, Documentation 📝

#4902 Bump canonicalwebteam.discourse to 5.4.3
  requirements.txt
Labels: Review: QA +1, Review: Code +1
