Repository canonical/vanilla-framework, pull requests merged in 2024-04, with the labels that each got.

#5045 Fix access to localhost server on CircleCI
  snapshots.js
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#5049 Remove get-site-urls dependency
  package.json
  yarn.lock
Labels: Review: Code +1

#5046 Fix link icon
  scss/_base_icon-definitions.scss
Labels: Review: QA +1, Review: Code +1, Bug 🐛, Review: Percy +1

#5050 Fix typo in release notes
  releases.yml
Labels: Review: QA +1, Review: Code +1, Documentation 📝

#5052 Deprecate old theme variables and remove them from code and docs
  scss/_patterns_buttons.scss
  scss/_settings_themes.scss
  scss/standalone/dark.scss
  templates/docs/patterns/contextual-menu/index.md
  templates/docs/patterns/divider.md
  templates/docs/patterns/navigation/index.md
  templates/docs/patterns/tabs/index.md
  templates/docs/settings/color-settings.md
Labels: Review: Code +1, Maintenance 🔨, Review: Percy +1

#5039 Add equal height row component
  releases.yml
  scss/_patterns_equal-height-row.scss
  scss/_patterns_media-container.scss
  scss/_vanilla.scss
  scss/standalone/patterns_equal-height-row.scss
  side-navigation.yaml
  templates/docs/examples/patterns/equal-height-row/3-column-row.html
  templates/docs/examples/patterns/equal-height-row/4-items-per-column.html
  templates/docs/examples/patterns/equal-height-row/default.html
  templates/docs/patterns/equal-height-row.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Feature 🎁

#5055 Fix typography docs
  templates/docs/base/typography.md
Labels: Review: Design +1, Review: Code +1, Documentation 📝

#5057 Update divided list to use new theme colours
  scss/_patterns_lists.scss
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5056 fix border color discrepancy between themes
  scss/_settings_colors.scss
Labels: Review: Code +1, Bug 🐛

#5058 Add theme support for active pagination button
  scss/_patterns_pagination.scss
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#5061 Add space to grid docs
  templates/docs/patterns/grid/index.md
Labels: Review: Code +1, Documentation 📝

#5064 Update rule component to use new theme variables
  scss/_patterns_rule.scss
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#4957 Adjust p-nudge to better align text to the baseline grid
  scss/_settings_spacing.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Maintenance 🔨, Review: Percy +1
