Repository canonical/vanilla-framework, pull requests merged in 2024-08, with the labels that each got.

#5259 Indent code snippets using `js-beautify`
  .gitignore
  package.json
  templates/_layouts/docs.html
  templates/static/js/example.js
  yarn.lock
Labels: Review: QA +1, Review: Code +1, Documentation 📝, Review: Percy +1

#5251 Simplify Percy Breakpoint/Theme snapshots
  snapshots.js
  tests/snapshots.test.js
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5258 Fix tagged navigation icon spacing
  scss/_patterns_navigation.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5291 Percy tokens prep
  .github/workflows/percy-prepare.yml
  .github/workflows/pr-percy-prepare-push.yml
  .github/workflows/pr-percy-snapshots.yml
  Dockerfile
  package.json
  sd.config.json
  tokens/README.md
  yarn.lock
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5285 Fix responsive grid example not rendering correctly in combined view
  templates/docs/examples/patterns/grid/responsive.html
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#5302 bug: Don't close navigation on vertical resize
  templates/docs/examples/patterns/navigation/_script-sliding.js
Labels: Review: QA +1, Review: Code +1, Bug 🐛, Review: Percy +1

#5214 Add form legend required symbol
  releases.yml
  scss/_base_forms.scss
  templates/docs/base/forms.md
  templates/docs/examples/patterns/forms/combined.html
  templates/docs/examples/patterns/forms/fieldset-required.html
Labels: Review: QA +1, Review: Code +1, Feature 🎁, Review: A11y +1, Review: Percy +1

#5310 Add advl to team members list
  webapp/app.py
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5305 Improve Percy workflow docs
  .github/actions/percy-snapshot/action.yml
  .github/workflows/percy-baseline.yml
  .github/workflows/percy-prepare.yml
  .github/workflows/pr-percy-snapshots.yml
  guides/percy-workflow.md
  guides/pull-requests.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝, Review: Percy +1

#5309 Add button to close example toolbar
  scss/docs/example.scss
  templates/static/js/example-tools.js
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5308 Responsive image aspect ratio variants
  releases.yml
  scss/_patterns_image.scss
  scss/_settings_breakpoints.scss
  templates/docs/examples/patterns/image/container/aspect-ratio/all.html
  templates/docs/examples/patterns/image/container/aspect-ratio/responsive-all.html
  templates/docs/examples/patterns/image/container/aspect-ratio/responsive.html
  templates/docs/patterns/images.md
  tests/snapshots.test.js
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Feature 🎁

#5327 Improve combined example baseline alignment
  templates/_layouts/examples.html
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨, Review: Percy +1
