Repository canonical/vanilla-framework, pull requests merged in 2024-12, with the labels that each got.

#5415 Fix typo in breakpoint class name used in documentation
  templates/docs/layouts/fluid-breakout.md
  templates/docs/layouts/full-width.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝

#5422 Corrected documentation for importing quote macro
  templates/docs/patterns/quote-wrapper/index.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝, Review: Percy +1

#5424 fix: make quote wrapper quote separator always use `.p-rule--muted`
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
  templates/_macros/vf_quote-wrapper.jinja
  templates/docs/patterns/quote-wrapper/index.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Bug 🐛, Review: Percy +1

#5428 fix: Update link to accessibility report tool
  templates/accessibility.html
Labels: Review: QA +1, Review: Code +1, Documentation 📝, Review: Percy +1

#5427 fix: quote wrapper's `title_text` is now a semantic `h2`.
  package.json
  templates/_macros/vf_quote-wrapper.jinja
Labels: Review: QA needed, Review: Code +1, Bug 🐛, Review: Percy +1

#5425 Ft: add content guidelines page
  side-navigation.yaml
  templates/docs/content-guidelines.md
  templates/docs/customising-vanilla.md
Labels: Review: QA +1, Review: Code +1, Feature 🎁, Review: Percy +1

#5429 docs: Update tiered list jinja template docs to use semantic structure
  templates/docs/examples/patterns/tiered-list/50-50-desktop-with-description-cta.html
  templates/docs/examples/patterns/tiered-list/50-50-desktop-with-description.html
  templates/docs/examples/patterns/tiered-list/50-50-desktop-with-list-item-cta.html
  templates/docs/examples/patterns/tiered-list/50-50-tablet-with-description.html
  templates/docs/examples/patterns/tiered-list/50-50-tablet-without-description.html
  templates/docs/examples/patterns/tiered-list/50-50-with-description.html
  templates/docs/examples/patterns/tiered-list/full-width-with-description.html
  templates/docs/examples/patterns/tiered-list/full-width-without-description.html
  templates/docs/patterns/tiered-list/index.md
Labels: Review: QA +1, Review: Code +1

#5436 chore: silence import and global builtin deprecation warnings in sass build
  package.json
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨, Review: Percy needed
