Repository canonical/vanilla-framework, pull requests merged in 2024-07, with the labels that each got.

#5202 Percy Error Logging Improvement
  .github/actions/percy-snapshot/action.yml
  snapshots.js
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#5207 Add `is-cover` to image container class reference
  scss/_patterns_image.scss
Labels: Review: QA +1, Review: Code +1, Documentation 📝

#5210 Move search into the reduced navigation
  scss/_patterns_navigation-reduced.scss
  scss/_patterns_navigation.scss
  templates/docs/examples/patterns/navigation/_script-sliding.js
  templates/docs/examples/patterns/navigation/reduced.html
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#5215 Align logo in reduced nav with the grid
  scss/_patterns_navigation-reduced.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Bug 🐛

#5222 Correct labels on grid examples
  templates/docs/examples/patterns/grid/empty-columns.html
  templates/docs/examples/patterns/grid/incorrect-empty-columns.html
  templates/docs/examples/patterns/grid/nested-medium.html
  templates/docs/examples/patterns/grid/nested-small.html
  templates/docs/examples/patterns/grid/nested.html
  templates/docs/examples/patterns/grid/offsets.html
  templates/docs/examples/patterns/grid/responsive.html
Labels: Review: QA +1, Review: Code +1, Bug 🐛, Review: Percy +1

#5220 Fix Intermittent Percy Snapshot Timeouts
  .github/actions/percy-snapshot/action.yml
Labels: Review: QA needed, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5225 Fix typo in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Review: Code needed, Maintenance 🔨, Review: Percy needed

#5224 Sync Github Issues to Jira Issues
  .github/.jira_sync_config.yaml
Labels: Review: Code +1, Maintenance 🔨, Review: Percy needed

#5196 CTA Block component
  package.json
  releases.yml
  scss/_patterns_cta.scss
  scss/_vanilla.scss
  scss/standalone/patterns_cta.scss
  side-navigation.yaml
  templates/docs/examples/patterns/cta-block/default.html
  templates/docs/patterns/cta-block/index.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Feature 🎁, Review: Percy +1

#5232 Fix duplicated suru fan examples
  templates/docs/patterns/suru.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝, Review: Percy +1

#5233 Remove bots from the contributors list
  webapp/app.py
Labels: Review: QA +1, Review: Code +1, Documentation 📝, Review: Percy +1

#5235 75/25% Grid Row (`.row--75-25`)
  redirects.yaml
  releases.yml
  scss/_patterns_grid.scss
  templates/docs/examples/patterns/grid/25-75-responsive-large.html
  templates/docs/examples/patterns/grid/25-75-responsive-medium.html
  templates/docs/examples/patterns/grid/75-25-mixed-responsive.html
  templates/docs/examples/patterns/grid/75-25-responsive-large.html
  templates/docs/examples/patterns/grid/75-25-responsive-medium.html
  templates/docs/examples/patterns/grid/75-25.html
  templates/docs/examples/patterns/grid/combined.html
  templates/docs/patterns/grid/index.md
Labels: Review: QA +1, Review: Code +1, Feature 🎁, Review: Percy +1

#5237 Change strips image example background to decrease load time
  templates/docs/examples/patterns/strips/image.html
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5250 Add `templates/_macros` to percy tests
  .github/workflows/percy-prepare.yml
  .github/workflows/pr-percy-prepare-push.yml
  .github/workflows/pr-percy-snapshots.yml
  guides/pull-requests.md
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5257 Percy macros artifact fix
  .github/workflows/pr-percy-snapshots.yml
Labels: Review: QA needed, Review: Code needed

#5249 Remove percy_upload status check
  .github/workflows/pr-percy-snapshots.yml
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5247 Remove excess whitespace in class reference table
  templates/_layouts/_class-reference.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Documentation 📝, Review: Percy +1

#5263 Fixes #5228 duplicate css
  scss/_base_placeholders.scss
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5265 Remove deprecated -webkit-search-cancel-button pseudo-element styles
  scss/_base_forms.scss
Labels: Review: QA +1, Review: Code +1, Bug 🐛, Review: Percy +1

#5246 Update styling of reduced nav on small screens
  scss/_patterns_navigation-reduced.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Maintenance 🔨
