Repository canonical/vanilla-framework, pull requests merged in 2024-06, with the labels that each got.

#5093 Add left & right chevron icon variants
  releases.yml
  scss/_patterns_icons.scss
  templates/docs/examples/patterns/icons/icons-dark-deprecated.html
  templates/docs/examples/patterns/icons/icons-dark.html
  templates/docs/examples/patterns/icons/icons-light.html
  templates/docs/patterns/icons/index.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Feature 🎁, Review: Percy +1

#5099 Fix stepped list content/item padding
  scss/_patterns_lists.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Bug 🐛, Review: Percy +1

#5106 Update modal component to support new theming variables
  scss/_patterns_modal.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5111 Update segmented control to use new color theme variables
  scss/_patterns_segmented-control.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Maintenance 🔨

#5100 Fix misleading icon import documentation
  templates/docs/patterns/icons/index.md
Labels: Review: QA +1, Review: Code +1, Bug 🐛

#5112 Update card pattern to support color themes
  scss/_base_placeholders.scss
  scss/_patterns_card.scss
  scss/_settings_placeholders.scss
  templates/docs/examples/patterns/card/header.html
  templates/docs/examples/patterns/card/overlay.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5124 Update lists pattern to use new color theme variables
  scss/_patterns_lists.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5126 Update article pagination to use new theme variables
  scss/_patterns_article-pagination.scss
  templates/docs/examples/patterns/article-pagination.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5132 Notify Figma library maintainers on release
  .github/workflows/publish-on-release.yml
Labels: Review: Code needed, Maintenance 🔨

#5138 Update accordion pattern to use new color theme variables
  scss/_patterns_accordion.scss
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5097 Add new image container component and deprecate legacy image variants
  package.json
  releases.yml
  scss/_patterns_image.scss
  templates/docs/examples/patterns/image/container/aspect-ratio/16-9.html
  templates/docs/examples/patterns/image/container/aspect-ratio/all.html
  templates/docs/examples/patterns/image/container/highlighted.html
  templates/docs/patterns/images.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Feature 🎁, Review: Percy +1

#5142 Percy examples combination preparation (jinja/python enablement code)
  templates/_layouts/examples.html
  webapp/app.py
Labels: Review: Code needed

#5168 Fix figma library alert
  .github/workflows/publish-on-release.yml
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨

#5144 Percy examples combination - `base/forms`
  templates/_layouts/examples.html
  templates/docs/examples/base/forms/combined.html
Labels: Review: QA +1, Review: Code +1

#5146 Percy examples combination - `base/hr`
  redirects.yaml
  templates/docs/base/separators.md
  templates/docs/examples/base/hr-dark.html
  templates/docs/examples/base/hr/combined.html
  templates/docs/examples/base/hr/default.html
  templates/docs/examples/base/hr/fixed-width.html
  templates/docs/examples/base/hr/muted.html
Labels: Review: QA +1, Review: Code +1

#5145 Percy examples combination - `base/headings`
  redirects.yaml
  templates/docs/base/typography.md
  templates/docs/examples/base/headings/accented.html
  templates/docs/examples/base/headings/combined.html
  templates/docs/examples/base/headings/default.html
  templates/docs/examples/base/headings/sub-headings.html
Labels: Review: QA needed, Review: Code +1

#5148 Percy examples combination - `base/paper`
  templates/docs/examples/base/paper/combined.html
  templates/docs/examples/base/paper/input-on-paper.html
  templates/docs/examples/base/paper/search-box-on-paper.html
Labels: Review: QA +1, Review: Code +1

#5149 Percy examples combination - `base/table`
  redirects.yaml
  templates/docs/base/tables.md
  templates/docs/examples/base/table/combined.html
  templates/docs/examples/base/table/default.html
  templates/docs/examples/base/table/empty.html
Labels: Review: QA +1, Review: Code +1

#5150 Percy examples combination - `base/typography`
  redirects.yaml
  templates/docs/base/code.md
  templates/docs/base/typography.md
  templates/docs/examples/base/typography/abbr.html
  templates/docs/examples/base/typography/blockquotes.html
  templates/docs/examples/base/typography/combined.html
  templates/docs/examples/base/typography/details.html
  templates/docs/examples/base/typography/font-weights.html
  templates/docs/examples/base/typography/links.html
  templates/docs/examples/base/typography/pre.html
  templates/docs/examples/base/typography/small.html
  templates/docs/examples/base/typography/strong.html
  templates/docs/examples/base/typography/sub.html
  templates/docs/examples/base/typography/sup.html
  templates/docs/examples/base/typography/variable-font.html
  templates/docs/patterns/links/index.md
Labels: Review: QA +1, Review: Code +1

#5152 Percy examples combination - `patterns/` simple combinations
  templates/docs/examples/patterns/accordion/combined.html
  templates/docs/examples/patterns/badge/combined.html
  templates/docs/examples/patterns/card/combined.html
  templates/docs/examples/patterns/empty-state/combined.html
  templates/docs/examples/patterns/equal-height-row/combined.html
  templates/docs/examples/patterns/grid/combined.html
  templates/docs/examples/patterns/heading-icon/combined.html
  templates/docs/examples/patterns/headings/combined.html
  templates/docs/examples/patterns/hero/combined.html
  templates/docs/examples/patterns/image/combined.html
  templates/docs/examples/patterns/image/container/aspect-ratio/all.html
  templates/docs/examples/patterns/media-object/combined.html
  templates/docs/examples/patterns/pagination/combined.html
  templates/docs/examples/patterns/pull-quotes/combined.html
  templates/docs/examples/patterns/section/combined.html
  templates/docs/examples/patterns/segmented-control/combined.html
  templates/docs/examples/patterns/strips/combined.html
  templates/docs/examples/patterns/tab-buttons/combined.html
  templates/docs/examples/patterns/table-of-contents/combined.html
  templates/docs/examples/patterns/tooltips/combined.html
Labels: Review: QA +1, Review: Code +1

#5154 Percy examples combination - `patterns/chip`
  redirects.yaml
  templates/docs/examples/patterns/chip/combined.html
  templates/docs/examples/patterns/chip/dark.html
  templates/docs/patterns/chip/index.md
Labels: Review: QA +1, Review: Code +1

#5155 Percy examples combination - `patterns/code-snippet`
  redirects.yaml
  templates/docs/examples/patterns/code-snippet/combined.html
  templates/docs/examples/patterns/code-snippet/default-dark.html
  templates/docs/examples/patterns/code-snippet/dropdown-multiple-dark.html
  templates/docs/examples/patterns/code-snippet/icon-dark.html
Labels: Review: QA +1, Review: Code +1

#5156 Percy examples combination - `patterns/contextual-menu`
  redirects.yaml
  templates/docs/examples/patterns/contextual-menu/combined.html
  templates/docs/examples/patterns/contextual-menu/dark.html
  templates/docs/patterns/contextual-menu/index.md
Labels: Review: QA +1, Review: Code +1, Blocked ⛔

#5158 Percy example combinations - `patterns/divider`
  redirects.yaml
  templates/docs/examples/patterns/divider/combined.html
  templates/docs/examples/patterns/divider/dark.html
  templates/docs/patterns/divider.md
Labels: Review: QA +1, Review: Code +1

#5161 Percy examples combination - `patterns/icons`
  redirects.yaml
  templates/docs/examples/patterns/icons/combined.html
  templates/docs/examples/patterns/icons/icons-dark.html
  templates/docs/examples/patterns/icons/standard.html
  templates/docs/patterns/icons/index.md
Labels: Review: QA +1, Review: Code +1

#5166 Percy examples combination - `patterns/notifications`
  redirects.yaml
  templates/docs/examples/patterns/notifications/combined.html
  templates/docs/examples/patterns/notifications/notifications-dark.html
  templates/docs/examples/patterns/notifications/variants-dark.html
Labels: Review: QA +1, Review: Code +1

#5167 Percy examples combination - `patterns/rule`
  redirects.yaml
  templates/docs/examples/patterns/rule/combined.html
  templates/docs/examples/patterns/rule/dark.html
  templates/docs/patterns/rule.md
Labels: Review: QA +1, Review: Code +1

#5169 Percy examples combination - `patterns/search-box`
  redirects.yaml
  templates/docs/examples/patterns/search-box/default-dark.html
Labels: Review: QA +1, Review: Code +1

#5173 Percy examples combination - `patterns/tabs`
  redirects.yaml
  templates/docs/examples/patterns/tabs/combined.html
  templates/docs/examples/patterns/tabs/content-dark.html
  templates/docs/patterns/tabs/index.md
Labels: Review: QA +1, Review: Code +1

#5164 Percy examples combination - `patterns/logo-section`
  redirects.yaml
  templates/docs/examples/patterns/logo-section/combined.html
  templates/docs/examples/patterns/logo-section/default.html
  templates/docs/examples/patterns/logo-section/logo-section-dark.html
  templates/docs/patterns/logo-section/index.md
Labels: Review: QA +1, Review: Code +1

#5160 Percy examples combination - `patterns/forms`
  redirects.yaml
  scss/standalone/patterns_forms.scss
  templates/docs/base/forms.md
  templates/docs/examples/patterns/forms/checkbox-heading.html
  templates/docs/examples/patterns/forms/checkbox-indeterminate.html
  templates/docs/examples/patterns/forms/checkbox-inline.html
  templates/docs/examples/patterns/forms/checkbox-validation.html
  templates/docs/examples/patterns/forms/checkbox.html
  templates/docs/examples/patterns/forms/combined.html
  templates/docs/examples/patterns/forms/default.html
  templates/docs/examples/patterns/forms/form-validation-dark.html
  templates/docs/examples/patterns/forms/password-toggle.html
  templates/docs/examples/patterns/forms/radio-heading.html
  templates/docs/examples/patterns/forms/radio-inline.html
  templates/docs/examples/patterns/forms/radio-validation.html
  templates/docs/examples/patterns/forms/radio.html
  templates/docs/examples/patterns/forms/tick-variants.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#5171 Percy examples combination - `patterns/suru`
  redirects.yaml
  templates/docs/examples/patterns/suru/50-50-dark.html
  templates/docs/examples/patterns/suru/combined.html
  templates/docs/examples/patterns/suru/dark.html
  templates/docs/examples/patterns/suru/variants.html
Labels: Review: QA +1, Review: Code +1

#5172 Percy examples combination - `patterns/tables`
  redirects.yaml
  scss/standalone/patterns_table-expanding.scss
  scss/standalone/patterns_table-mobile-card.scss
  scss/standalone/patterns_table-overflow.scss
  scss/standalone/patterns_table.scss
  templates/docs/examples/patterns/tables/combined.html
  templates/docs/examples/patterns/tables/table-expanding.html
  templates/docs/examples/patterns/tables/table-formatting.html
  templates/docs/examples/patterns/tables/table-mobile-card-dark.html
  templates/docs/examples/patterns/tables/table-mobile-card.html
  templates/docs/examples/patterns/tables/table-overflow.html
  templates/docs/examples/patterns/tables/table-sortable-dark.html
  templates/docs/examples/patterns/tables/table-sortable.html
Labels: Review: QA +1, Review: Code +1

#5162 Percy examples combination - `patterns/links`
  redirects.yaml
  scss/standalone/patterns_links.scss
  templates/docs/examples/patterns/links/combined.html
  templates/docs/examples/patterns/links/default.html
  templates/docs/examples/patterns/links/links-inverted.html
  templates/docs/patterns/links/index.md
Labels: Review: QA +1, Review: Code +1

#5163 Percy examples combination - `patterns/lists`
  redirects.yaml
  scss/standalone/patterns_lists.scss
  templates/docs/examples/patterns/lists/combined.html
  templates/docs/examples/patterns/lists/lists-mid-dot-dark.html
  templates/docs/examples/patterns/lists/lists-stepped-dark.html
  templates/docs/patterns/lists/index.md
Labels: Review: QA +1, Review: Code needed

#5177 Percy example combinations - `patterns/search-and-filter`
  templates/docs/examples/patterns/search-and-filter/_search-prompt-script.js
  templates/docs/examples/patterns/search-and-filter/combined.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#5188 fix Percy workflows not running correctly in multi-label case
  .github/workflows/pr-percy-prepare-label.yml
  .github/workflows/pr-percy-prepare-push.yml
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5179 Fix aspect ratio in image container component on smaller screens
  scss/_patterns_image.scss
  templates/docs/examples/patterns/image/container/aspect-ratio/all.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Bug 🐛, Review: Percy +1

#5184 fix percy snapshots widths test failing for responsive combined examples
  tests/snapshots.test.js
Labels: Review: QA +1, Review: Code needed

#5165 Percy examples combination - `patterns/navigation`
  redirects.yaml
  templates/_layouts/examples.html
  templates/docs/examples/patterns/navigation/combined.html
  templates/docs/examples/patterns/navigation/deprecated-logo.html
  templates/docs/examples/patterns/navigation/dropdown-alignment.html
  templates/docs/examples/patterns/navigation/dropdown-dark.html
  templates/docs/examples/patterns/navigation/dropdown.html
  templates/docs/examples/patterns/navigation/search-dark.html
  templates/docs/examples/patterns/navigation/search.html
  templates/docs/examples/patterns/navigation/sliding-dark.html
  templates/docs/examples/patterns/navigation/sliding-search.html
  templates/docs/examples/patterns/navigation/sliding.html
  templates/docs/patterns/search-box/index.md
Labels: Review: QA +1, Review: Code +1

#5170 Percy examples combination - `patterns/side-navigation`
  redirects.yaml
  templates/docs/examples/patterns/side-navigation/_layout-JAAS.html
  templates/docs/examples/patterns/side-navigation/accordion-dark.html
  templates/docs/examples/patterns/side-navigation/accordion.html
  templates/docs/examples/patterns/side-navigation/combined.html
  templates/docs/examples/patterns/side-navigation/dark.html
  templates/docs/examples/patterns/side-navigation/default.html
  templates/docs/examples/patterns/side-navigation/docs.html
  templates/docs/examples/patterns/side-navigation/expandable-dark.html
  templates/docs/examples/patterns/side-navigation/expandable.html
  templates/docs/examples/patterns/side-navigation/icons.html
  templates/docs/examples/patterns/side-navigation/paper.html
  templates/docs/examples/patterns/side-navigation/raw-html.html
  templates/docs/examples/patterns/side-navigation/sticky.html
  templates/docs/patterns/navigation/index.md
Labels: Review: QA +1, Review: Code +1

#5191 Fix Percy tests being queued against PRs with Percy label when the ne…
  .github/workflows/pr-percy-prepare-label.yml
Labels: Review: QA +1, Review: Code +1, Priority: High, Maintenance 🔨

#5183 Fix favicon not rendering properly in google search.
  templates/_layouts/_root.html
  templates/static/images/favicons/vanilla_favicon_48px.png
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Documentation 📝

#5193 Fix standalone logo section scss
  scss/standalone/patterns_logo-section.scss
Labels: Review: QA +1, Review: Code +1

#5198 Update alt background in paper theme
  scss/_settings_colors.scss
Labels: Review: QA needed, Review: Design +1, Review: Code needed, Bug 🐛, Review: Percy +1

#5199 Add cover option to image container component
  releases.yml
  scss/_patterns_image.scss
  templates/docs/examples/patterns/image/combined.html
  templates/docs/examples/patterns/image/container/cover.html
  templates/docs/patterns/images.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Feature 🎁
