Repository canonical/vanilla-framework, pull requests merged in 2024-03, with the labels that each got.

#5013 Add validation example
  scss/standalone/patterns_form-tick-elements.scss
  templates/docs/examples/patterns/forms/checkbox-validation.html
  templates/docs/examples/patterns/forms/radio-validation.html
Labels: Review: QA +1, Review: Code +1, Documentation 📝

#5018 Fixed typo in GH issue template (out site -> our site)
  .github/ISSUE_TEMPLATE/report-a-bug.md
Labels: Review: Code +1, Maintenance 🔨

#5020 Update link to Accessibility Alphabet
  templates/accessibility.html
Labels: Review: QA +1, Review: Code +1, Documentation 📝

#5022 Theme switch in examples
  scss/_utilities_baseline-grid.scss
  scss/_utilities_theme-toggle.scss
  scss/_vanilla.scss
  scss/docs/example.scss
  templates/_layouts/examples.html
  templates/docs/examples/base/code-inline-dark.html
  templates/docs/examples/base/hr-dark.html
  templates/docs/examples/patterns/article-pagination.html
  templates/docs/examples/patterns/card/overlay.html
  templates/docs/examples/patterns/divider/dark.html
  templates/docs/examples/patterns/lists/lists-stepped-dark.html
  templates/docs/examples/patterns/logo-section/logo-section-dark.html
  templates/docs/examples/patterns/pagination/pagination-deprecated.html
  templates/docs/examples/patterns/rule/dark.html
  templates/docs/examples/patterns/search-and-filter/chip-overflow.html
  templates/docs/examples/patterns/search-and-filter/default.html
  templates/docs/examples/patterns/search-and-filter/expanded.html
  templates/docs/examples/patterns/search-and-filter/with-chips.html
  templates/docs/examples/patterns/search-and-filter/with-search-prompt.html
  templates/docs/examples/patterns/strips/dark.html
  templates/static/js/example-tools.js
Labels: Review: QA +1, Review: Code +1, Documentation 📝, Review: Percy +1

#5028 Fix regression that caused wrong success icon being used in lists
  scss/_base_icon-definitions.scss
  scss/_patterns_lists.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Bug 🐛, Review: Percy +1

#5029 Move active/hover button opacity variables to settings
  package.json
  scss/_patterns_buttons.scss
  scss/_settings_colors.scss
Labels: Review: Code +1, Maintenance 🔨

#5027 Revert default info icon to standard colour
  scss/_base_icon-definitions.scss
  scss/_patterns_notifications.scss
Labels: Review: QA +1, Review: Code +1, Bug 🐛, Review: Percy +1
