Repository canonical/vanilla-framework, pull requests merged in 2024-10, with the labels that each got.

#5340 Manually set baseline build commit signature
  .github/actions/percy-snapshot/action.yml
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5342 feat: Publish & Document Jinja Macros
  package.json
  releases.yml
  templates/_macros/vf_hero.jinja
  templates/_macros/vf_tiered-list.jinja
  templates/docs/building-vanilla.md
  templates/docs/examples/patterns/hero/hero-50-50-full-width-image.html
  templates/docs/examples/patterns/hero/hero-50-50-split-on-medium.html
  templates/docs/examples/patterns/hero/hero-50-50.html
  templates/docs/examples/patterns/hero/hero-75-25.html
  templates/docs/examples/patterns/hero/hero-fallback.html
  templates/docs/examples/patterns/hero/hero-signpost-full-width-image.html
  templates/docs/examples/patterns/hero/hero-signpost.html
  templates/docs/examples/patterns/tiered-list/50-50-desktop-with-description-cta.html
  templates/docs/examples/patterns/tiered-list/50-50-desktop-with-description.html
  templates/docs/examples/patterns/tiered-list/50-50-desktop-with-list-item-cta.html
  templates/docs/examples/patterns/tiered-list/50-50-tablet-with-description.html
  templates/docs/examples/patterns/tiered-list/50-50-tablet-without-description.html
  templates/docs/examples/patterns/tiered-list/50-50-with-description.html
  templates/docs/examples/patterns/tiered-list/full-width-with-description.html
  templates/docs/examples/patterns/tiered-list/full-width-without-description.html
  templates/docs/patterns/hero/index.md
  templates/docs/patterns/tiered-list/index.md
  templates/static/js/example.js
  templates/static/js/scripts.js
  webapp/app.py
Labels: Review: QA +1, Review: Code +1, Priority: High, Feature 🎁, Review: Percy +1

#5370 Remove SASS warnings by using color.scale and color.channel functions
  scss/_global_functions.scss
  scss/_patterns_image.scss
  scss/_patterns_strip.scss
  scss/_patterns_switch.scss
  scss/_settings_colors.scss
  scss/_settings_placeholders.scss
  scss/_utilities_baseline-grid.scss
  scss/_utilities_font-metrics.scss
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5373 Update contributors list
  webapp/app.py
Labels: Review: QA needed, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5376 Add content guidance for tables
  templates/docs/base/tables.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝

#5371 fix(skip-link): give the skip link a more modern styling
  scss/_patterns_links.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Maintenance 🔨

#5379 Add `sass` as a peer dependency
  package.json
Labels: Review: Code +1, Maintenance 🔨, dependencies, Review: Percy +1

#5380 Change links for react components
  templates/docs/base/code.md
  templates/docs/base/forms.md
  templates/docs/base/tables.md
  templates/docs/patterns/accordion/index.md
  templates/docs/patterns/buttons/index.md
  templates/docs/patterns/card/index.md
  templates/docs/patterns/chip/index.md
  templates/docs/patterns/contextual-menu/index.md
  templates/docs/patterns/grid/index.md
  templates/docs/patterns/links/index.md
  templates/docs/patterns/lists/index.md
  templates/docs/patterns/modal/index.md
  templates/docs/patterns/notification/index.md
  templates/docs/patterns/pagination/index.md
  templates/docs/patterns/search-and-filter.md
  templates/docs/patterns/search-box/index.md
  templates/docs/patterns/slider/index.md
  templates/docs/patterns/strip/index.md
  templates/docs/patterns/tabs/index.md
  templates/docs/patterns/tooltips/index.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝, Review: Percy +1

#5383 Change the JIRA epic where new issues are synchronised
  .github/.jira_sync_config.yaml
Labels: Review: Code needed

#5381 Add links to react storybook for existing components
  templates/docs/base/forms.md
  templates/docs/patterns/badge/index.md
  templates/docs/patterns/navigation/index.md
  templates/docs/patterns/status-labels/index.md
  templates/docs/patterns/switch/index.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝

#5378 Add basic themes documentation
  redirects.yaml
  side-navigation.yaml
  templates/docs/base/paper.md
  templates/docs/base/themes.md
  templates/docs/settings/color-settings.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝, Review: Percy +1

#5377 Update remaining legacy components to use new theme colours.
  scss/_layouts_full-width.scss
  scss/_patterns_badge.scss
  scss/_patterns_image.scss
Labels: Review: QA +1, Review: Design +1, Maintenance 🔨, Review: Code +1 (with changes), Review: Percy +1

#5385 Update icon SVGs to use simplified paths and fix artifacts
  scss/_base_icon-definitions.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5387 Fix icon margin within small buttons
  scss/_base_button.scss
  templates/docs/examples/patterns/buttons/icon.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Bug 🐛

#5314 Set icon alignment in paragraph to text-bottom
  scss/_patterns_icons.scss
Labels: Review: QA +1, Review: Design +1, Maintenance 🔨, Review: Code +1 (with changes), Review: Percy +1

#5395 Add CSS range syntax to breakpoints settings page
  templates/docs/settings/breakpoint-settings.md
Labels: Review: QA +1, Review: Code +1, Documentation 📝, Review: Percy +1

#5392 Fix slider margin
  scss/_base_forms-range.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Bug 🐛, Review: Percy +1

#5275 feat: Quote Wrapper Pattern
  releases.yml
  side-navigation.yaml
  templates/_macros/vf_quote-wrapper.jinja
  templates/docs/examples/patterns/quote-wrapper/combined.html
  templates/docs/examples/patterns/quote-wrapper/large-minimal.html
  templates/docs/examples/patterns/quote-wrapper/large-no-citation.html
  templates/docs/examples/patterns/quote-wrapper/large-no-cta-image-or-citation.html
  templates/docs/examples/patterns/quote-wrapper/large-no-cta-image.html
  templates/docs/examples/patterns/quote-wrapper/large-no-header-no-signpost.html
  templates/docs/examples/patterns/quote-wrapper/large-no-header.html
  templates/docs/examples/patterns/quote-wrapper/large-no-signpost.html
  templates/docs/examples/patterns/quote-wrapper/large-shallow.html
  templates/docs/examples/patterns/quote-wrapper/large.html
  templates/docs/examples/patterns/quote-wrapper/medium-no-citation.html
  templates/docs/examples/patterns/quote-wrapper/medium-no-header.html
  templates/docs/examples/patterns/quote-wrapper/medium-no-signpost.html
  templates/docs/examples/patterns/quote-wrapper/medium.html
  templates/docs/examples/patterns/quote-wrapper/small-no-citation.html
  templates/docs/examples/patterns/quote-wrapper/small-no-header.html
  templates/docs/examples/patterns/quote-wrapper/small-no-signpost.html
  templates/docs/examples/patterns/quote-wrapper/small.html
  templates/docs/macros/notice.jinja
  templates/docs/macros/patterns/wip-notice.jinja
  templates/docs/patterns/hero/index.md
  templates/docs/patterns/quote-wrapper/index.md
  templates/docs/patterns/tiered-list/index.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Priority: High, Feature 🎁, Review: Percy +1

#5389 Fix input padding alignment
  scss/_base_forms.scss
  scss/_patterns_search-box.scss
  scss/_settings_placeholders.scss
  scss/_settings_spacing.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Bug 🐛, Review: Percy +1

#5339 fix: Search and filter hidden search button alignment and stacking order adjustment
  scss/_base_placeholders.scss
  scss/_patterns_search-and-filter.scss
  scss/_utilities_off-screen.scss
  templates/docs/examples/patterns/search-and-filter/chip-overflow.html
  templates/docs/examples/patterns/search-and-filter/default.html
  templates/docs/examples/patterns/search-and-filter/expanded.html
  templates/docs/examples/patterns/search-and-filter/with-chips.html
  templates/docs/examples/patterns/search-and-filter/with-search-prompt.html
  tests/parker.js
Labels: Review: QA +1, Review: Code +1, Bug 🐛, Review: A11y +1, Review: Percy +1

#5306 Feat: Rich vertical list pattern
  releases.yml
  side-navigation.yaml
  templates/_macros/vf_rich-vertical-list.jinja
  templates/docs/examples/patterns/rich-list-vertical/bulleted-flipped.html
  templates/docs/examples/patterns/rich-list-vertical/bulleted.html
  templates/docs/examples/patterns/rich-list-vertical/bulletless-flipped.html
  templates/docs/examples/patterns/rich-list-vertical/bulletless.html
  templates/docs/examples/patterns/rich-list-vertical/combined.html
  templates/docs/examples/patterns/rich-list-vertical/minimal.html
  templates/docs/examples/patterns/rich-list-vertical/ordered-flipped.html
  templates/docs/examples/patterns/rich-list-vertical/ordered.html
  templates/docs/examples/patterns/rich-list-vertical/ticked-flipped.html
  templates/docs/examples/patterns/rich-list-vertical/ticked.html
  templates/docs/patterns/rich-list-vertical/index.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Priority: High, Feature 🎁, Review: Percy +1

#5400 Update layout of the homepage "downloads" section on medium screens
  templates/index.html
Labels: Review: QA +1, Review: Code +1, Maintenance 🔨, Review: Percy +1

#5399 Adjust search and filter component height to align with standard inputs
  scss/_patterns_search-and-filter.scss
Labels: Review: QA +1, Review: Code +1, Bug 🐛, Review: Percy +1

#5403 Fix using the image container with lazyloaded images
  package.json
  scss/_patterns_image.scss
Labels: Review: QA +1, Review: Code +1, Bug 🐛, Review: Percy +1
