Repository canonical/vanilla-framework, pull requests merged in 2025-08, with the labels that each got.

#5602 feat: added support for highlighting images in equal-heights macro
  package.json
  releases.yml
  templates/_macros/vf_equal-heights.jinja
  templates/docs/examples/patterns/equal-heights/4-columns-highlighted-images.html
  templates/docs/examples/patterns/equal-heights/combined.html
  templates/docs/patterns/equal-heights/index.md
Labels: Review: QA +1, Feature 🎁, Review: Code +1 (with changes), Review: Percy +1

#5608 fix: correct image container class selector to use * instead of ^
  scss/_patterns_image.scss
Labels: Review: QA +1, Review: Code +1, Priority: Critical, Bug 🐛, Review: Percy +1

#5607 [WD-24276] feat: implemented Single Pricing Block pattern variant
  package.json
  releases.yml
  templates/_macros/vf_pricing-block.jinja
  templates/docs/examples/patterns/pricing-block/1-block.html
  templates/docs/examples/patterns/pricing-block/block-with-description-and-highlighted-rule.html
  templates/docs/examples/patterns/pricing-block/block-without-description-and-muted-rule.html
  templates/docs/examples/patterns/pricing-block/combined.html
  templates/docs/patterns/pricing-block/index.md
Labels: Review: QA +1, Review: Design +1, Question ❓, Review: Code +1, Feature 🎁, Review: Percy +1
