Repository canonical/vanilla-framework, pull requests merged in 2025-07, with the labels that each got.

#5569 fix(Badge): Truncate badges with long text, make the smallest badge a perfect circle
  package.json
  scss/_patterns_badge.scss
Labels: Review: Design needed, Review: QA +1, Review: Code +1, Bug 🐛, Review: Percy needed

#5529 feat(vf_tiered-list): Remove hr above first tiered list item across all varients
  releases.yml
  templates/_macros/vf_tiered-list.jinja
  templates/docs/examples/patterns/tiered-list/50-50-desktop-with-description-cta.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Feature 🎁

#5565 [WD-22558] feat: Implement CTA section pattern
  releases.yml
  side-navigation.yaml
  templates/_macros/vf_cta-section.jinja
  templates/docs/examples/patterns/cta-section/block-25-75.html
  templates/docs/examples/patterns/cta-section/block-full-width.html
  templates/docs/examples/patterns/cta-section/combined.html
  templates/docs/examples/patterns/cta-section/default-25-75-links-within-text.html
  templates/docs/examples/patterns/cta-section/default-25-75.html
  templates/docs/examples/patterns/cta-section/default-full-width-links-within-text.html
  templates/docs/examples/patterns/cta-section/default-full-width.html
  templates/docs/patterns/cta-section/index.md
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Feature 🎁, Review: Code +1 (with changes), Review: Percy +1

#5572 [WD-22567] feat: Implement Text Spotlight section pattern
  releases.yml
  side-navigation.yaml
  templates/_macros/vf_text-spotlight.jinja
  templates/docs/examples/patterns/text-spotlight/combined.html
  templates/docs/examples/patterns/text-spotlight/default.html
  templates/docs/examples/patterns/text-spotlight/links.html
  templates/docs/patterns/text-spotlight/index.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1, Feature 🎁, Review: Percy +1

#5578 Cleanup typography/spacing settings
  releases.yml
  scss/_base_button.scss
  scss/_base_code.scss
  scss/_base_details.scss
  scss/_base_forms.scss
  scss/_base_placeholders.scss
  scss/_base_tables.scss
  scss/_base_typography-definitions.scss
  scss/_base_typography.scss
  scss/_layouts_full-width.scss
  scss/_patterns_badge.scss
  scss/_patterns_chip.scss
  scss/_patterns_heading-icon.scss
  scss/_patterns_lists.scss
  scss/_patterns_matrix.scss
  scss/_patterns_navigation-reduced.scss
  scss/_patterns_navigation.scss
  scss/_patterns_notifications.scss
  scss/_patterns_search-and-filter.scss
  scss/_patterns_search-box.scss
  scss/_patterns_status-label.scss
  scss/_patterns_table-mobile-card.scss
  scss/_patterns_table-sortable.scss
  scss/_patterns_tabs.scss
  scss/_settings.scss
  scss/_settings_font.scss
  scss/_settings_spacing.scss
  scss/_utilities_content-align.scss
  templates/docs/settings/font-settings.md
  templates/docs/settings/spacing-settings.md
  tests/parker.js
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Maintenance 🔨, Review: Percy +1
