Repository canonical/vanilla-framework, pull requests merged in 2025-04, with the labels that each got.

#5495 #bartaz { visibility: hidden }
  webapp/app.py
Labels: Review: QA +1, Review: Code +1, Documentation 📝, Review: Percy needed

#5464 feat(linked logo section) - Build Linked Logo Section pattern
  releases.yml
  side-navigation.yaml
  templates/_macros/vf_linked-logo-section.jinja
  templates/docs/examples/patterns/linked-logo-section/25-75.html
  templates/docs/examples/patterns/linked-logo-section/50-50.html
  templates/docs/examples/patterns/linked-logo-section/combined.html
  templates/docs/examples/patterns/linked-logo-section/default.html
  templates/docs/patterns/linked-logo-section/index.md
Labels: Review: QA +1, Review: Design +1, Feature 🎁, Review: Code +1 (with changes), Review: Percy +1

#5506 fix(code) allow code line selection with triple click
  package.json
  scss/_base_code.scss
Labels: Review: QA +1, Review: Code +1, Bug 🐛, Review: Percy +1
