Repository canonical/vanilla-framework, pull requests merged in 2025-03, with the labels that each got.

#5478 Update release-process.md
  guides/release-process.md
Labels: Review: Code +1, Documentation 📝

#5473 Nested dropdowns no longer dismiss overlay
  templates/docs/examples/patterns/navigation/_script-sliding.js
Labels: Review: QA +1, Review: Code +1, Bug 🐛, Review: Percy +1

#5483 docs(layout settings): Update layout settings docs to reflect new grid variable
  templates/docs/settings/layout-settings.md
Labels: Review: QA needed, Review: Code needed, Documentation 📝, Review: Percy needed
