Repository canonical/vanilla-framework, pull requests merged in 2025-01, with the labels that each got.

#5442 Add credit card icon
  package.json
  releases.yml
  scss/_base_icon-definitions.scss
  scss/_patterns_icons.scss
  scss/standalone/patterns_icons-additional.scss
  templates/docs/examples/patterns/icons/icons-additional.html
  templates/docs/patterns/icons/index.md
Labels: Review: Design needed, Review: QA +1, Review: Code +1, Feature 🎁, Review: Percy +1

#5443 Full width image Hero - Remove margin bottom from H1 only if the subtitle_text is missing
  package.json
Labels: Review: Code +1, Bug 🐛

#5437 feat: Horizontal list section component
  package.json
  releases.yml
  scss/_patterns_lists.scss
  templates/docs/examples/patterns/lists/_list-horizontal-section-example.jinja
  templates/docs/examples/patterns/lists/combined.html
  templates/docs/examples/patterns/lists/lists-dividers-bulleted.html
  templates/docs/examples/patterns/lists/lists-horizontal-section-25-75-responsive-bulleted.html
  templates/docs/examples/patterns/lists/lists-horizontal-section-25-75-responsive-crossed.html
  templates/docs/examples/patterns/lists/lists-horizontal-section-25-75-responsive-ordered.html
  templates/docs/examples/patterns/lists/lists-horizontal-section-25-75-responsive-ticked.html
  templates/docs/examples/patterns/lists/lists-horizontal-section-25-75-responsive.html
  templates/docs/examples/patterns/lists/lists-horizontal-section-responsive-bulleted.html
  templates/docs/examples/patterns/lists/lists-horizontal-section-responsive-crossed.html
  templates/docs/examples/patterns/lists/lists-horizontal-section-responsive-ordered.html
  templates/docs/examples/patterns/lists/lists-horizontal-section-responsive-ticked.html
  templates/docs/examples/patterns/lists/lists-horizontal-section-responsive.html
  templates/docs/patterns/lists/index.md
  tests/snapshots.test.js
Labels: Review: QA +1, Review: Design +1, Feature 🎁, Review: Code +1 (with changes), Review: Percy +1

#5444 fix(vf_tiered-list.jinja): Update to have top hr on all screen sizes
  templates/_macros/vf_tiered-list.jinja
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Bug 🐛, Review: Percy +1

#5450 fix(hero): 50/50 with no image is laid out in split columns
  package.json
  releases.yml
  templates/_macros/vf_hero.jinja
  templates/docs/examples/patterns/hero/combined.html
  templates/docs/examples/patterns/hero/hero-50-50-no-image.html
  templates/docs/patterns/hero/index.md
  templates/docs/patterns/tiered-list/index.md
  templates/docs/utilities/align.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Bug 🐛, Review: Percy +1

#5457 fix(tabs): Bottom border of `.p-tabs__list` spans full width on all screen sizes
  package.json
  scss/_patterns_tabs.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Bug 🐛, Review: Percy +1

#5461 Fix wrapping items in right side of navigation
  package.json
  scss/_patterns_navigation.scss
  templates/docs/examples/patterns/navigation/search.html
Labels: Review: QA +1, Review: Code +1, Bug 🐛, Review: Percy +1
